### ISSUE TITLE
Out of memory may not be logged in event log.

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#1005]
Out of memory error may or may not be logged in event log depending of circumstance.

**Comment by eriohl** [comment]
Handling out of memory needs to be managed system wide, not on application level (there are tools for this).

**Comment by dan31** [comment]
@eriohl on the other hand, based on my experience, sometimes people don't understand they run out of memory, instead complaining about log entry from Starcounter which is hard to grasp (suspecting a Starcounter bug, while it is not). A better reason in the log entry would be very useful (if having that doesn't impede anything badly like performance drain). I note it since running out of memory case is unexpectedly more frequently occurring among customers than one might think. (They usually do something in their code that saturates all RAM and swap so that disk space ends).

**Comment by eriohl** [comment]
It is almost impossible to make a foolproof solution for making sure that an out of memory is always logged on application level. In addition to that, there may be many reasons why a process fails on out of memory that is not detected in the kernel. And in some cases the OS or some other service can simply kill processes to free up memory. Better then to use outside monitoring checking memory system wide and logging when it is running low.
