### ISSUE TITLE
Starcounter Latest Online Documentation problem

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#1639]
The link to a version documentation will not always work properly.

This is due to the folder is locked by starcounter server.

See #1638

**Comment by parherman** [comment]
This happens every now and then with the latest docs folder, version tacker fails to delete latest folder because access is denied. To solve it I restart Starcounter and it will be able to delete the folder. 

Would it be possible to make a html link to the latest docs instead of using a copy? So that /doc/Polyjuice/DevelopNightlyBuilds/latest would rewrite the url to the latest docs so that you can still rely on that link

**Comment by andwah** [comment]
Obsolete, we do not have any uploaded documentation to the server any longer. Closing.
