### ISSUE TITLE
Slow table in Administrator SQL + some editing bugs

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#1842]
I'm using Chrome version 33.0.1750.154 m.

I do a query `select * from materialized_column` and get a table with some number of columns. Its quite slow, but the real performance problems occurs after some time of browsing the table resulting in browser hang on this page (corresponding Chrome process takes one CPU core).

Also after I change focus between table and SQL edit box - I can't type spaces in there (only letters and numbers).

Will originally assign to @warpech but maybe @andwah is also involved.

**Comment by warpech** [comment]
After upgrading to Handsontable 0.19.0 this is largely improved. I created a Gist that produces a table of 60 columns and puts 1000 rows in it: https://gist.github.com/warpech/90ffa8782ff21aa1d3f7

Result:

- performance in Chrome is perfect
- performance in Firefox is good
- performance in Edge is very bad

@budnix could you take a look is something can be improved? Instructions to use the Gist:

1. Just save [this file](https://gist.github.com/warpech/90ffa8782ff21aa1d3f7) on your disk as "many.cs"
2. Then run "star many.cs" from Windows cmd
3. Go to Administrator and execute SQL query in default database: `SELECT * FROM BigTable`

> Also after I change focus between table and SQL edit box - I can't type spaces in there (only letters and numbers).

This was fixed with https://github.com/Starcounter/Starcounter/issues/2400

**Comment by miyconst** [comment]
@budnix, @warpech this is an old issue, I believe it is fixed now. Could you close it if it is so?

**Comment by warpech** [comment]
I received some code updates from @budnix before holidays. I will test them today and close issues accordingly. Thanks for reminding

**Comment by warpech** [comment]
This is unrelated to the last fixes from @budnix, so I can close it right now independently of them.
