### ISSUE TITLE
X.GET HTTP response not initialized

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#1855]
Hi!

I'm using X for server internal requests. I make a request to a service that returns:
    
    return HttpStatusCode.OK;

This is the code making the call:

    object scResponse = null;

    ScdbHelper.RunAttached(() =>
    {
        scResponse = X.GET(url);  // Exception here!
    });
    return scResponse;

But this yields the following exception:
System.ArgumentException: HTTP response not initialized.
   at Starcounter.Response.get_Content()
   at Starcounter.X.GET(String uri, Int32 receiveTimeoutMs)
   at HSM.SUS.Server.SimpleWebAppSUS.ForwardHelper.<>c__DisplayClasse.<GetScResponse>b__d() in d:\source\Scdb2Apps\HeadsAdmin\HSM\SUS.Server\SimpleWebAppSUS.cs:line 162
   at Heads.Scdb.Commons.ScdbHelper.<>c__DisplayClass1.<RunAttached>b__0() in d:\source\Scdb2Apps\HeadsAdmin\Heads.Db.Commons\ScdbHelper.cs:line 22
   at Starcounter.Task.Run()

**Comment by dan31** [comment]
@andwah, what's the resolution?

**Comment by andwah** [comment]
Sorry, i dont remember, I have to test to be sure if it was resolved.

**Comment by dan31** [comment]
@andwah, please verify! @parherman, follow up with @alemoi that corresponding test is added.

**Comment by alemoi** [comment]
Yes, the tests exist for this issue. I just have to extend it with Json hierarchical responses.

**Comment by parherman** [comment]
I added a new Needs test label to this issue, and we can close it ones we have a test running on the build server

**Comment by parherman** [comment]
When reading @eriohl comment I realize my previous patch dose not take into account the files specified in input.list, I have now pushed a new commit that make CMake depend on input.list and all the files specified in it.

This solution is probably not ideal since input.list needs to be replicated in src/build/behemothrcc/CMakeLists.txt. Maybe it would make more sense to pass the files list to behemothrcc directly from CMakeLists.txt?

@eriohl, I also added -D_CRT_SECURE_NO_WARNINGS to src/build/behemothrcc/CMakeLists.txt witch is the only change I can see in 1233

**Comment by alemoi** [comment]
The tests were written for this a while ago (unit tests that is). And "X" is now completely gone. "Self" uses templated syntax to retrieve certain types of response (e.g. `Self.GET<Json>`). When not templated - it returns `Response` object. When called handler is not found - `null` is returned.
