### ISSUE TITLE
Starcounter incorrectly detected as malware

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#1939]
I believe that outputting .dll files makes us look like a virus. We should investigate if Clang codegen also for other parts will solve the problem.

Anders Wahlgren gets the message on his Windows machine.

**Comment by pal88** [comment]
VS file is a virus according to AVAST!!!

**Comment by warpech** [comment]
To expand the problem - some antivirus software detects Starcounter as false positive.

This is because Starcounter uses code generators which may look like a virus to some heuristic algorithms.

I think the best way to improve this situation is to notify the antivirus vendor. There is an extensive list of false positive reporting pages here: http://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm

@pal88 According to the above page, a false positive can be reported to Avast using their website: https://support.avast.com/Tickets/Submit/&cls04&ptf01&lic04&scr05

I am afraid that until they whitelist Starcounter, you may need to disable Avast (as in #925)

**Comment by dan31** [comment]
CC @alemoi @andwah Is it a case that we completely moved to in-memory llvm now and the issue should be resolved? In-memory llvm is there for around a month already. Have you noticed anything related to false antivirus positive?

**Comment by alemoi** [comment]
Current 'develop' should completely eliminate this problem. I haven't noticed any malware detections.

**Comment by andwah** [comment]
Haven't noticed any malware detection either.

**Comment by dan31** [comment]
@alemoi @andwah 
@Starcounter-Jack reported to me that a friend of him experienced antivirus alert 2 weeks ago, which means it happened on a version with in-memory llvm. Hence I'm not closing issues related to antivirus so far.

**Comment by alemoi** [comment]
Will be good if we can get details on this matter.

**Comment by dan31** [comment]
@Starcounter-Jack, greatly asking for details!

**Comment by Mackiovello** [comment]
This should be resolved with https://github.com/Starcounter/Starcounter/issues/925#issuecomment-261786668. If there are more malware detections, please reopen.
