### ISSUE TITLE
Relax keyword POSITION

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2027]

**Comment by andan342** [comment]
There is a built-in function `POSITION ()` (case-insensitive), which allows a special syntax: `POSITION (a, b)` is equivalent to `POSITION (b IN a)`, so it has to be handled by the parser.

Currently, one can use `POSITION ` as a column/property name, but not as a variable, table/class or a function name (due to the special treatment of `IN` by the parser.

**Comment by andan342** [comment]
- The corresponding function in [Oracle](https://docs.oracle.com/cd/B28359_01/olap.111/b28126/dml_functions_1103.htm#OLADM564) is called `INSTR()`, and has a conventional function call syntax: `INSTR(str_where , str_what [, startpos [, occurrence]])`.

- In [MySQL](http://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_locate) `POSITION()` and `LOCATE()` is the same function, having its essential arguments swapped: `POSITION(str_what, str_where [, startpos])`.

- [MS SQL Server](https://msdn.microsoft.com/en-us/library/ms186323.aspx) has `CHARINDEX()` function, with the order of arguments similar to MySQL: `CHARINDEX(str_what, str_where [, startpos])`.

Since there is obviously a disagreement on which argument should be first, I guess PostgreSQL guys added `IN` syntax to avoid errors which arise when porting the SQL queries from another DBMS. 

If we decide to follow either Microsoft & MySQL approach, we no longer need `POSITION` as a keyword. If we stick to `PostgreSQL` syntax, I see no easy way to further relax it.

**Comment by andan342** [comment]
One might also think of allowing `(x IN y)` equivalent to `(y, x`) syntax for argument lists of all function. This would also solve the problem, but is probably bad idea UX-wise.

**Comment by k-rus** [comment]
We want to remove keyword `POSITION` and use `func_name` for this. Then the question: does the grammar allow `func_name(x IN y)`?
If not, then we go for `func_name(str_what, str_where)` as our customers more familiar with Microsoft environment as C# and SQL Server.

**Comment by andan342** [comment]
One simple solution is to allow 'a_expr IN SCONST` as an argument to a function. I.e. having a string literal after 'IN'.

**Comment by andan342** [comment]
Following another couple of days of investigation (using the [GRM](https://github.com/andan342/GRM) tool developed earlier for Starcounter), I have to conclude that it is not realistic to support both
- `POSITION(x IN y`), where `y` is a general expression, and `POSITION` is a function name, treated by the parser as any other function name, and
- `POSITION(x, y)` (or `POSITION(x, y, ...)`), also following the general function syntax.

# Background
PosgreSQL defines two types of expression symbols: the more general `a_expr`, and more restricted `b_expr`, which does not allow most boolean-valued operators like `AND`, `OR`, `IN`, etc.

In general, an argument to a function (not special functions defined by keywords, that `POSITION` currently is), is `a_expr`, and changing it to `b_expr` would be too limiting.

In other words, we have to live with the fact that an argument to (any) function can be, for example, `x IN (1,2,3)`, or `x IN (SELECT ...)`.

# Problems with different directions for fixing the grammar
1. Using any expression without parentheses after `IN` would would collide with the above cases: either `a_expr` or `b_expr` can have or have no parentheses around them, or start with an opening parenthesis anyway.

2. An opposite approach, by making `IN` a general expression operator, and the current RHS operands of `IN` - particular cases of expressions, involves the following

2.1. (SELECT ...), as defined by `select_with_parens` symbol` is already a variant of `c_expr`

2.2. Parenthesized comma-separated lists like `(1,2,3)`, if syntactically considered as expressions, would have to be generalizations of parenthesized  expressions. This would be generally possible in a 'lean' grammar for expressions, but leads to some new hard-to-trace conflicts in our grammar. I can spend more time investigating those, if you like...

2.3. Besides, making lists like `(1,2,3)` to be treated as general expressions, we risk **making syntax too general** to be reflect the actual language. Semantic checks will have raise error on all occurrences of such lists, unless the are a second operand of IN.

2.4. On the other hand, `IN` will have to be treated in all possible cases, however, with different semantics:
- if `IN` is a first argument to the built-in `POSITION()` function, and its operands are string-valued expressions, `IN` should be interpreted as 'syntactic sugar' for the argument list,
- if second operand of `IN` is a parenthesised SELECT query, or a list like `(1,2,3)`,  `IN` should be treated as a set membership operator,
- however, since the parser puts no information into the AST regarding the parentheses used in expressions, any expression should be treated as a singleton list.

# Summary for policy-makers
The original PostgreSQL grammar is already quite complicated, (so that it needs a GLR parser), so making it substantially 'wider' (like allowing wider ranges of expressions) is both prone to obstacles for future extensions, and risks making the current GLR-parsing (which is non-deterministic in a sense) resolve the ambiguities in a non-intuitive way.

Hence, I would advice to simplify the syntax, instead of complicating it. Making `POSITION()` a 'normal' function would free the keyword, remove the current ad-hoc argument syntax for it, making the grammar simpler.

**Comment by k-rus** [comment]
> Making POSITION() a 'normal' function would free the keyword, remove the current ad-hoc argument syntax for it, making the grammar simpler.

Isn't it what I suggested by:

> Then the question: does the grammar allow func_name(x IN y)?

You say:



> PosgreSQL defines two types of expression symbols: the more general a_expr, and more restricted b_expr, which does not allow most boolean-valued operators like AND, OR, IN, etc.

Does it mean `func_name(a_expr)` is allowed, where `a_expr` includes `IN` operator?

Basically, if we can use identifiers instead of `POSITION` and semantically check for `POSITION` at later step (in type biding phase after parsing), then it will be good solution.

**Comment by andan342** [comment]
Answering @k-rus
> Isn't it what I suggested by:
Yes, that's exactly what you have suggested! This solution is implemented now - commit #e526895

> Does it mean func_name(a_expr) is allowed, where a_expr includes IN operator?
Yes, `IN` operator is allowed in function argument - in the form of:
- `x IN (SELECT ...)`
- x IN (y, z, ...)
<br></br>
Hence, adding `IN` with a general expression on the right-hand side would create a lookahead problem for the parser.

**Comment by andan342** [comment]
Fix is applied, testcase added to to **sqlparser_inittest**, changes are pushed to **develop**.

**Comment by k-rus** [comment]
Great! However, I don't see the changes in develop.

**Comment by andan342** [comment]
It was actually part of this merge commit `23bd0c0` to **develop**, done later on that day: Jan 16 22:23.

The original commit is `e526895` to branch **grammar4**, done on Jan 11 17:18.

A test case was added in commit `c204464` on Jan 16 14:07. 

So my previous comment here was ahead of the actual merge to **develop** - my fault.

@k-rus: please confirm there's no problem now.

**Comment by k-rus** [comment]
I don't see any new test covering the above syntax fix, i.e., using IN inside argument expression of a function. I cannot confirm that the test cases are added. Can you double check and clarify? Preferably add the test cases.

**Comment by k-rus** [comment]
I read the above again. Do I understand correctly that `f(x IN y)` is not allowed, but `f(x IN (y))` is allowed?

**Comment by k-rus** [comment]
> I read the above again. Do I understand correctly that f(x IN y) is not allowed, but f(x IN (y)) is allowed?

I think it is more like rhetoric question. The answer to question is yes. Let me know if not.

Then we will follow SQL server and C# way, where the first argument is what and the second is where, i.e., like now but `,` is instead of `IN`.

**Comment by k-rus** [comment]
I think the issue can be closed.

**Comment by andan342** [comment]
> Do I understand correctly that f(x IN y) is not allowed, but f(x IN (y)) is allowed?

That's right!
