### ISSUE TITLE
Reuse Json in other Jsons

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2059]
Let say I have my Object1:
```
{
     prop1:"",
     prop2:"",
     AList:[{
             aprop1: "",
             aprop2:"",
     }]
}
```
This works good and I have AList being automatically filled with data from the binding to Object1:s data object.

But the items in AList is quite common and also used in other places so I don't want to duplicate the code. The solution is to break out the code into one Json AListJson:
```
{
     aprop1: "",
     aprop2:"",
}
```
And have a undefined array in Object1:
```
{
     prop1:"",
     prop2:"",
     AList:[{ }]
}
```
But now I have to manually fill the AList. Is there someway to have it automatically defined to another external JSON?

**Comment by miyconst** [comment]
@chrhol what is the status of this issue? I just tried the `Reuse` keyword and it worked fine for me. Can we close it?

**Comment by per-samuelsson** [comment]
> @chrhol what is the status of this issue? I just tried the `Reuse` keyword and it worked fine for me. Can we close it?

@miyconst, did you also try adding additional properties?

**Comment by per-samuelsson** [comment]
> @miyconst, did you also try adding additional properties?

Seem from [this code snippet](https://github.com/Starcounter/Starcounter/blob/4271794fa55c52a9646d161d3838e4d2b22294fc/src/Starcounter.XSON.PartialClassGenerator.Tests/PartialClassGenerationTests.cs#L67-L73) that @chrhol in fact added unit tests for additional properties. Then we could definitely close this issue IMO.

**Comment by miyconst** [comment]
>@miyconst, did you also try adding additional properties?

To where? To the object which "reuses" another JSON or to the root level? Root level works fine.

**Comment by per-samuelsson** [comment]
> To where? To the object which "reuses" another JSON or to the root level?

The the reusing object. It should support reuse + extra fields.

**Comment by per-samuelsson** [comment]
```json
{
  "Reuser": {
    "$": { "Reuse": "Foo.Reused" },
    "And": "More"
  }
}
```

**Comment by miyconst** [comment]
>It should support reuse + extra fields.

Should it? I never heard of such behavior, but I will test it.

**Comment by miyconst** [comment]
No, it does not work.

**Comment by per-samuelsson** [comment]
> No, it does not work.

OK, that's weird. I was under the impression it should, and that @chrhol added tests for that in https://github.com/Starcounter/Starcounter/commit/4271794fa55c52a9646d161d3838e4d2b22294fc. I'm not an expert on the full story though, so maybe it's best to wait to see what @chrhol has to say about it.

**Comment by chrhol** [comment]
> > No, it does not work.

> OK, that's weird. I was under the impression it should, and that @chrhol added tests for that in 4271794. I'm not an expert on the full story though, so maybe it's best to wait to see what @chrhol has to say about it.

No, this was never supported, the unittests are for testing reusing different objects (objects, arrays). And I think maybe it doesn't have to. The thing is how the reuse works now is that you take the complete TypedJson object you want to reuse and simply uses that type in the generated code. If we would allow additional properties we need create a new type which includes both the properties from the reused object and the extra. I think this can instead be solved with inheritance instead (maybe we need to change or make it so that existing properties is automatically included).

Working with the codegenerator is frustrating to say the least, so I try to avoid tamper with it as much as possible, especially when it comes to more complex changes. It takes a long time just to get back in in how it works.

I will review this when I get back in the office to see how we should solve it.

**Comment by chrhol** [comment]
Considering that we have had the reuse-functionality for quite some time and the need for adding additional properties to a reused object have not surfaced, I think it will be good enough to keep it as-is. 

That is, with reuse you reuse a whole object, and cannot add additional properties. With inheritance you can add any properties you like.

Closing this issue.
