### ISSUE TITLE
Introduce ordering for release channels

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2295]
- [x] I noticed that the icon of the stable installer is the old one, however it should be new like with daily builds.
- [x] The order of builds on the download page looks strange for me. Is it correct that Polyjuice goes above Starcounter channels? And develop channel is above nightly channel, which is above stable. Thus the stable branch is the last on the page and requires scrolling.

**Comment by k-rus** [comment]
Polyjuce edition does not exist, however the order still seems to be strange: it is started from the most unstable and the most stable does not fit the first screen.

**Comment by andwah** [comment]
It's in alphabetical order.

**Comment by k-rus** [comment]
> It's in alphabetical order.

then descending alphabetical order?

**Comment by andwah** [comment]
At the moment we have ```Daily```, ```Nightly``` and ```Stable``` and very soon ```pnext```

**Comment by dan31** [comment]
@andwah Can you make the channel ordering configurable via some conf table
(Channel-name, Channel-order-number)? So that, if ordering is given by a
number - it is used to order, and for all these channels that aren't given
an order, they are put to the bottom of all other channels in alphabetical
order. It would help a lot not to mislead the majority of downloaders.

**Comment by andwah** [comment]
@dan31 Sure that is possible it only take time,  when should i do this?

**Comment by warpech** [comment]
Merged from #3290

Currently, the sorting order of channels on the [Download page](http://downloads.starcounter.com/download) is: `Daily`, `Nightly`, `PnextNighty`, `Stable`.

![screen shot 2016-01-22 at 14 54 19](https://cloud.githubusercontent.com/assets/566463/12512335/0e6d8142-c118-11e5-9fa7-f9758e5b6678.png)

A newbie does not know what to download from here. I think we need to do two things:

1. Change the order to: `Stable`, `Nightly`, `PnextNighty`, `Daily`
2. Add a one line description for each channel. Something like:
  - `Stable`: Stable release channel. Updated once in few weeks. All the Docs contain information relevant to the latest version in this channel, unless said otherwise. Sample Apps and Prefab Apps run in latest version in this channel and sometimes support more stable versions back (see the package information for details).
  - `Nightly`: Unstable release channel. Updated daily. Contains features considered release candidate for a next stable release. Feel free to use it for the bleeding edge developer experience.
  - `PnextNighty`: Experimental release channel. Might contain breaking changes. Use it at your own risk.
  - `Daily`: Unstable release channel. Updated irregularly. Typically out of date. Contains custom releases for test purposes.

The above is just how I would explain the channels to a stranger. Please adjust these texts if needed.

The fallacy of the current page was confirmed today by @aloscha. A person who wants to download the latest nightly is the most likely to incorrectly download the latest daily (which is currently 4 months old).

**Comment by k-rus** [comment]
BUMP

**Comment by andwah** [comment]
@k-rus Thanks for the *bump*.

**Comment by k-rus** [comment]
Order is still a problem on the channel page. Note that the stable is the last in the list, which requires extensive scrolling.

**Comment by andwah** [comment]
Download page updated,
Fixed sort order and added channel description as @warpech suggested.

**Comment by warpech** [comment]
Looks super nice, thanks!

**Comment by k-rus** [comment]
Seems to be fixed
