### ISSUE TITLE
JSON primitive arrays not supported in XSON

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#237]
When I make a JSON model with a primitive array, using the XSON.Json class as my code baseclass, I get a compile-time error like

> Unable to cast object of type
> 'Starcounter.Templates.TArr`2[Starcounter.Json,Starcounter.Templates.TJson]' to type
> 'Starcounter.Templates.TJson'.

Sample JSON to reproduce:

```
{
    "Foo": [
        "Bar",
        "Baz"
    ]
}
```

Apparently, this is because we don't yet support arrays with primitives, only objects. This must be addressed.

**Comment by peterbergman** [comment]
Please prioritise this feature request. 

I am working on a Starcounter project where I am using the HTTP handlers as endpoints towards other systems. Since primitive arrays are not yet supported, I cannot receive the data from the external systems properly.

**Comment by chrhol** [comment]
I've been working on this for a couple of days now with not as much  progress as I have hoped. There are quite a few places in our code that  needs to be rewritten/refactored (and tested of course) to support primitive arrays. Or rather json as a primitive value I should say since it will not be much difference to support json as a single primitive value and primitive values in arrays.

- **Json-by-example parser.** Parses the json-file and calls the template factory. Luckily I think that only small tweaks are needed here.
- **Template factory.** Factory for creating a template (or schema) from the parsed json. This is mostly done.
- **Codegenerator.** Generates code when compiled in  a userapplication to allow intellisense and additional features (like typed dataobjects and compiletime error-checking).
- **API to user.** How do we access and work with primitive values in userapplications. Since we have additional metadata and settings for values we cannot simply work with the value directly but need to wrap it somehow. API have been discussed but not decided yet.

All of these steps are connected so it's hard to finish one without touching the others. Currently working on getting the codegenerator to compile so that I can test the parser and factory properly.

**Comment by chrhol** [comment]
I have now pushed this implementation to develop and next. It's a quite big implementation so chances are there might be some bugs in it :) I will continue testing and write some documentation on how to use it.

**Comment by peterbergman** [comment]
Ok, great! How can I specify in the typed JSON file that I expect an array of strings for a field?

**Comment by chrhol** [comment]
I'm a bit behind in the documentation. Sorry about that.

You specify it in json like this:
```javascript
// PrimitiveArray.json
{ 
    "myArr": [ "someValue" ]
}
```

In c# you can then get and set the value using the property `StringValue` on class `Json`

```c#
...
Handle.POST("/someuri", (PrimitiveArray json) => {
    foreach (Json item in json.myArr) {
      Console.WriteLine(json.StringValue)
    }
    return 200;
});
...
```

The same pattern is used for all different types (`IntegerValue`, `DoubleValue`, `DecimalValue`, `StringValue`, `BoolValue`). There are also properties to check what type a Json-instance is representing (`IsObject`, `IsArray`, `IsString`...)

**Comment by peterbergman** [comment]
Ok, thanks! :) And what if I would like to add values to the array programatically? 

Given the JSON above, the following does not seem to work (called from the code behind class):

```c#
myArr.Add("foo")
```

Should I wrap the "foo"-value in some object before adding it to the array?

**Comment by chrhol** [comment]
Yes, you need to wrap it in a json-instance with the same type as each item in the array. 

The easiest way would be like this I guess:
```c#
var item = myArr.Add();
item.StringValue = "foo";
```

If you have any input or suggestions on how to improve or change how you work with single value json, please comment in #2720. I will update that issue with how the API looks today.

**Comment by peterbergman** [comment]
Ok, thanks, that seems to work!

**Comment by warpech** [comment]
@chrhol can this be changed? Does Starcounter support adding and removing array properties through `add` and `remove` operations?

**Comment by Starcounter-Jack** [comment]
The idea is to also support arrays without a hosting object.

**Comment by Starcounter-Jack** [comment]
If we make an extension cast method on string such that we can
do ```myArr.Add("foo") ``` such that it matches ```void Add( Json value )```

**Comment by Starcounter-Jack** [comment]
@chrhol WDYT?

**Comment by chrhol** [comment]
I guess it should be possible to simplify this, I have to look into it. I guess we want to avoid bloating the API and I'm not sure you can filter extension-methods properly since the (primitive) type the array contains is specified on the template and not the instance (the instance is always Json or subclass).

Maybe it would be better to add it in the generated code for that specific type? Add, remove and enumerator.

**Comment by warpech** [comment]
@chrhol I think this is done now?

**Comment by chrhol** [comment]
Right, yes! There is another issue for the last comments in here (#2720)
