### ISSUE TITLE
Database size warning on TeamCity server

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2377]
I've got the following warning when opened a project settings page:
>The server currently uses the internal database whose size has grown over the warning level and is already 259.56 MB. To achieve better performance and reliability, switching to a standalone database is strongly recommended.

**Comment by parherman** [comment]
scbuildserver2 had memory problems due to hardware error, this is now fixed. Once we will move/upgrade TeamCity we will use a external db as suggested by the message, I have it as a task in [Build system and development infrastructure improvements](https://github.com/Starcounter/CompanyTrack/issues/72) and will close this issue now
