### ISSUE TITLE
Polymer upgrade to native Web Components after template is imported to DOM

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2511]
Sometimes when loading a page the components are empty. 

Investigated by @warpech with the following comments: 

"Polymer is upgrading native Web Components to Polymer Elements in async way which is sometimes after our script inserts the imported template to DOM"

"The fix will be in imported-template.html which is one of the files from Polyjuice /sys/ directory"

**Comment by warpech** [comment]
Thanks for creating the ticket! Adding @tomalec

**Comment by tomalec** [comment]
From what I've found the issues was caused by template instance (one imported by `imported-template`) being stamped before `adfenix-chart` was created. As (according to [spec](http://www.w3.org/TR/html-imports/)) the HTML Imports are blocking . The possible reason was that Polymer 0.5.1 registers elements somewhat asynchronously.

I have upgraded Polymer to 0.5.3 and cannot reproduce the issue any longer. 
So, after smoke testing that 0.5.3 does not break Launcher I will push it to the Starcounter repo, then I'll try to prepare a isolated test that with blocking `<link rel="import" src="nestes.html">` inside imported template document and synchronous code, imported document is not loaded before end of `nestes.html` execution.

@Ripipip, I can guide you how to hot fix it on your installation.

**Comment by Ripipip** [comment]
Update: we are still able to reproduce the issue even with upgraded Polymer.

**Comment by warpech** [comment]
Try this workaround: pre-import all the elements in LauncherTemplate.html `<head>`:

```html
<link rel="import" href="/elements/menu/menu.html">
<link rel="import" href="/elements/tabs/tabs.html">
<link rel="import" href="/elements/chart/chart.html">
...
```

We are still working on the real fix, but the above workaround seems to cure the symptom.
