### ISSUE TITLE
Incorrect SQL syntax

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2559]
Steps to reproduce

1. Create a table/object Order in database.
2. Try to execute sql: SELECT o FROM Order o

You will get an error:
Failed to process query: SELECT o FROM Order o: Incorrect syntax.
The error does not contain any explanation of why the syntax is incorrect.

The same situation under MS-SQL server raises this exception:
Incorrect syntax near the keyword 'Order'.
Which explains what is going on.

**Comment by dan31** [comment]
@miyconst, thanks for the question!
@k-rus, do I remember correctly that @andan342 -s parser works only in certain cases and we don't have info on error location for arbitrary queries?

**Comment by k-rus** [comment]
Thank you for reporting the issue.
Unfortunately the error message cannot be improved currently. It is produced by old parser, which does not provide more information. The old parser is being replaced with new parser, where the above statement is parsed successfully, since there is no ambiguity in using the keyword. As soon as new parser is in use in new query processor, the error message will disappear.

**Comment by k-rus** [comment]
Let us know if you are satisfied with the answer that we close the issue.

**Comment by miyconst** [comment]
Yes, the issue should be closed. Hope to see the new parser soon.
