### ISSUE TITLE
ScErrCantBindAppWithPrivateData 

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2561]
Hi!

Why am I no longer allowed to have private datafields? I have a private field that I set through methods. The value is then exposed as a readonly string

/C
````
private SoftwareManifestState m_before; 
public string Before { get { return m_before != null ? m_before.Name : null; } }
````
ScErrCantBindAppWithPrivateData (SCERR2149): The application can not start because it contains at least one database class with private data. See separate errors with ID "ScErrNonPublicFieldNotExposed". 3 illegal fields exist.
ScErrNonPublicFieldNotExposed (SCERR4285): The database field was not public and no public property exist that expose it. HSM.Concepts.SoftwareManifestState.m_after not exposed

**Comment by k-rus** [comment]
Thank you for your question!
In the current version private fields without public accessors are not allowed, since it is not possible to do unload/reload of data with such fields. Unload/reload is commonly used if migration to new incompatible version of Starcounter or migration to new application schema is needed.

Current work around is to create a public get accessor to your field or make the field public. For more information see #2436, #2485, etc.

Do you have more questions or can we close the issue?

**Comment by careri** [comment]
I had already added public accessors to get past this problem. OK, so the unload works with classes and not just tables?

The unload logic in SCDB1x must have been implemented at a lower level since private DbFields where allowed then?
I mean the load logic is writing directly to tables I guess, so why not the unload?

**Comment by k-rus** [comment]
> I had already added public accessors to get past this problem. OK, so the unload works with classes and not just tables?

Current version of unload uses the same code host interface to get data as your application. This simplified its implementation and allowed to have the unload be presented now.



> The unload logic in SCDB1x must have been implemented at a lower level since private DbFields where allowed then?
> I mean the load logic is writing directly to tables I guess, so why not the unload?

New version of unload is planned and depends on new query processor, which is also in plans.

**Comment by careri** [comment]
OK, that clarifies things.
