### ISSUE TITLE
Image size on table deletion

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#2572]
@eriohl, a short question to you (I'm following @Ripipip, using "develop"):
What happens with the image file when we delete tables from DB?
If it only marks space unused (presuming that shrinking empty pages in ```SCI``` is obviously expensive), is there a way to ```VACUUM``` the image files?

**Comment by eriohl** [comment]
Image files never shrink unless you rebuild the database.

**Comment by dan31** [comment]
@eriohl, how difficult it might be to add such feature: https://www.sqlite.org/lang_vacuum.html for ```develop``` kernel? For ```pending next``` this shouldn't be a problem, as I understand, and is available by design with ```logopt```.

**Comment by eriohl** [comment]
In order to shrink the files you need to release space at the end of the file. Truncating the files in this case is trivial. But you are unlikely to free up a lot of space at the end of the file deleting database data. Instead you need to defragment the logical storage positions of database pages, which is best done by rebuilding the database (which I understand that vacuum does also).

Adding some kind of automatic defragmentation of logical storage positions in not trivial because we do not usually track reference to a given storage position. And as you point out: This is not a problem in later versions of the kernel.

**Comment by dan31** [comment]
@eriohl, thanks for input! @Ripipip, what you can do now is: do Unload, recreate an empty database, and do Reload to it. The Unload/Reload procedure is described here: https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions. Please tell if the process isn't clear and you need assistance. In future versions, the vacuum will be provided in an ordinary way.

**Comment by Ripipip** [comment]
Ok, thanks for the replies. It is not necessary right now but will be in the short future so I just wanted to know beforehand how to fix it.
