### ISSUE TITLE
Undefined properties in JSON

### ISSUE THREAD

**Issue by peterbergman** [Starcounter/Starcounter#2600]
When using JSON in HTTP handlers, an exception is thrown if the received JSON contains properties that is not specified in the typed JSON file.

Exception example:
System.Exception: ScErrJsonPropertyNotFound (SCERR14003): The property is not defined in the template. Property="ua"

This makes the application less robust since there is no way to handle these cases. As an application programmer I would like to either be able to catch these exceptions myself and handle them accordingly. Or preferably, the HTTP handlers should be able to handle undefined properties and match the properties that are defined.

**Comment by dan31** [comment]
@peterbergman, thanks for questioning! @chrhol, please check, this one is important.

**Comment by chrhol** [comment]
Sorry for the delay in answering. 

Yes currently, when a typedjson object created compiletime (i.e. has a predefined template) is used it's required that the incoming json does not contain any extra properties. Maybe this should change so they are ignored, not sure what the correct behaviour should be. We have to discuss this and see what should be done. Maybe the support for having typedjson types directly in the handler should be improved.

If you want more control (with the current implementation that is) in handling the incoming json you can create the typedjson object yourself instead of having it declared on the handler. 

So instead of:
```c#
...
Handle.POST("/myhandler", (MyTypedJson json) => {
   ...
});
...
```
You do this:
```c#
...
Handle.POST("/myhandler", (Request request) => {
    MyTypedJson json = new MyTypedJson();
    try { 
        json.PopulateFrom(request.Body);
    } catch {
       ...
    }
});
...
```

You can also use a dynamic instance of typedjson. The downside is that you get no compiletime errors for using properties that does not exist, only runtime exceptions. There are one issue unsolved here though, described in #2571.

```c#
...
Handle.POST("/myhandler", (Request request) => {
    dynamic json = new Json(request.Body);
    Console.WriteLine(json.MyProperty);
});
...
```

**Comment by peterbergman** [comment]
Ok, thank you for the information and the proposed solutions. 

For my use case, it would be nice if undefined properties were ignored by default.

**Comment by erikvk** [comment]
@chrhol 
+1 for the option to ignore undefined properties when populating a typed JSON.
