### ISSUE TITLE
JSON by example negative decimal number throws an error

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2614]
The following JSON does not work (.json file):
```
    "GeoLocation" : {
        "Latitude" : 40.0,
        "Longitude" : -74.0
    },
```
in comparison with the following, that works:
```
    "GeoLocation" : {
        "Latitude" : 40.0,
        "Longitude" : 74.0
    },
```

The error occurs when building the project:
`LocationInfo.json.cs : json error : Expected "array, object, string, boolean, number, function or event" but found a Unary (Minus,Decimal (74.0M,Starcounter.Internal.JsonTemplate.DebugInfo))`

**Comment by chrhol** [comment]
Thank you for reporting this.

The problem lies in the Json-By-Example parser that does not handle parsing negative numbers correctly. Negative numbers are supported though in TypedJson. 

As you described in your comment, the workaround for now is to set a positive number in the json and then setting the (negative) number on the instance.

**Comment by chrhol** [comment]
I've changed the parser so that negative numbers are handled and correctly set as default value. Pushed to develop and next.

**Comment by alemoi** [comment]
Super!
