### ISSUE TITLE
Auto incremented property

### ISSUE THREAD

**Issue by peterbergman** [Starcounter/Starcounter#2621]
Is there any built in mechanism in Starcounter that allows for a property on a database class to be auto incremented for each new object created of that specific class? Or, should this be handled by implementing it in the database class? If so, is there any recommended way of implementing such a property (static field etc.)?

**Comment by k-rus** [comment]
The only auto-incremented property supported in the database is the object identifier, which is guaranteed to be unique. However, it cannot be used to count number of objects or for sequential numbering.
Implementing your request, i.e., auto-incremented property, is **not recommended**, since it will be serious **performance bottleneck**. This is because the objects can be created concurrently. There are two common ways to implement your behaviour: pessimistically or optimistically. In the first case, the creation is serialised through locks. In the second case, the updates are failed during commit due to conflict.

**Comment by peterbergman** [comment]
Ok, thanks for the information!

**Comment by k-rus** [comment]
I close the issue. You are welcome to reopen if you have further questions.
