### ISSUE TITLE
When Db.Scope transaction dies?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2661]
I know that there are two sorts of transactions:
`Db.Transact` and `Db.Scope`. The first one starts on the line we call it and ends on the line with the last `}`.

But what about `Db.Scope`?

I have two pages:
- `/People/Persons` - list of peoples.
- `People/Persons/@w` - single person details.

The second page is Db.Scoped.
```csharp
return Db.Scope(() => {
    return X.GET<Json>("/people/partials/persons/" + id);
});
```

Handle event on Save button clicked:
```csharp
this.Transaction.Commit();
this.RedirectUrl = UrlHelper.GetUrl("/persons");
```

Handle event on Cancel button clicked:
```csharp
this.RedirectUrl = UrlHelper.GetUrl("/persons");
```

I never call 
```csharp
this.Transaction.Rollback();
```

However next time I open a person details page the changes I didn't save disappears.
So, the final questions are
- When the `Db.Scope` transaction dies?
- Can I keep it live longer?
- Do I even need `Transaction.Rollback()` and if so then what for?

**Comment by chrhol** [comment]
> When the `Db.Scope` transaction dies?

It depends on how it is used. There are three different times it can be disposed, depending on if someone reference it after the scope is ended.

1. Noone is referencing it. It will be cleaned up directly after the end of the scope.
2. A Json-object is using the transaction, but the json-object is not connected to a stateful tree (i.e. a session). It will be cleaned up in the end of the task.
3. A json-object that is attached to a session is using the transaction. The transaction will be cleaned up when either the json-object is removed or the session dies.

> Can I keep it live longer?

Not sure exactly what you mean here, Do you want to keep the person details open but not visible? You need to keep the json-object in the viewmodel for the transaction to continue to live. There is a way to take manual control of the transaction and make it be cleaned up when the transaction-object is garbage collected, but I dont think that is a good solution here (maybe).

> Do I even need `Transaction.Rollback()` and if so then what for?

By calling `Transaction.Rollback()` you can cancel the non-committed changes and continue using the same transaction, but if you for example close the person details page (and remove the json-object) then you don't have to do a rollback since the transaction will be disposed.

**Comment by miyconst** [comment]
@chrhol thanks for the explanation.

Basically transaction lives as long as it's JsonViewModel lives. Is that correct?

> Can I keep it live longer?

If, for example I want user to save or clean changes by clicking on button, but when user navigates to another page without cancelling the changes then keep them in memory. Then if user navigates back to same page he will see those changes.

For this I have to store JsonViewModel and use it till user cancels or saves changes, correct?

Another situation which confuses me a bit:

```csharp
Handle(Input.AddNew Action) {
    Db.Scope(() => {
        Person person = new Person() { Name = "John" };
        this.RedirectUrl = "/Peope/Persons/" + person.Key;
    });
}
```

This will redirect to person details page and I will see *John* inside name field. However the Person object won't be in the page's Db.Scope and it won't be saved when user presses *Save* button.

I understand that `Db.Scope` of `/People/Person` died when we navigate out, but the object should also die with the scope.

**Comment by chrhol** [comment]
> Basically transaction lives as long as it's JsonViewModel lives. Is that correct?

> > Can I keep it live longer?

> If, for example I want user to save or clean changes by clicking on button, but when user navigates to another page without cancelling the changes then keep them in memory. Then if user navigates back to same page he will see those changes.

> For this I have to store JsonViewModel and use it till user cancels or saves changes, correct?

Yes correct, you need to keep it in the viewmodel to avoid that the transaction will be cleaned up.

> I understand that `Db.Scope` of `/People/Person` died when we navigate out, but the object should also die with the scope.

Hmm yes it should have. This feels like really strange behaviour. Is this code available somewhere in some app? I can take a look and see if I can find an explanation for it.

**Comment by miyconst** [comment]
Hm, I could not reproduce the behaviour any more. Now it rises exception `Data in the transaction is created or updated, but the transaction is not referenced and will be discarded.`. Whatever the issue was it has gone.

Thank you for the detailed explanation. I close the issue.
