### ISSUE TITLE
ScErrUnsupportLiteral when using LIMIT 1

### ISSUE THREAD

**Issue by peterbergman** [Starcounter/Starcounter#2670]
When I execute the following query through the Db.SQL method, I get the error "ScErrUnsupportLiteral (SCERR7029): Literals are not supported in the query..."

Query: 
SELECT t FROM Foo t ORDER BY Bar DESC LIMIT 1

However, the same query seems to work with the Db.SlowSQL method. Should the Db.SlowSQL method be used in cases where the query contains LIMIT 1? Or is the query supposed to work with the regular Db.SQL method?

**Comment by k-rus** [comment]
Thank you for your question.
Your query contains literal `1`, thus the query fails if method `Db.SQL`. `Db.SlowSQL` can be used to execute queries with literals. However, it is not recommended to use literals in queries for performance reason, since the query cannot  be prepared and cached and have to be optimised every time.
Our suggestion is to replace the literal with a parameter, e.g.:
```c#
Db.SQL("SELECT t FROM Foo t ORDER BY Bar DESC LIMIT ?", 1);
```
See also [this wiki page](https://github.com/Starcounter/Starcounter/wiki/SQL-Variables)

Let me know if you have further questions. I close this issue for now.

**Comment by peterbergman** [comment]
Thanks for the information!
