### ISSUE TITLE
Next-nightly-ctest fails with linking error

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2687]
Out of all build projects on next only this one, i.e., ctest, fails. This happens after I added new file with source code. I added it to cmake file in the corresponding folder, which works fine locally and for most build projects, e.g., Next-daily and Next-nightly.
I guess ctest project requires more: either more complex way of adding file, or better build script.
Can it investigated and clarified?

**Comment by parherman** [comment]
The ctest job is a experimental job to evaluate using ctest as a test runner, i will disable it for now and investigate this ones i get back to work!

**Comment by k-rus** [comment]
> The ctest job is a experimental job to evaluate using ctest as a test runner, i will disable it for now and investigate this ones i get back to work!

Is this test easy to run locally with help of cmake?

**Comment by parherman** [comment]
Hello @k-rus,

First this issue, the problem was that the TeamcityBuild.bat was not updated in the buildsystem branch that is used to run the ctest runner (next-ctest branch of buildsystem git). So no further action would be required by you when adding files. The only thing that is changed is how the tests are run.

> Is this test easy to run locally with help of cmake?

This basicly replaces the RunUnitTests.exe and RunTests.bat in buildsystem repo with some more flexibility, but you still run the same bat tests in the end.

One thing that is simpler is running only a selected test:

ctest -T Test -C Release -R Http -VV

This line will only run tests Http in the name

You can also run a personal build of Next-Nightly-CTest and edit the CTEST_REGEX and CTEST_EXCLUDE_REGEX parameters to only run the tests you want
