### ISSUE TITLE
Using shortnames in queries: problem with ambiguous names and mapped database views

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2730]
When we are now moving to having several smaller apps running together that have their own mapped views of the database, the likelyhood of having more then one databasetype with the same shortname increases. 

This poses a problem since it is really easy to break an working app, by starting another one that happen to have the same shortname for a dabasetype in their mapped model.

This has been mentioned before, but only briefly in shorter discussions, so I add it as an issue so we can discuss and come up with a solution.

As far as I can see there is not too many different options to solve this. I can come up with two:
- The shortnames are resolved by application, so that each app have there local database views usable with shortnames. Not sure if this is even possible to implement.
- Require all database types to be specified with fully qualified name in queries. This will be the simplest solution and will make it certain that all queries will work. The downside is of course that you have to write the fullname which can be quite long.

@malx122, @warpech, @miyconst, @dan31, @k-rus, @Starcounter-Jack

**Comment by chrhol** [comment]
Currently this problem arises when you use society-objects and simplified.dll together, since a lot of the types have the same name in different namespaces.

**Comment by k-rus** [comment]
> Require all database types to be specified with fully qualified name in queries. This will be the simplest solution and will make it certain that all queries will work. The downside is of course that you have to write the fullname which can be quite long.

This is the only possible short term solution. I believe it can be done in two working days and more time to fix bugs, since the change needs to be done in several different algorithms.

The long term solution can be: propagating context such as namespaces together with query. This can be similar to C#.

The long term solution needs to be discussed and decided, however not now.

**Comment by miyconst** [comment]
I never use short names in sql queries, so the second solution seems to be okay for me.

**Comment by dan31** [comment]
@k-rus, I think you suggest a very good long-term solution! Ideally name resolution in queries must be done similar to how unqualified names are resolved in the given codehost (currently C#). Short-term, we will have in a plan for 2.0 adding a feature: making db be a polyjuice-db (@alemoi's flag) will require all db types in queries to be qualified, exception/error otherwise.

**Comment by k-rus** [comment]
> Short-term, we will have in a plan for 2.0 adding a feature: making db be a polyjuice-db (@alemoi's flag) will require all db types in queries to be qualified, exception/error otherwise.

The functionality is currently not supported. Adding flag will not help without implementing the functionality in the legacy query processor.

**Comment by warpech** [comment]
@chrhol, @alemoi is this issue still relevant? I think we don't support shortnames in apps anymore.

**Comment by alemoi** [comment]
Should not be relevant. SO and Simplified have full names.
