### ISSUE TITLE
Explain Polyjuice.Map and Polyjuice.OntologyMap

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2743]
Add a (simple or more elaborate) explanation of using Map and OntologyMap:

- `Map`: http://starcounter.io/guides/apps/uri-mapping/
- `OntologyMap`: http://starcounter.io/guides/apps/data-mapping/

You can rename the pages if you find the name inadequate.

**Comment by ivarbergman** [comment]
Hi! Any progress on mapping documentation?

I trying to understand Polyjuice.Map and why mappings are restricted to only map to /polyjuice/ URIs? Wouldn't it be possible to allow arbitrary URIs in Polyjuice.Map ?

**Comment by alemoi** [comment]
Thank you for the question! Since I see a big interest around this, I would prioritize the thing, make it generic, and document it!

**Comment by alemoi** [comment]
Today I have spent time regarding this. And possibly we would even put more constraints on mapping, but first lets have a discussion around this.

The thing is that `Polyjuice.Map` is a very specific thing used to get results from several application handlers mapped to a known one. This is needed, for example, for `/polyjuice/menu` specifically for Launcher. I am thinking to disallow mapping to root handler in `Polyjuice.Map`.

If we are talking about usual Starcounter application, then mapping to root can be done as following:

```c#
Handle.GET("/", () => {
   return Self.GET("/index.html");
});
```

This approach allows users to have full control over the code without introducing some extra functionality.

If we talk about Polyjuice applications, I think they should not be allowed to map to root. Instead there should be an interface to configure this in Administrator or something like that, but not programmatically, since then one app can potentially disturb other.

@ivarbergman how would you like to utilize mapping? Are there any specific uses you are looking for?

In any case I still have to write documentation around this.

**Comment by alemoi** [comment]
Right now `Polyjuice.Map` is used only for the common URIs used in Launcher. Maybe we should even rename this to `Polyjuice.LancherMap` or `Polyjuice.MapCommon`?

**Comment by dan31** [comment]
Also see https://github.com/Polyjuice/Polyjuice/issues/15#issuecomment-111595135, join us @alemoi

**Comment by warpech** [comment]
Explanation should include turning OntologyMap on and off (see the above link)

**Comment by warpech** [comment]
@alemoi would it be possible to put at least some minimum information on the pages

- `Map`: http://starcounter.io/guides/apps/uri-mapping/
- `OntologyMap`: http://starcounter.io/guides/apps/data-mapping/

Usage of Map & OntologyMap is now demonstrated on every presentation but there is zero docs on how to use it

**Comment by alemoi** [comment]
Sure, I will add this information.
