### ISSUE TITLE
 Raw sockets tests Unstable on build server

### ISSUE THREAD

**Issue by parherman** [Starcounter/Starcounter#2751]
Performance Tests: Raw sockets tests has failed during several, but not all nightly builds since yesterday, link to logs logs:

[Starcounter_Next_Nightly_Debug](https://scbuildserver/viewLog.html?buildId=28448&buildTypeId=Starcounter_Next_Nightly_Debug&tab=buildLog#_focus=5937)

[Starcounter_Next_Nightly_Debug](https://scbuildserver/viewLog.html?buildId=28445&buildTypeId=Starcounter_Next_Nightly_Debug&tab=buildLog#_focus=5935)

[Starcounter_Develop_Nightly_Debug](https://scbuildserver/viewLog.html?buildId=28415&buildTypeId=Starcounter_Develop_Nightly_Debug&tab=buildLog#_focus=5241)

[Starcounter_NextNightly](https://scbuildserver/viewLog.html?buildId=28419&buildTypeId=Starcounter_NextNightly&tab=buildLog#_focus=6611)

**Comment by alemoi** [comment]
This one is on me. Probably some client missbehavior, regarding how it checks statistics.

**Comment by alemoi** [comment]
Still haven't found the exact problem, but working on it. For tonight I will disable the node test so overall build passes.

**Comment by parherman** [comment]
@alemoi Is this a problem with the test? Is the client the test i mean? Assigning this to you!

**Comment by alemoi** [comment]
No, seems some bug introduced during big refactoring. Hope to resolve this today/weekends. Will then reenable the tests!

**Comment by alemoi** [comment]
This one should be resolved now! Introduced because of massive refactoring. Thanks for reporting!

**Comment by parherman** [comment]
@alemoi looks like [Starcounter_Next_Nightly_Debug](https://scbuildserver/viewLog.html?buildId=28684&buildTypeId=Starcounter_Next_Nightly_Debug&tab=buildLog#_focus=5923) failed with System.Net.Sockets.SocketException so there might still be a problem, or did your changes not make it in time for that build? We also have a hung build, [Starcounter_DevelopNightly](https://scbuildserver/viewLog.html?buildId=28685&buildTypeId=Starcounter_DevelopNightly&tab=buildLog#_focus=4972), during Burst Tests, do you think it could be related?

**Comment by alemoi** [comment]
Thanks for notifying! Next was not merged properly yet so I will keep an eye on this! Maybe the problem still persists!

**Comment by alemoi** [comment]
I checked the situation and `next` branch wasn't merged from yesterday (so it didn't contain the fix for this that was pushed yesterday). @per-samuelsson can you  merge your `develop` changes to `next` because they cause a merging conflict? :)
Hanging situation is with `UrlsTest` using aggregation, I guess another refactoring problem that only occurs intermittently. I will check it! Thanks for reporting! Please keep doing like that! :)

**Comment by dan31** [comment]
The procedure of completely discontinuing "next" is discussed in here: https://github.com/Starcounter/CompanyTrack/issues/76 . We will, asap, either freeze it and then delete, or just delete, so that only "develop" and "pnext" remain in use. What we've learned from maintaining a couple of big syncronised branches is that it is, ugh, doesn't work well and consumes time. Instead, we are approaching multi-repository scheme with @parherman.

**Comment by parherman** [comment]
@alemoi UrlsTest hangs again: [Starcounter_Develop_Nightly_Debug](https://scbuildserver/viewLog.html?buildId=28769&buildTypeId=Starcounter_Develop_Nightly_Debug&tab=buildLog#_focus=4956)

And Raw sockets fails: [Starcounter_Next_Nightly_Debug](https://scbuildserver/viewLog.html?buildId=28770&buildTypeId=Starcounter_Next_Nightly_Debug&tab=buildLog#_focus=5932) - maybe we should keep this bug open until your changes make it into next? I will open it for now!

**Comment by alemoi** [comment]
The `next` branch is still not merged and won't probably merge. So I guess it will continue to fail, but I can disable this test.

Regarding hanging I found the reason for it. Just need to push a fix.

**Comment by parherman** [comment]
I believe this is resolved, will close this now!
