### ISSUE TITLE
Latest Documentation (2.0.3XXX.3) button does not work

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2757]
There are green and blue buttons on the download page: http://downloads.starcounter.com/download

The blue `Latest Documentation (2.0.3XXX.3)` buttons redirect to a non existing page, and only the last one `Latest Documentation (2.0.0.0)` redirects to the real documentation.

The buttons should be disabled or redirect to the latest existing documentation, not to a 404 page.

**Comment by dan31** [comment]
That is because doc tool license has expired. We need to choose something modern and free instead. We will have a look with Par sometime this week.

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Jun 9, 2015 at 12:55 AM -0700, "Konstantin" <notifications@github.com<mailto:notifications@github.com>> wrote:


There are green and blue buttons on the download page: http://downloads.starcounter.com/download

The blue Latest Documentation (2.0.3XXX.3) buttons redirect to a non existing page, and only the last one Latest Documentation (2.0.0.0) redirects to the real documentation.

The buttons should be disabled or redirect to the latest existing documentation, not to a 404 page.

-

**Comment by parherman** [comment]
I'm working on building the docs with doxygen instead

**Comment by parherman** [comment]
In commit 1463bd28bb4e081ba2deb940244c8395a5a39bc9 I pushed some initial support for building documentation with doxygen. You can test it by installing doxygen and run it in src/BuildSystem/Doxygen/

It also looks like only the latest documentation button is broken, but the links to docs for each build still works - will look into why that is

**Comment by parherman** [comment]
Now it works again! Will see it it still works after the next nightly builds tomorrow

**Comment by miyconst** [comment]
I confirm, it works.

**Comment by parherman** [comment]
It looks like this works now, will close this
