### ISSUE TITLE
Administrator panel: wrong column size in sql query result

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2761]
Something has happened to the query result table in the new Administrator panel. Now the select result looks like this:

![sa-sql-query-wrong-column-size](https://cloud.githubusercontent.com/assets/6435556/8056649/f6dc9b8e-0eb2-11e5-9003-ce66d803bad1.png)

I have to manually resize columns to make the result readable.

**Comment by warpech** [comment]
The fix is to add the following line:

```
            $scope.$apply(); //forces ng-hide to show container for Handsontable, which is required to measure available screen width
```

After line 138 in https://github.com/Starcounter/Starcounter/blob/2c79d0cdf5a12ab2b30f26d472034ba8a17ae5f0/src/Starcounter.Administrator/app/controllers/SqlCtrl.js#L138

The complete code should look:

```
        // Execute query
        SqlService.executeQuery(query, databaseName, function (response) {

            // Success
            $scope.isBusy = false;
            $scope.$apply(); //forces ng-hide to show container for Handsontable, which is required to measure available screen width
``` 

Btw. Administrator is using quite old version of Handsontable. I asked Handsontable guys for help in upgrading to the current version.

**Comment by andwah** [comment]
This is now solved,  instead of calling ```$apply()```. I removed the ```ng-hide``` attribute to the element that contains ```handsontable```.
