### ISSUE TITLE
Hook<T>.OnDelete behaviour

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2767]
This is a subissue of https://github.com/Starcounter/Starcounter/issues/2760

**Comment by miyconst** [comment]
By @miyconst

Okay. Then it seems like current hooks are already behaving like OnBeforeUpdate & OnBeforeInsert, but the OnDelete hook is very confusing. I can cancel the transaction by throwing an exception, but can't access the object, because it is already "deleted".

**Comment by miyconst** [comment]
By @per-samuelsson 

Yes, I can see your point, and I agree to some level. At the same time, its consitent with how a proxy behave right after you have deleted it, like this:

```C#
var f = Db.SQL<Foo>("SELECT f FROM Foo f").First;
f.Delete();

// Will raise exception, since `f` has been deleted in the
// current context/transaction, hence you cant 
Console.Write(f.Bar);
```

**Comment by miyconst** [comment]
Yes, this is a big limitation.

Let's assume that I have access to `X.OnDelete` method and `Hook<X>.OnDelete` hook. Then if I want to remove a file associated with the object I have to:

1. Subscribe to `X.OnDelete` and save file path to a variable.
2. Subscribe to `Hook<X>.OnDelete` and check the variable, if any values in there, then remove the files.
3. The question is how and when to clean the variable if a transaction was cancelled?

**Comment by per-samuelsson** [comment]
@miyconst, sorry i didnt respond sooner to this, i've been busy doing #2683 today.

I think you have provided several important points about inconsistencies around delete, both regarding hooks and for the ```OnDelete``` callback. I agree with what your write. Lets try improve on it!

The hardest thing to achieve is to provide access to the object in the scope of the commit hook, since it would require kernel rewrites. So lets try to avoid that. TBH, I'm not even sure its doable (with reasonable effort), since the implementation of the delete is really old - supporing objects to be accessed after they have been deleted is just really... yeah, awkward. (Like, you can't find it in a query either - it's deleted).

So what alternatives do we have?

As you wrote somewhere in #2760, its a problem also that only defining classes have access to the ```OnDelete``` callback, and that its part of an interface. Maybe we should turn that into a code-host global event, replacing the ```IEntity``` interface as a whole? In such case, not only the defining class can interpret deletes (of itself), but any class. This would solve at least some of the hazzle.

Any other ideas?

**Comment by miyconst** [comment]
As we can't change current implementation of deleted objects, but have to solve the issue somehow, a crazy idea came to my mind.

The `OnDelete` method of db class should return an object, this object should implement `IDeleted` interface which would have a `Dictionary<string, object>` of values. This object should be passed to the `Hook<T>.OnDelete` action instead of objectId.

Then, if I need to delete physical file associated with my Image object, I will save the path to the file in the dictionary and access it inside the `Hook<Image>.OnDelete`.

The `IEntity` should have `event EntityDeleteEventHandler BeforeDelete`. The event will be triggered inside the `OnDelete` method, and the `IDeleted` object will be passed in the `EventArgs`. This will let each subscriber to the `BeforeDelete` event add required values to the dictionary.

I know, it sounds too complicated, but I could not think up a better way with current limitations.

**Comment by per-samuelsson** [comment]
> I know, it sounds too complicated, but I could not think up a better way with current limitations.

I'm probably missing something from your description, but I can't see what would not work for the same use case, if we had changed to what I proposed here:

> As you wrote somewhere in #2760, its a problem also that only defining classes have access to the OnDelete callback, and that its part of an interface. Maybe we should turn that into a code-host global event, replacing the IEntity interface as a whole? In such case, not only the defining class can interpret deletes (of itself), but any class. This would solve at least some of the hazzle.

With such solution, we encourage decoupling too. Any piece of code can easily subscribe to events triggered when - or actually, *before* - any object of an arbitrary database class is deleted, and developers could quite easily couple that with commit hooks if required.

```C#
void Main() {
  // New hook that complement/replace IEntity.OnDelete, allowing
  // any arbitrary piece of code to subscribe to events triggering when
  // a database class is deleted, but before the object is inaccessible
  Hook<Image>.BeforeDelete += (image) => {
    var photo = image as Photo;
    if (photo != null) {
      new DeletedPhoto(image.FilePath);
    }
  }
  Hook<DeletedPhoto>.OnInsert(p => { p.DeleteFile(); });
}
```

**Comment by miyconst** [comment]
Yes, if we introduce the new `Hook<T>.BeforeDelete`, it will solve some of the problems.

In your example, who and when will delete the `DeletedPhoto` objects after they inserted?
Also, as mentioned before, the hooks don't fire for objects created/updated inside hooks. I assume that this is not the case for the `BeforeDelete` hook?

**Comment by per-samuelsson** [comment]
> Also, as mentioned before, the hooks don't fire for objects created/updated inside hooks. I assume that this is not the case for the BeforeDelete hook?

Exactly - its not. Because its not really a hook in the traditional sense. Its merely a callback triggered at the very time of a ```Db.Delete``` call, and hooks are actually a very specific type of callback - their full name is *commit hooks*; i.e. they are invoked at the time of commit (as you already know).

When on the subject, we should probably review the terminology as well. One idea might be to use the term **hook** as a general term for hooking into various database-related events, and then name the *events* so that they distinquish what kind of hook we are really exposing, something like:

```C#
static class Hook<T> {
  event EventHandler<T> BeforeDelete;
  event EventHandler<T> InsertComitted;
  event EventHandler<T> UpdateComitted;
  event EventHandler<ulong> DeleteComitted;
}
```

WDYT, @miyconst? Something along the lines with your initial proposal, right?

> In your example, who and when will delete the DeletedPhoto objects after they inserted?

Well, my case was just an example, but I guess either you could keep then until some job runs and delete any ```DeletedPhoto``` based on some setting or whatever, and you can preserve history or what not. Or have the application support it as a feature, "Clear History".

Or, alternatively, use some non-persistent mechanism if you prefer, like a list or dictionary or whatever, like:

```C#
class Photo {
  static List<string> Deleted = new List<string>();
  static void DeleteFiles() {
    foreach (var file in Deleted) {
      File.Delete(file);
    }
  }
}

void Main() {
  Hook<Image>.BeforeDelete += (image) => {
    var photo = image as Photo;
    if (photo != null) {
      Photo.Deleted.Add(image.FilePath);
    }
  }
  Hook<Image>.OnDelete(id => { Photo.DeleteFiles(); });
}

**Comment by miyconst** [comment]
I really like your events list, nothing to add. Would be really good to see that implemented.

If we leave `DeletedImage` object in database for further deleting by *Clear cache* button, then why do even bother myself with `DeletedImage` class? Why not just delete old files by *Clear cache* button?

I also came up with using list/dictionary in combination with `OnDelete` event and hook, but the question is how to clean up the storage if the transaction was aborted? It is not a big deal to wait till server restarts, but still a potential memory leak.

**Comment by per-samuelsson** [comment]
> If we leave DeletedImage object in database for further deleting by Clear cache button, then why do even bother myself with DeletedImage class? Why not just delete old files by Clear cache button?

Again, it was just a suggested approach, and I provided a non-storage based alternative in this follow-up https://github.com/Starcounter/Starcounter/issues/2767#issuecomment-111394569. I'm sure there are a whole bunch of alternative ways. 

As yet another example, here's a tweaked one that use persistance but require no manual maintainance, always assuring there are only the "latest" DeletedPhoto instance that sticks around in the database.

```C#
class DeletedPhoto {
  readonly string path;
  public DeletedPhoto(string file) {  path = file; }
  public void Process() {
    File.Delete(path);
    var old = Db.SQL<DeletedPhoto>("SELECT dp FROM DeletedPhoto dp WHERE dp != ?", this);
    foreach (var dp in old) {
      dp.Delete();
    }
  }
}

void Main() {
  Hook<Image>.BeforeDelete += (image) => {
    var photo = image as Photo;
    if (photo != null) {
      new DeletedPhoto(image.FilePath);
    }
  }
  Hook<DeletedPhoto>.OnInsert(p => { p.Process(); });
}
```

> I really like your events list, nothing to add. Would be really good to see that implemented.

Super. Lets go with that then. I'll try come up with a more complete model, that will also include the required non-generic form that will be required when you want to register for hooks either by their runtime type, or type name (making it future-proof, considering upcoming dynamic types). I'll open up a new issue about redesigning the API, and we can take it from there!

**Comment by miyconst** [comment]
Nice! I close this one.
