### ISSUE TITLE
object.MemberwiseClone produces distinct but somehow aliased objects

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2855]
When using `object.MemberwiseClone` on an object to get a shallow copy I expect the following:

   1. The two objects are distinct in the sense of `object.ReferenceEquals`. This property is satisfied for Starcounter database objects.
   2. Changes to a primitive field of the original don't affect the clone, and vice versa. This property is *not* satisfied, as demonstrated by the repro below.

In my opinion, the fact that `object.MemberwiseClone` has different semantics depending on whether it is invoked on a database object or not is incredibly confusing and a potential source of very grave errors.

```
using Starcounter;
using System.Diagnostics;

namespace Clone
{
    [Database]
    public class Foo
    {
        public string Name;

        public Foo Clone()
        {
            return (Foo)this.MemberwiseClone();
        }
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() =>
            {
                var f1 = new Foo() { Name = "Foo" };
                var f2 = f1.Clone();
                Debug.Assert(!object.ReferenceEquals(f1, f2)); // Property 1. This check passes.
                f2.Name = "Bar";
                Debug.Assert(!object.ReferenceEquals(f1.Name, f2.Name)); // Curiously, this check also passes... :-)
                Debug.Assert(f1.Name != f2.Name); // Property 2. This check fails.
            });
        }
    }
}
```

Note that the asserts all pass if the `[Database]` attribute is stripped from `Foo`.

**Comment by mtornwall** [comment]
A small addendum: It turns out they even have the same database ID, which arguably is the real bug here. :-)

**Comment by per-samuelsson** [comment]
@mtornwall 

Thats an interesting case you are presenting. Thanks for taking the time to do so! And the short answer is: you are right. This is exactly how Starcounter operate.

`object.MemberwiseClone` create shallow copies of heap objects, and basically copies their instance values (as you probably know). Fields of reference types are copied, but the referenced object is not (as opposed to the semantics of a deep copy, where the idea is that you copy the entire tree).

With Starcounter heap objects, think of them as a single reference (because that's what they really are). When you shallow copy such, you will copy the reference into another heap memory address (which is why `object.ReferenceEquals` return false - this comparison is comparing pointers, and the are in fact two objects in memory). Other than that, both references act equal - if you change the value of one, the other is modified to. Because they both reference the same, underlying unique database "tuple".

Consider this:

```C#
var f = new Foo() { Name = "Foo"; }
var f2 = DbHelper.FromId(f.GetObjectNo()) as Foo;
Assert(!object.ReferenceEquals(f, f2));  // pass
Assert(f.Equals(f2)); // pass
```

Its somewhat the same thing.

Regarding these, from your example:

```C#
Debug.Assert(!object.ReferenceEquals(f1.Name, f2.Name)); // Curiously, this check also passes... :-)
Debug.Assert(f1.Name != f2.Name); // Property 2. This check fails.
```

The first one simply pass because strings are objects of their own, and like I wrote above, `object.ReferenceEquals` compares by address. The same value is read from the database, but it's stored in two different string instances on the heap when read/accessed in the C# context.

The second one fail for the reasoning above - both instances refer to the same underlying database object/tuple. So if you modify one, you explicitly modify the other.

Regarding this

> In my opinion, the fact that object.MemberwiseClone has different semantics depending on whether it is invoked on a database object or not is incredibly confusing and a potential source of very grave errors.

I'm not at all an expert on other technologies with ORM-like layers like ours, but TBH, I wouldn't be suprised if the way it works in Starcounter is similar to other related API's. Have you checked how EF deal with this, for example?

Finally: it's somewhat tricky making generic deep clones, b/c they are not always clear in purpose. How far do you go? But I could see that maybe we could add some shallow copy utility method in a future version, that duplicated a database object (i.e. also allocatting a new unique key, which is what you would need to do, and copy values in the same manner as a standard shallow copy operation on a heap POCO, i.e. copying primitives and leaving references still pointing to the same referenced object). Such thing is not part of the current 2.x though, and neither anywhere in our roadmap AFAIK. Feel free to open an issue requesting it if you like, and bump it like crazy. That usually work, since we aim to please by default. :santa:

**Comment by k-rus** [comment]
Thank you @per-samuelsson for the good explanation. I just want to add that the following statement is true:
```c#
Debug.Assert(f1.Equals(f2));
```
This is because of VMDBMS technology that the data are stored in one place - database memory. Thus changing properties is reflected immediately and visible during accessing properties in the same transaction.

**Comment by mtornwall** [comment]
Thanks for the background @per-samuelsson!

Based on your description I think I have a pretty clear mental model of how Starcounter database objects behave.

The problem (in light of your comment about EF I'm hesitant to call it a "bug") in my opinion is that since Starcounter objects *behave* just like normal CLR objects in almost every respect - which, of course, is a good thing - it's an easy mistake to make to simply assume that they always behave like normal CLR objects.

Looking at the documentation it seems that making `object.MemberwiseClone` behave as expected is far from straightforward, unless I'm overlooking something. Perhaps the answer is simply: "don't use it"?

Regarding the introduction of a Starcounter-specific `Clone` extension method, I'm not sure that it's worth the effort. Cloning can be done manually without much effort; the reason I filed the issue is rather to discuss whether the behavioral difference in `MemberwiseClone` could be eliminated.

> Finally: it's somewhat tricky making generic deep clones, b/c they are not always clear in purpose. How far do you go?

Agreed - deep copying is far from straightforward, particularly with cyclic structures. It's not needed at all for my use case, either.

**Comment by per-samuelsson** [comment]
> The problem (in light of your comment about EF I'm hesitant to call it a "bug") in my opinion is that since Starcounter objects behave just like normal CLR objects in almost every respect - which, of course, is a good thing - it's an easy mistake to make to simply assume that they always behave like normal CLR objects.

This is a very good point, and I agree. In fact, there are other areas relating to this we have been concerned with in the past. The biggest thing, from the top of my head, is the issue with the semantics of the `==` operator. We simply can't solve it in a good way today. So we advice `Equals`. See #1694 for the nitty gritty details.

> Perhaps the answer is simply: "don't use it"?

I think our best shot at this is to be clear and precise in *documenting it*. We need some kind of overview article like *What every C# developer should know about Starcounter* that covers things like how the proxy objects work, how it relates to cloning/copying, how constructors and field intializers work (or doesn't work), how object equality is achieved, etc. And keep the focus on how it relates to the POCO experience in "standard" C# development.

> Based on your description I think I have a pretty clear mental model of how Starcounter database objects behave.

Good. Consider this, to make it even clearer:

```C#
// Defined class

[Database] class Foo {
  public string Value;
}

// will operate similar to

[Database] class RuntimeFoo {
  ulong thisPointer;
  public string Value {
    get { return Starcounter.ReadString(thisPointer, "Value"); }
    set { Starcounter.WriteString(thisPointer, "Value", value); }
  }
}
```

Quite simplified and pseudo-code-ish, but still valid. Hope this makes sense to you! And don't hesitate to ask if its not. :phone:

**Comment by mtornwall** [comment]
> We need some kind of overview article like What every C# developer should know about Starcounter that covers things like how the proxy objects work, how it relates to cloning/copying, how constructors and field intializers work (or doesn't work), how object equality is achieved, etc. And keep the focus on how it relates to the POCO experience in "standard" C# development.

That would be great to have, particularly upon first contact with Starcounter. I'd be happy to contribute tales of some of my own mistakes and misconceptions.

> Quite simplified and pseudo-code-ish, but still valid. Hope this makes sense to you!

It makes perfect sense and looks much as I would have expected. Thanks a lot! :-)

**Comment by per-samuelsson** [comment]
@mtornwall 

I've opened up #2857 for the suggested article. Let's see how it turns out. I'm closing this one for now. Let me know if you want it reopened. And thanks for all the valuable feedback!
