### ISSUE TITLE
Create EnforceURINamespaces flag

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2862]
As part of Starcounter/CompanyTrack#92, we need to turn "Polyjuice" functionality into the core functionality. This includes removing of PolyjuiceDatabaseFlag.

One of the features enabled by the flag nowadays is strict checking if the HTTP handlers have the app name as the first segment (`/myapp/...`).

This makes the development experience harder, because it:

- requires newcomers to learn a sophisticated concept while trying a simple hello world
- disallows merry hacking, copy pasting code between projects, etc

It is agreed that `EnforceURINamespaces` will be a useful flag especially for test environments (as well as production), but for development purposes it is mostly an obstacle. Because of that, it should be OFF by default.

**Comment by per-samuelsson** [comment]
> Because of that, it should be OFF by default.

What exactly are the effects of that its turned off? When would I hit an error if its off?

Isn't it possible to derive the application name from the context the handler is defined in, rather than enforcing it as part of the URI? After all, handlers are always bound to a certain (i.e. the registering) app, no? I have some memory that I was part of some discussion/implementation some time ago..

**Comment by per-samuelsson** [comment]
> Isn't it possible to derive the application name from the context the handler is defined in [...]?

```C#
void Main() {
  Handle.GET("/foo", () => {...);

class Handle {
  void GET(string uri) {
    var name = AppScope.Name;
    if (!uri.StartsWith(name) {
      Route.GET(uri, name + uri);
      uri = name + uri;
    }
  }
```

**Comment by alemoi** [comment]
> What exactly are the effects of that its turned off? When would I hit an error if its off?

For example, if a public App1 registers a root handler / which app-composer or administrator would like to alias somewhere else, like to /people.

And yes, we had discussions about that previously to e.g. implicitly prefix appnames but that didn't work because of too many "automatic" things and some other reasons. But please give a suggestion if you have something!

**Comment by per-samuelsson** [comment]
> For example, if a public App1 registers a root handler / which app-composer or administrator would like to alias somewhere else, like to /people

Aha, ok. That I can understand.

> And yes, we had discussions about that previously to e.g. implicitly prefix appnames but that didn't work because of too many "automatic" things and some other reasons.

OK. To be honest, I don't like those "automatics" either, I was just trying to be a little creative, since I think the enforcment of application name in URI's is quite unsexy, in terms of simple applications and for those that want to use Starcounter in the simpler way. But maybe its a neccessary evil we'll have to live with.

> But please give a suggestion if you have something!

Sorry I don't really have any more than what I've written above. I did think a little about that we'd support two different registration methods, one for the simpler, and one for the context where you actually do use the "appified" version, so that you would have like:

```C#
// Simple scenarios
Handle.GET("/foo", () => {....));

// For the "real world" application scenarios, and these would prefix it with app
// context
AppHandle.GET(/"foo", () => {....)); // or..
App.Current.GET("/foo", () => {....));
```

But I don't like that particularly much either. :smile:

**Comment by warpech** [comment]
> To be honest, I don't like those "automatics" either, I was just trying to be a little creative, since I think the enforcment of application name in URI's is quite unsexy, in terms of simple applications and for those that want to use Starcounter in the simpler way. But maybe its a neccessary evil we'll have to live with.

Thanks for creative approach, as usual. As a developer, I think that the URLs should be exactly the same as I defined them. Enforcing app name as the first segment is Starcounter's way to prevent ambiguity when running multiple apps. If we ever find a better way (hinting, etc), we can loosen up the constraint. 

This ticket is only about making optional the thing that is currently strictly enforced (to lower the learning curve). Removing the enforcement should be discussed in a separate thread if needed.

**Comment by alemoi** [comment]
I just added EnforceURINamespaces locally. Not pushing because there are a lot of other changes related to total removal of Polyjuice footprints.
