### ISSUE TITLE
pnext: IWP hangs on write if DM terminates on unexpected error

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#2892]
Should be detected and raise an error on IWP instead.

**Comment by bigwad** [comment]
I had a thought to employ job objects to handle IWP lifecycle, but seems not the way to go as IWP may be a part of another job. I will consider several options:
1. Check that DM is alive at IWP-DM communication points. Doesn't look good due to be error-prone (some points may be missed) and detects DM crash on write transactions only.
2. Launch separate thread in IWP to check DM is alive.
3. Use nested jobs, but requires windows server 2012/windows 8, requires a separate job for each IWP and not easily portable.

I'm leaning towards option 2. Thoughts?

**Comment by eriohl** [comment]
Go with 2. There are cases where the client hangs if scdata dies even if no communication. So best make sure it is detected.

**Comment by bigwad** [comment]
Done using system thread pool. 
Now IWP is just terminated on death of DM. Todo: allow to specify custom callback to execute additional actions.

**Comment by bigwad** [comment]
Done
