### ISSUE TITLE
Question: How to download/write a file on client end using response in Handle.GET

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#2909]

**Comment by mtornwall** [comment]
By "download a file on client end", do you mean that you have a separate client application (outside of Starcounter) that needs to fetch content from a Starcounter GET handler and save it as a local file?

**Comment by warpech** [comment]
Can you paste some code what have you already tried and what is the expected behaviour? 

What is the content that you want to make downloadable? Is it some data output generated on the fly? If so, then you might need to set up a custom HTTP response header: http://stackoverflow.com/questions/20508788/do-i-need-content-type-application-octet-stream-for-file-download

If this is a static file then you can use the built in web server: https://github.com/Starcounter/Starcounter/wiki/Using-the-internal-web-server

**Comment by atifsheikh** [comment]
@mtornwall Yes, By "download a file on client end" I mean save it as local file (out side of Starcoutner Installation computer). 

@warpech here is an idea of what I intend to do: 

Handle.GET("/DownloadReport", () => 
{
      string FilePath = AdFenix.Functions.GenerateNewXLS_Report();
      File ExcelFile = GetFile(FilePath);
      //How to return this file, so if someone come to this handler he downloads this ExcelFile
      return ExcelFile;
});

and whenever any go to this handler, a file should be downloaded.

**Comment by warpech** [comment]
And what is the current behavior of the code that you posted?

**Comment by alemoi** [comment]
By returning the file you would probably need to return a new `Response` object with `resp.BodyBytes` set to your file contents. Please check http://starcounter.io/guides/network/handling-responses/ for more details and let us know if it solved the problem.

**Comment by atifsheikh** [comment]
@alemoi Perfect, resp.BodyBytes worked for me. thanks for the help guys.
