### ISSUE TITLE
Removing an array element generates wrong json patch

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2920]
Removing an array element of json view-model generates json patch as if I would moved all of the next elements up one index and removed the last element.

Example to explain:

```json
{
    "items": [1, 2, 3, 4, 5]
}
```

Removing element 2 would generate the next json patch:

```json
{
    "patches": [
        { "op": "replace", "path": "items/1", "value": 3 },
        { "op": "replace", "path": "items/2", "value": 4 },
        { "op": "replace", "path": "items/3", "value": 5 },
        { "op": "remove", "path": "items/4" }
    ]
}
```

But it should generate this json patch:

```json
{
    "patches": [
        { "op": "remove", "path": "items/1" }
    ]
}
```

cc @chrhol, @warpech, @tomalec

**Comment by miyconst** [comment]
Index page of Barcodes application can demonstrate the issue.

You will have to run SysUpgrade, Launcher, Barcodes.
Create some barcodes, delete not the last element, and investigate the patch.

**Comment by tomalec** [comment]
Is it behavior of Starcounter jsonpatch, or JavaScript one as well?

**Comment by miyconst** [comment]
I didn't check the JavaScript part, because Starcounter server side does not support array operations either way.

**Comment by chrhol** [comment]
This is due to the implemenation of dirtycheck in Puppets (Starcounter). The list of barcodes is bound to a property returning the result of a query and the implementation for checking if bound objects are added or removed is very primitive today. Basically it compares two lists index for index and adds a change for each diff.

The example in the first comment, using unbound values works as expected. Only one remove patch is generated.

I would consider this definitely to be an enhancment issue to avoid uneccessery patches to be generated and sent. Not sure though if it should be considered a bug or not.

**Comment by miyconst** [comment]
Okay, I removed the `bug` label. 

How long would this improvement take you? Is it possible to fix it today, before the Starcounter 2.1 release?

**Comment by chrhol** [comment]
It should be possible to do it today I guess. It's only a small amount of code to change.

**Comment by miyconst** [comment]
Then do it, please.

**Comment by tomalec** [comment]
I think it may be considered as a bug if we think of JSON as tree of object, not as a string
```js
        { "op": "replace", "path": "items/1", "value": {"some": "obj"}}
```
in
```js
        { "op": "replace", "path": "/items/1", "value": {"some": "obj"}}
        { "op": "remove", "path": "/items/2"}
```
creates an object, and does not move the reference, so
```js
someObj = json.items[2]; //{"some": "obj"}
// apply patch, supposed just to remove /1
sameObj != json.items[1] 
// even thoug
JSON.stringify(sameObj) === JSON.stringify(json.items[1])
```

**Comment by chrhol** [comment]
Good point @tomalec. Did not think of it in that way. Lets readd the label :) 

I'm working on changing this anyway.

**Comment by chrhol** [comment]
This was a bit more complicated than I expected. 

I have a fix for this now that performs around the same as the old solution, when benchmarking the dirtycheck only and since the resulting changes in most cases will be fewer it should perform better overall. 

I have one more thing to implement and I really want to test this more to make sure I'm sending out the correct patches.

One question: is move-operation supported in PuppetJs?

**Comment by warpech** [comment]
It is, because it is supported by https://github.com/Starcounter-Jack/JSON-Patch

@tomalec can you confirm?

**Comment by tomalec** [comment]
I confirm that puppetJs supports it as fast-json-patch supports it. However
I have to check if we defined all OT for it.
5 paź 2015 17:39 "Marcin Warpechowski" <notifications@github.com>
napisał(a):

**Comment by chrhol** [comment]
I've pushed the changes for this issue to develop now. Let me know if it works out or not.

I've not implemented move-operations for now, so no need to check OT at this moment. We can do it at a later time-

**Comment by warpech** [comment]
Looks like solved for me, thanks! (tested in Barcodes app).
