### ISSUE TITLE
Rework <puppet-client> to be Polymer 1.2-aware

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2922]
After we started to support Polymer 1.1 (https://github.com/Starcounter/Starcounter/issues/2854), the demos switched to use `<dom-bind-notifier>` which requires `Object.observe`. This makes the demos not working in Firefox and IE/Edge.

Implementing `<puppet-dom-bind-notifier>` should make it work cross browser.

After `<puppet-dom-bind-notifier>` is implemented, all apps in https://github.com/StarcounterSamples should be upgraded.

This is a priority before CodeNight (15.10.2015).

**Comment by miyconst** [comment]
I think we might just replace `dom-bind-notifier` in `Starcounter/sys` directory with `puppet-dom-bind-notifier` to don't rework all of the apps.

Something similar we did with `launcher-include` vs `starcounter-include`.

**Comment by warpech** [comment]
Sounds like a nice idea.

@tomalec can you estimate the effort? It is the top priority, because it prevents apps from running cross-browser.

**Comment by tomalec** [comment]
I would say If there will be no unexpecdedly heavy issue, it may take a week, with tests and so.
But there might be still some limitations and glitches as they are now with Polymer binding itself

**Comment by warpech** [comment]
[Polymer 1.2](https://blog.polymer-project.org/releases/2015/11/02/release-1.2.0/) released. Does it include the fixes you were anticipating? Is the upgrade straightforward or are there any backward compatibility problems to be expected?

**Comment by warpech** [comment]
@tomalec, I remember you said that JSON-Patch is missing the old value information, which is required for Polymer. If needed, we can make the patches include this information, since we control our own implementation.

**Comment by tomalec** [comment]
Brief plan looks as follows:

- [ ] Create a custom element, similar to current `<puppet-client>`, that will create an instance of Puppet connect to server, and on each patch received we will modify Polymer's object, using its regular methods like `set` and `splice`, - at this point we may leave fast-json-patch do the redundant job,
- [ ] Remove the dom-bind-notifier,
- [ ] Change the PuppetJS to use custom / different `jsonpatch.apply` and `observe`,
- [ ] replace `fast-json-patch` with Polymer methods and notifications in `<puppet-polymer-client>

**Comment by tomalec** [comment]
The problem with first is that we cannot use existing `onPatchReceived`, as it happens before adding item to queue, so we will loose entire OT and versioning benefits.

**Comment by tomalec** [comment]
I will add `patch-applied` event to PuppetJS hopefully it will be quick, and wont affect performance nor create new bugs.

**Comment by tomalec** [comment]
Plus we will still face `notifySplice` issues, as object is already changed by `fast-json-patch`. Luckily this time, it should be easier to workaround, as instead of complicated splices, we have atomic remove operations, so we could reorder them somehow.
However, I do not think I will be able to provide this workaround this week, so we could release an alpha.

**Comment by warpech** [comment]
It was decided today that the new component described above will be named `puppet-client` and will be a drop in replacement for the old one. `dom-bind-notifier` will become redundant.

**Comment by tomalec** [comment]
> dom-bind-notifier will become redundant.

Therefore for interim phase, when we will deliver new `<puppet-client>` with sysupgrade app, we will also overwrite `dom-bind-notifier` with no-op one, that will only console log a message, that it's deprecated, and should be removed from app's code.

**Comment by tomalec** [comment]
Ok I have changed the plan, as any shortcut stuck with the same place, at `notify*` API.

I have managed to:

- do small change in PuppetJS to make it possible to replace jsonpatch with something else (this could be polished a little bit, but so far works fine)
- implement [`puppet-polymer-client`](https://github.com/PuppetJs/Puppet-polymer-client/tree/puppet-apply) that creates PuppetJS instance, but replaces jsonpatch with Polymer integration (`.set`, `.splice`, and observers),
  - Right now we have to attached `<puppet-polymer-client obj="{{model}}">` into the `dom-bind`, and no other `dom-bind-notifier` is needed,
  - The overhead, and compatibility issues regarding redundant Object.observe shim are gone,
  - Even `fast-json-patch` is no longer needed,
  - We use more stable and tested API of Polymer, and build the app in more "Polymer-way",
- Related component [`starcounter-debug-aid`](https://github.com/StarcounterSamples/starcounter-debug-aid/tree/puppet-polymer-client) is updated to use new version of `puppet-client`
- [Launcher](https://github.com/StarcounterPrefabs/Launcher/tree/puppet-polymer-client) template was updated to use new version of `puppet-client`
- [SysUpgrade](https://github.com/StarcounterSamples/SysUpgrade) is updated to overwrite Launcher's and Starcounter's packages with new ones.

In general performance should be way much better, flow should get simplified, and is seems that it's almost finished.

Unfortunately, it does not work all integrated together.
I suspect this is because our other components ('imported-template', 'starcounter-include', etc.) are vanilla ,and not Polymer elements, therefore, may not propagated notifications, observers and bindings for nested partials.

**Comment by warpech** [comment]
Current status: Polymer 1.2 changes are available in https://github.com/StarcounterSamples/SysUpgrade repo that is being tested by @malx122. After he confirms it works, SysUpgrade can be merged to Starcounter `develop` and issues #3384, #3022, #2922 can be closed.

**Comment by warpech** [comment]
Upgrade to Polymer 1.3 done in https://github.com/Starcounter/Starcounter/issues/3384

**Comment by warpech** [comment]
Upgrade to Polymer 1.3 done in https://github.com/Starcounter/Starcounter/issues/3384

This includes creating https://github.com/puppetjs/puppet-polymer-client
