### ISSUE TITLE
Add a Visual Studio template for creating pages, not just JSON

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2931]
I consistently forget to change the base class of my pages from `Json` to `Page`. Though ultimately my own fault it has cost me lots of frustration. I propose you add a template in Visual Studio for creating pages with code-behind to avoid confusion.

**Comment by warpech** [comment]
Great catch! Let's try to do something before CodeNight

**Comment by warpech** [comment]
Maybe we could get as far as merging `Page` into `Json` class directly? 

@dan31, @chrhol, @alemoi, WDYT?

**Comment by warpech** [comment]
I see three options:

1. Merging `Page` into `Json` class directly
2. Don't merge, but just make the Visual Studio template use the `Page` class instead of the `Json` class
3. Add another template for Starcounter Page with code-behind

@dan31, @chrhol, @alemoi, WDYT?

**Comment by dan31** [comment]
How often do we need only JSON but not PAGE? If not frequently, one can change Page back to Json. I'm thinking of P.3 in that respect. WDYT @warpech?

**Comment by warpech** [comment]
> How often do we need only JSON but not PAGE?

I would say:

- 75% of cases we use Page
- 24.9% of cases we use Json, but Page would be also fine (just the Page features would not be used)
- 0.1% of cases we want to use Json and Page would cause problems

Option 4: Let's change `Page` to be an interface (similarly to [`IBound`](https://github.com/Starcounter/Starcounter/blob/4c44ec195f9aa3d05cb50e7d57f76fa97db1ca8a/src/Starcounter.XSON.PartialClassGenerator/CompilerMono/CodeBehindParser.cs#L185)). So that the default Starcounter Json template will create:

```
partial class Message1 : Json, IPage {
} 
```

If someone doesn't want Page features, they would just remove `, IPage` interface.

**Comment by chrhol** [comment]
Hmm, I'm not sure what I like more. I think adding another template might be confusing, better to make `Page` default and then make it easy to switch to `Json` if needed.

> 0.1% of cases we want to use Json and Page would cause problems

Do you have any example of when this can happen? Other then this merging them seems good.

> Option 4: Let's change Page to be an interface (similarly to IBound). So that the default Starcounter Json template will create:

There is some code added to `Page` that needs to added during codegeneration instead, so this option involves a little bit of work.

**Comment by warpech** [comment]
>> 0.1% of cases we want to use Json and Page would cause problems

> Do you have any example of when this can happen? Other then this merging them seems good.

This is when I want my Json to NOT have a `text/html` representation. Or if I want to create a `Html` property that is of other type than `string`.

**Comment by chrhol** [comment]
Right, thanks.

Then 2 or 4 gets my vote.

**Comment by mtornwall** [comment]
>> 0.1% of cases we want to use Json and Page would cause problems

> Do you have any example of when this can happen? Other then this merging them seems good.

Presumably merging `Json` and `Page` would mean that actual JSON responses would always have an `Html` property attached, even if it would be empty? If the client-side uses strongly typed JSON deserialization (as my .NET code does) this would blow up.

**Comment by warpech** [comment]
> Presumably merging Json and Page would mean that actual JSON responses would always have an Html property attached, even if it would be empty? If the client-side uses strongly typed JSON deserialization (as my .NET code does) this would blow up.

> If this is not the case then +1 for merging.

That's not the case. `Html` property is only exposed if you explicitly declare it in JSON-by-example, even with the `Page` class.

**Comment by mtornwall** [comment]
> That's not the case. Html property is only exposed if you explicitly declare it in JSON-by-example, even with the Page class.

Ah! In that case I have no issues with that solution. :-)

**Comment by warpech** [comment]
@chrhol How much work would be required to get option 4 (IBound)?

@alemoi, @dan31, @Starcounter-Jack WDYT?

**Comment by dan31** [comment]
Guys, talking of that solution:
```
partial class Message1 : Json, IPage {
} 
```
then one objection there is a lack of simplicity: the instant question of an average user would be "why so"? And then there should go a good way to explain why. Maybe we need to review the classes hierarchy instead?

**Comment by warpech** [comment]
> then one objection there is a lack of simplicity: the instant question of an average user would be "why so"? And then there should go a good way to explain why. Maybe we need to review the classes hierarchy instead?

The purpose is to declare that there exists a different representation of the JSON - a HTML template. Maybe `Page` or `IPage` isn't the best word for that at all. `IHtml` anyone?

To speed up the decision, I will repeat the aforementioned solution proposals and add another one (5):

1. Merging `Page` into `Json` class directly
2. Don't merge, but just make the Visual Studio template use the `Page` class instead of the `Json` class
3. Add another template for Starcounter Page with code-behind
4. Change Page to be an interface (`Message1 : Json, IPage` or `Message1 : Json, IHtml`)
5. Rename `Page` -> `Json`, `Json` -> `RawJson`

My favorites are 4 & 5.

**Comment by miyconst** [comment]
>My favorites are 4 & 5.

Same here.

**Comment by per-samuelsson** [comment]
@jwillmer also reported this as a headache, so its clearly something we should do *something* about.

**Comment by warpech** [comment]
Even simpler solution would be to add more usage of **"partial"** to our jargon, as opposed to "page".

Partials are explained on the website but are still counterintuitive. You create an instance of `Page` to make a partial. Also, the word "Page" is less searchable than "Partial".

Since nobody fell in love with the previously proposed solutions, here is a new one:

6 . Create a clone of `Page` class called `Partial`. Start using this one from now on. Create Visual Studio templates: `Starcounter Partial JSON with Code-behind`, `Starcounter Partial HTML Template`. I can provide the template for the latter.

**Comment by per-samuelsson** [comment]
> Create a clone of `Page` class called `Partial`. Start using this one from now on. Create Visual Studio templates: `Starcounter Partial JSON with Code-behind`, `Starcounter Partial HTML Template`. I can provide the template for the latter.

Im all for this one. I'm usually against introducing to many words that are not super-intuitive, but in this case, I think partials is really something we should promote and add to our core lingo. I'm all with @warpech on this one.

**Comment by warpech** [comment]
> I'm usually against introducing to many words that are not super-intuitive, but in this case, I think partials is really something we should promote and add to our core lingo

Speaking with @miyconst and @jwillmer I got confirmation that the concept of "partial" also exists in ASP.NET and is not very far from ours.

@per-samuelsson then maybe actually you have enough information to implement the solution?

@tomalec Could you provide what should be the Visual Studio template for `Starcounter Partial HTML Template`?

**Comment by tomalec** [comment]
Something like this: https://gist.github.com/tomalec/45271780b0736b6f2ced
or is it to elaborate?

**Comment by warpech** [comment]
I think these comments are great for a starcounter.io page, but the actual VS template should go without them. Could you paste the commented version in http://starcounter.io/guides/web/partials/ ?

**Comment by tomalec** [comment]
.io updated: http://starcounter.io/guides/web/partials/#example
Then the skeleton should look like:
```html
<link rel="import" href="/sys/polymer/polymer.html" />
<link rel="import" href="/sys/dom-bind-notifier/dom-bind-notifier.html" />

<template>
    <template is="dom-bind">
        {cursor goes here}
        <dom-bind-notifier path="model" observed-object="{{model}}" deep></dom-bind-notifier>
    </template>
</template>
````

**Comment by warpech** [comment]
Could the template for `Starcounter Partial JSON with Code-behind` (`.json` part) look like this?

```json
{
    "Html": "/<appname>/<filename>.html"
}
```

Where `<appname>` is the name of the .exe and `<filename>` is the same name as provided for the `.json`

**Comment by warpech** [comment]
And of course the partial for `Starcounter Partial JSON with Code-behind` (`.json.cs` part) should be something like this:

```cs
using Starcounter;

namespace $rootnamespace$ {
    partial class $safeitemname$ : Partial {
    }
}
```

**Comment by warpech** [comment]
> Create a clone of Page class called Partial.

Actually this does not need to be a clone, since I have a working implementation of the desired `Partial` class. Info here: https://github.com/StarcounterSamples/Barcodes2/issues/2

**Comment by per-samuelsson** [comment]
> [...] since I have a working implementation of the desired `Partial` class.

Since I've been asked to look at this some week ago (and I have, and tested how it works), I have a question related to the upcoming switch: how should we promote naming of triplet items?

Now, the standard pattern is:

```
ProductPage.json
ProductPage.json.cs
ProductPage.html
```

Are we refining this as well, reflecting the `Page` -> `Partial` base type recommendation? Or are we to promote both, where pages are more like stand-alone mode, while partials are the "nested" ones?

**Comment by jwillmer** [comment]
I differentiate between partials and pages by putting the partials in a subfolder "Partial"

**Comment by per-samuelsson** [comment]
OK, I'm now quadripel-voting this one up, after spending like 2 hours myself trying to understand why the f** I couldn't see anything when requesting a certain resource, refactoring the PIM down to half the size just to find out, before it hit me. Its just super-sick. :smile:

**Comment by per-samuelsson** [comment]
Somewhat related to a discussion I'm pushing here: #3165.

**Comment by warpech** [comment]
> Since I've been asked to look at this some week ago (and I have, and tested how it works), I have a question related to the upcoming switch: how should we promote naming of triplet items?

I propose:

```
ProductEdit.json
ProductEdit.json.cs
ProductEdit.html
```

For me, the word `Page` or `Partial` in the file name is redundant. Just 4 (7) more letters to type. @miyconst WDYT?

Note that the view-model name cannot be called just `Product`, because that would be ambiguous with the data model name (bad for namespace resolution, bad for human trying to understand what's going on).

**Comment by per-samuelsson** [comment]
> I propose:

```
ProductEdit.json
ProductEdit.json.cs
ProductEdit.html
```

Yeah, this is in line with what we discussed earlier. I too favor something like this.

> For me, the word `Page` or `Partial` in the file name is redundant.

For sure.

**Comment by chrhol** [comment]
> @per-samuelsson, @chrhol: Could you please just add one VS file template (called: Starcounter HTML template with dom-bind) with the following code:

I can do that. Sounds like a good issue to fix before vacation :)

**Comment by chrhol** [comment]
I always forget what a hassle it for anything around VS and templates (and extensions). I think I got it working now, currently doing a personal build and after I will just verify that everything works with the installer before pushing it.

**Comment by warpech** [comment]
Thanks a :100:!

**Comment by chrhol** [comment]
Pushed to develop and pnext now.

**Comment by warpech** [comment]
@chrhol, the file template actually ended up containing the text `{cursor goes here}`: https://github.com/Starcounter/Starcounter/blob/48c8ff5c8ab2c2a86b4fba2dfaec34ea16f3d7ca/src/Development/Starcounter.VS.HTMLTemplateItemTemplate/HTMLTemplate.html#L5

My intention was not to put that text there, but to place the text caret in that position. Is that possible?

**Comment by chrhol** [comment]
> @chrhol, the file template actually ended up containing the text {cursor goes here}:

:smile: I was actually wondering what that code did, but I simply copied everything.

> My intention was not to put that text there, but to place the text caret in that position. Is that possible?

No that's not possible. There is no way to (or at least no way without adding some strange hack in the extension) to control where the caret is positioned. The template is simply a static file that are copied and renamed when added. 

What we could do is add a comment there instead saying that usercode goes here or something. 

I will start with simply removing the text for now.

**Comment by warpech** [comment]
> I will start with simply removing the text for now.

That will be food, thanks!

**Comment by chrhol** [comment]
Can we consider this issue solved @warpech , or is it some point left to do for it?

**Comment by warpech** [comment]
Yes, well done! Closing.
