### ISSUE TITLE
Middleware filter is not being hit for sc/htmlmerger request

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2963]
@alemoi,

Should 
```cs
Handle.AddFilterToMiddleware(r => {
    ...
});
```
Be invoked per `http://localhost:8080/sc/htmlmerger?` requests?

I need it, but not sure it should.

**Comment by alemoi** [comment]
Thank you for the question! All external requests are inducing invokation of middleware filters. The exception is if handler uses SkipMiddlewareFilters flag when created. If request is internal - then no middleware filters are involved.

**Comment by alemoi** [comment]
I guess I will close this one.

**Comment by warpech** [comment]
In the [htmlmerger handler](https://github.com/Starcounter/Starcounter/blob/66b8b35c34631c49c4cb4cc54248fb86f2810ba3/src/Starcounter/Apps/OntologyAndOrdinaryMapping.cs#L1001), the `SkipMiddlewareFilters` flag is not set, which means the filters should be applied. The OP suggests it is otherwise.

@miyconst was your problem solved?

**Comment by miyconst** [comment]
Yes. The issue was solved in another way.

Instead of capturing all requests and authenticating sessions, I just check whether user is signed in by incoming cookie.
