### ISSUE TITLE
Query result table goes outside of the bounds

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2986]
```sql
SELECT * FROM Starcounter.Metadata.Table
```

![image](https://cloud.githubusercontent.com/assets/6435556/10665585/89fe7788-78cc-11e5-8104-8f891d2b111f.png)

**Comment by warpech** [comment]
Thanks! May be fixed by the fix for https://github.com/Starcounter/Starcounter/issues/2828.

**Comment by warpech** [comment]
Column width is now fixed, but horizontal leaking problem prevails. This is what happens when Handsontable does not fit horizontally in the layout:

![bug](https://cloud.githubusercontent.com/assets/566463/10701455/ddaf5ba2-79c3-11e5-83fb-a5a99363b99e.gif)

The desired result is to expand the main container without leaking out from it or adding any special scrollbars.

@budnix could you take this?

---

When horizontal scrolling is in use, the header (screenshot below) should be `position: fixed`:

<img width="1032" alt="screenshot 2015-10-23 20 28 47" src="https://cloud.githubusercontent.com/assets/566463/10701619/c0bd2b90-79c4-11e5-8df8-82992b664d25.png">

**Comment by miyconst** [comment]
@warpech can you increase priority of this issue, as it is really annoying and was pointed out by TargetEveryOne guys as well.

**Comment by warpech** [comment]
The priority P/Normal is good, but the progress is bad :) I will bump @budnix about it.

**Comment by budnix** [comment]
I have pushed changes to my branch 5 hours ago that relates to this issue but please ignore it. After more testing I found that my solution is not good enough and needs improvement. Still working on that.

**Comment by warpech** [comment]
@budnix wrote in an email:

> After introduce new feature preventOverflow to Handsontable (https://github.com/handsontable/handsontable/issues/3071) this should not appear any more.

I confirm that https://github.com/budnix/Starcounter/commit/e258f21c0a9490be9fc3f72dd5d32a2d5c6c6e59 fixes the problem.

I will merge it later.

**Comment by warpech** [comment]
Merged
