### ISSUE TITLE
Using inherited indexes does not work properly

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3062]
IndexQueryTest is not able to find instances. I don't know what exactly is the problem. The test is `TestInheritedIndexes()` on line 63 in *Level1\src\Samples\IndexQueryTest\InheritedIndexTest.cs*

**Comment by eriohl** [comment]
I'm checking this.

**Comment by eriohl** [comment]
It is a kernel issue. The insert verified the updates between insert and setting set specifier and then index seems not to be updated properly. This is also rather expensive so I addressed this (see DbState.Insert) and then the test works.

But the underlying issue is still there so looking into that.

**Comment by eriohl** [comment]
(Call to GetSpecifier in DbState.Insert will add a lot of overhead to insert by the way. Set specifier should be stored with type binding instead. Doesn't change for a given table at runtime after all.)

**Comment by eriohl** [comment]
Underlying kernel issue addressed as well.

**Comment by k-rus** [comment]
> (Call to GetSpecifier in DbState.Insert will add a lot of overhead to insert by the way. Set specifier should be stored with type binding instead. Doesn't change for a given table at runtime after all.)

Agree. Had a task about it, now created issue #3070.
