### ISSUE TITLE
Space in JSON file returns multible errors

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3103]
Because VS does not like properties in JSON without quotes it is easy to (accidentally) write something like this:

```{
    "Products In Stock": [ ]
}```

But the error this produces is not user friendly. Depending on the document you get over 100 compile errors. It took me awhile to find the problem.

Could you improve the error handling to one message that directs the user to the problem?

**Comment by per-samuelsson** [comment]
Thanks for reporting this @jwillmer. We'll surely look in to it and improve the error message.

**Comment by per-samuelsson** [comment]
Checked what standard JSON has to say about spaces, and it turns out to be legal: you can have keys and values with spaces.

Run this

```json
{
    "Testing this": "Yes you can"
}
```
 in [this](http://jsonlint.com/#) to see.

Why we can't support it is because of the generated code; C# does not allow spaces in fields/properties.

Talked to @chrhol about it. We will adress this by validating keys for this pattern, and raise an informative exception (including the errornous token).

**Comment by chrhol** [comment]
I've added verification of propertynames when generating code for JSON-by-example that is pushed to develop. 

In this case, you should get a compiletime error that looks like this:

![invalid_property](https://cloud.githubusercontent.com/assets/1658979/12718856/91079594-c8f1-11e5-92b9-51afe8870538.JPG)
 
Double-clicking on the error form the errorlist window in VS, will open and point to the correct property.

This fix will be available in the upcoming nightly builds (will merge it to pnext as well)

**Comment by jwillmer** [comment]
cool! :+1:
