### ISSUE TITLE
Administrator hangs with huge select results

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3106]
As TargetEveryOne guys pointed out, Starcounter Administrator hangs if select returns many records, tested with 1 000 000 records.

I know, this is crazy to manage such number of rows in a browser, but we have to automatically add `FETCH 10000` or something like this to avoid the hang. If the total number of records exceeds the visible number, then a message like `There are too many rows matching this query, displaying first 10000` should be displayed.

@warpech, @andwah

**Comment by per-samuelsson** [comment]
@miyconst 

> [...] tested with 1 000 000 records

Yeah, wow, thats cool. Really nice to see someone querying a result that big.

I'm not sure how we can solve this fast, but we should of course support paging. In fact, we have support for it already, since a few years back, in the lower level (kernel + managed iterators), but we've never took it "all the way", simply because there hasn't been some urgent need.

Unsure how we should prio this tbh. I'm adding @dan31 to the mix, and lets see like next week when he's back how and when to put this one in the loop.

**Comment by warpech** [comment]
As an easy fix for this issue, Administrator C# code could just check it the `Count` of the result is `> 1000` and show an error message ("Too many rows in the result").

If we want to use pagination, this repo http://github.com/handsoncode-apps/InvoiceDemo is supposed to show how to add pagination. Basically, it uses `FETCH` & `OFFSET`.

**Comment by miyconst** [comment]
>"Too many rows in the result"

This should not be an error, it should be a warning.

"There are X records in this result. Displaying first 1000 records."

**Comment by andwah** [comment]
To add pagination would be the right way but it will take the longest time to do.

I think the short time solution is just to limit the result and show a warning like @miyconst  suggest.

**Comment by warpech** [comment]
:+1:

**Comment by andwah** [comment]
Fixed 946cab5082d41ebe9fa7a131153fbac9cb4b351e
![image](https://cloud.githubusercontent.com/assets/2656996/12448925/b28db080-bf79-11e5-9f65-93821baa7d96.png)
**Note:** the limit is 1000 records not 10 as the image suggest

**Comment by miyconst** [comment]
Thanks @andwah, closing the issue.
