### ISSUE TITLE
Metadata binding error

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3136]
This json:
```json 
"To": {
            "Harbor$": "",
            "$Harbor": { "Bind": "Simplified.Ring3.Address.Name" }
        }
```
gives me the compile time error: ```Metadata but no field for 'Harbor' found```

But this is valid:
```json
"To": {
            "Harbor": "",
            "$Harbor": { "Bind": "Simplified.Ring3.Address.Name" }
        }
```

Why is it not valid if I like to change the property value from the client?

**Comment by chrhol** [comment]
Looks like the check for this is a bit incomplete. It requires the ending `$` to be set on both, so the following will work: 

```javascript
"To": {
            "Harbor$": "",
            "$Harbor$": { "Bind": "Simplified.Ring3.Address.Name" }
        }
```

I will assign issue to me to fix so that your first example will work.

**Comment by chrhol** [comment]
I've pushed a fix for this to develop. The first example in your code should work with the next nightly build.

I wanted to not allow specifying editable on a metadata-property (since it makes no sense) but opted for allowing it, since the change would break to many existing applications. So now the ending `$` on a metadata-property will simply be ignored.

to recap, all of these are valid: 

```javascript
"Harbor$": "",
"$Harbor": { "Bind": "Simplified.Ring3.Address.Name" }

"Harbor": "",
"$Harbor": { "Bind": "Simplified.Ring3.Address.Name" }

"Harbor$": "",
"$Harbor$": { "Bind": "Simplified.Ring3.Address.Name" }

"Harbor": "",
"$Harbor$": { "Bind": "Simplified.Ring3.Address.Name" }
```
