### ISSUE TITLE
ScErrTransactionModifiedButNotReferenced 

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3168]
What does it mean?
Code looks samewhat like this:

```
new DbSession().RunSync(() =>
            {
                Db.Scope(...)
            }, SchedulerPartitioner.GetNext());
```

**Comment by careri** [comment]
Seems like I have to call Transaction.Current.Commit() before leaving the scope?

**Comment by chrhol** [comment]
You are using a `Db.Scope()` (i.e a longrunning transaction) and writes to a database-object, but you don't do a Commit or Rollback, and you are not referencing the transaction (using it for TypedJson or getting a `Transaction` object), which means that the transaction will be cleaned up in the end of the scope. 

The error was added to avoid doing writes thinking they would be committed, and being confused or thinking something in the database is not working.

When you have these short scopes, it might be better to use `Db.Transact` instead, or maybe create a readonly `Db.Scope` if the write was not intentional.
