### ISSUE TITLE
How to trigger a json dirtyCheck?

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3191]
Hi! 

As far as I can see the  [json-patch-duplex.ts](https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/json-patch-duplex.ts)  performs a dirtyCheck either on mouse/key events or on a timeout basis.

This results in a annoying delay in some parts of our apps when the json data is changed without any user mouse/key activities. 

Are the some recommended ways to explicitly force a dirtyCheck? Or will this be reworked in the near future. Today I use:

    var clickEvent = document.createEvent ('MouseEvents');
    clickEvent.initEvent ("mousedown", true, true);
    window.dispatchEvent (clickEvent);

**Comment by miyconst** [comment]
@tomalec, me and @warpech were also curious about this question.

**Comment by warpech** [comment]
@ivarbergman this is absolutely right approach. I would only change `mousedown` to `mouseup`, because we might dump `mousedown` on some point (see https://github.com/Starcounter-Jack/JSON-Patch/issues/98)

I have explained the approach you took in PuppetJs README: https://github.com/PuppetJs/PuppetJs/blob/gh-pages/README.md#generating-patches-based-on-local-changes

A high level API is discussed in https://github.com/PuppetJs/PuppetJs/issues/29
