### ISSUE TITLE
Strange behaviour with POST request

### ISSUE THREAD

**Issue by binte** [Starcounter/Starcounter#3225]
Hey everyone,

I am having some complications with a POST request, in the line highlighted with ** **.The code is shown below:

```c#
public static string POST(string url, string attributes)
{
        string response = "";
        HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
        request.Credentials = CredentialCache.DefaultCredentials;
        request.Method = "POST";
        Stream postStream = request.GetRequestStream();
        var bytes1 = System.Text.Encoding.UTF8.GetBytes(attributes);
        postStream.Write(bytes1, 0, bytes1.Length);
        postStream.Close();

	// Get the response
	** WebResponse response1 = request.GetResponse(); **
	Stream dataStream = response1.GetResponseStream();
	StreamReader reader = new StreamReader(dataStream);
	
	response = reader.ReadToEnd();

	reader.Close();
	response1.Close();

	return response;
}
```

It is invoked like this:

                AF.Func.HttpReq.POST(string.Format(URL, token, domain), json);

Everything seems to go smoothly: the URL in the request, immediately prior to the call to getResponse() is correctly formed, the response returned from the asynchronous call as well, but I keep getting these errors after that return:

"An exception of type 'System.Net.WebException' occurred in System.dll but was not handled in user code"

"The remote server returned an error: (500) Internal Server Error."

Any idea on what might be happening here?

**Comment by mtornwall** [comment]
It sounds like you should debug the server side. If it's a Starcounter application, try starting it in the debugger and set up breaking on all exceptions (Ctrl+Alt+E, then check "Thrown" for "Common Language Runtime Exceptions"). This way you can see when the exception occurs.

Note that if you are POST:ing a JSON document that is automatically parsed by a Starcounter handler, e.g.,:

~~~
Handle.POST("/someurl", (SomeJson json) => {
    // Do something with SomeJson...
});
~~~

Any JSON parse errors may be masked because they are occurring in Starcounter code. If you believe this could be the case, try disabling "Just My Code" under the Tools -> Options -> Debugging menu.

**Comment by binte** [comment]
I think we are talking about slightly different things. The json is parsed properly from the http body. All the code is running as expected. 

The last few lines of our handler looks like this: 

                Response response = new Response()
                {
                    StatusCode = 200
                };
                response.HeadersDictionary["Access-Control-Allow-Origin"] = origin;
                response.Body = returnString;
                return response;

In debug mode I can see that the starcounter response object looks perfectly fin. But somehow I dont get the expected response and receive this instead:

System.NullReferenceException: Object reference not set to an instance of an object.
 at Starcounter.Response.EstimateNeededSize(Byte[] bytes) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Internal\Http\Response.cs:line 1039
 at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Internal\Http\Response.cs:line 844
 at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Internal\Http\Request.cs:line 1174
 at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 390
 HResult=-2147467261

**Comment by mtornwall** [comment]
@binte Sorry, I misunderstood your question. :-)

Is it possible that `origin` is null? While I cannot run your exact code on my machine (since `HeadersDictionary` has been removed in Starcounter v2.1) I got a similar result trying to set a header like this:

    Handle.AddOutgoingHeader("Access-Control-Allow-Origin", null);

@alemoi Could we have `AddOutgoingHeader` trap this with an `ArgumentNullException`?

**Comment by alemoi** [comment]
Thank you for you question, @binte !

> @alemoi Could we have AddOutgoingHeader trap this with an ArgumentNullException?

Sure! I will add this check!
And make sure to throw exceptions on null headers.

@binte 
> Is it possible that origin is null?

**Comment by binte** [comment]
Hey guys, sorry for not following the conversation, but I have been on holidays until today. @mtornwall you are correct. Seems that the problem was that origin was NULL, as you said. The value was being changed by reference, and I didn't notice that.

Thank you so much for your help!
