### ISSUE TITLE
Very weird exception when trying to execute an expression over a db class

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3248]
I am working on a `Starcounter.DbContext` class which would provide basic access to database tables without writing any sql.

Here is the repository: [Starcounter.DbContext](https://github.com/miyconst/Starcounter.DbContext)
Here is the main class: [DbContext.cs](https://github.com/miyconst/Starcounter.DbContext/blob/master/Starcounter.DbContext/DbContext.cs)

Now, strange things happens as soon as I try to invoke a method with a property expression parameter, for example this one: [Select](https://github.com/miyconst/Starcounter.DbContext/blob/master/Starcounter.DbContext/DbContext.cs#L45).

As soon as execution hits the line of invocation, like in the [demo](https://github.com/miyconst/Starcounter.DbContext/blob/master/Starcounter.DbContexDemo/Program.cs#L18), the process gets terminated with the following exception:

```
"Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.MissingFieldException: Field not found: 'Simplified.Ring1.Something.Name'.
   at Starcounter.DbContexDemo.Program.Main()
Version: 2.1.944.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 580
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 271
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 71
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 554
HResult=-2146232828
---> System.MissingFieldException: Field not found: 'Simplified.Ring1.Something.Name'.
   at Starcounter.DbContexDemo.Program.Main()
HResult=-2146233071
"
```

Or this if I put the call into [OnData](https://github.com/miyconst/Starcounter.DbContext/blob/master/Starcounter.DbContexDemo/IndexPage.json.cs#L6) method of a Page.

```
"System.MissingFieldException: Field not found: 'Simplified.Ring1.Something.Name'.
   at Starcounter.DbContexDemo.IndexPage.OnData()
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 79
   at Starcounter.Json.set_Data(Object value) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 51
   at Starcounter.DbContexDemo.Program.<>c.<Main>b__0_0() in E:\GitHub\Miyconst\Starcounter.DbContext\Starcounter.DbContexDemo\Program.cs:line 11
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-145\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 523
HResult=-2146233071
"
```

This is extremely annoying.

- I see different exceptions depending on the place I try to invoke same code.
- The debugger does not work in this situation.
- The exception tells me `Field not found: 'Simplified.Ring1.Something.Name'` where there is obviously such field.

**Comment by miyconst** [comment]
cc @alemoi, @k-rus, @eriohl

**Comment by eriohl** [comment]
I'm just guessing here but if Product and Something is in different assemblies it could be that the assembly with Product links to a different assembly then the one you expect. CLR allows for multiple classes with the same name to be loaded and you can get really weird results when this happens (usually because different assemblies links to different versions of the same assembly).

**Comment by miyconst** [comment]
No, `Product` and `Something` both are declared in `Simplified`.

**Comment by eriohl** [comment]
Another idea then: You're code probably links the field name while the weaver changed it to a property (thus the field Name is missing). Name is a database field right. The weaver is supposed to change access to a property call but this probably isn't working for some reason.

**Comment by miyconst** [comment]
Is it @per-samuelsson responsibility?

**Comment by eriohl** [comment]
He has the best handle on the weaver yes so he is probably then one to ask if this is the problem (although this is a guess on my part).

**Comment by per-samuelsson** [comment]
I have no instant guess, but I'm a bit tired right now. Let me take a look tomorrow with a pair of fresh :eyes:

**Comment by miyconst** [comment]
@per-samuelsson sure, it's time to take some rest.

**Comment by k-rus** [comment]
> Another idea then: You're code probably links the field name while the weaver changed it to a property (thus the field Name is missing). Name is a database field right. The weaver is supposed to change access to a property call but this probably isn't working for some reason.

+1

Side note: your implementation of `Starcounter.DbContext` is expensive due to string concatinations.

**Comment by miyconst** [comment]
>Side note: your implementation of `Starcounter.DbContext` is expensive due to string concatinations.

@k-rus thanks for the note, you are always about the performance :).

Here are my thinks:

- `DbContext` does not support complex sql queries, and those smart guys who work on extremely big tasks will write their sql queries manually.
- In a small to mid size Starcounter application the performance impact would be minimal, as there are about up to 5 sql queries per page.
- As soon as I get the solution work at least somehow I will replace the string concatenation with `System.Text.StringBuilder`.
- If we find the `DbContext` class useful, we can add another layer in weaver or even before compilation, which would replace `DbContext` calls which direct `Db` calls.

**Comment by k-rus** [comment]
A proper implementation of `Starcounter.DbContext` should not rely on SQL and should use low level API. It is the only way to have reasonable performance. However, it is not a small task.
To move in that direction I created a small task for our side, issue #3249.

**Comment by miyconst** [comment]
>A proper implementation of Starcounter.DbContext should not rely on SQL and should use low level API. 

Totally agree, but I don't have access to it. Maybe you can feed me with some readme?

>However, it is not a small task.

I don't know how this all works under the hood, but I do know, that if we implement those few methods I have in the `DbContext`, we would eliminate about 80% of string sql queries in the apps.

**Comment by k-rus** [comment]
> A proper implementation of Starcounter.DbContext should not rely on SQL and should use low level API.
> Totally agree, but I don't have access to it. Maybe you can feed me with some readme?
> 
> However, it is not a small task.
> I don't know how this all works under the hood, but I do know, that if we implement those few methods I have in the DbContext, we would eliminate about 80% of string sql queries in the apps.

Since this discussion is off-topic for this issue, I moved it into separate issue Starcounter/CompanyTrack#167

**Comment by per-samuelsson** [comment]
Just a short update on this: the problem is in the weaver, where expressions like the one used is not really supported. 

There are a few cases we can't handle, and that we never have bothered addressing. One example is passing database fields as `ref` or `out` parameters. When such code is detected, the weaver produce an error, saying this is not allowed.

For this particular case, I'm just in the middle of stepping code and testing a few cases to see what our options are. I'll get back later with the conclusions of that.

**Comment by per-samuelsson** [comment]
OK, I don't think I can justify spending more time on this without us putting it into the context of the roadmap. 

The weaver fail to detect the reference to the field because it is in a lambda expression, and when I've studied the IL, it's clear the compiler does not emit any instructions we currently act upon, i.e. neither `ldfld` nor `ldflda`.

In fact, reverse-enginering the produced code shows a weird usage of a `fieldof` operator in C#, which is quite weird, since its been a thing the community has wished for for a very long time (> 5 years or so), but it's never been implemented (to my knowledge). In C# 6.0, there is the new `nameof`, but that one is quite different, bringing out the name compile-time to a literal only.

Looking at the IL, the compiler convert it to a long sequence of instructions, where one we could possible act upon would be the `ldtoken`, trying to check if the argument is a `.field` token and, if so, give a warning or produce an error if that argument represent a database field, and even long term, try to switch it to a a method call. But this is not at all trivial I'm afraid, and I'm also unsure of if there are other cases where an instruction like that could be valid and shouldn't be replaced / warned on. Most likely not, but guessing and praying for the best is not something I really want to do.

For the moment, I simply have to say that I'm not sure what to do here, and I'll need help to prioritize it. The thing is, in DNX (or more specifically, Roslyn), this will be dealt with like a first hand citizen, so we'll have it solved there right from the beginning. I'm not sure how much we want to spend on trying to cope better with marginal cases in 2.x.

**Comment by miyconst** [comment]
@per-samuelsson thank you for the investigation. In spite of this issue really upsets me, I don't think you should spend more time trying to fix it.

Can you propose me any solution of providing property name of a db class property without typing any strings?

**Comment by k-rus** [comment]
> Can you propose me any solution of providing property name of a db class property without typing any strings?

I guess you can use our internal structures, which contain meta-data about database classes and properties for .NET code host use: `TypeBinding`, `TypeDef`, `PropertyDef`. They don't have any separate documentation. So it is necessary to look to their definitions and how they are used in Level1.

**Comment by miyconst** [comment]
@k-rus you misunderstood me.

I am trying to replace string sql queries with something that won't compile if the db class was changed.
So, my first solution for such query: 

```cs
Db.SQL<Product>("SELECT p FROM Product p WHERE p.Name = ?", name);
```

Was

```cs
DbContext<Product>(x => x.Name, name);
```

But `x => x.Name` is not supported by Starcounter. Any replacement?

**Comment by per-samuelsson** [comment]
> I am trying to replace string sql queries with something that won't compile if the db class was changed.

Yeah, it makes perfect sense, and this is kind of why the community has wanted C# operators like `propertyof`, `fieldof`, `methodof` etc for, in addition to the current `typeof`, but C# still lack that. 

> But `x => x.Name` is not supported by Starcounter. Any replacement?

Even if what you tried would work, it's still not really what we want I think. Because it's slow. Acessessing and interpreting the lamda expression like that is not compile time optimized, so I think that the overhead of doing queries that way could be quite bad. 

In 6.0, there is the new `nameof` (as I already mentioned), and that's at least compile time. We could recommend our users to use that in our examples, even though we could never *force* them too (because the signature still would have to be typed as accepting a string).

```C#
DbContext<Product>(nameof(Product.Name), name);
```

**Comment by miyconst** [comment]
Thank you @per-samuelsson, I go with `nameof` for now, and hope to see linq support in Starcounter 3.0. Closing this issue for now.
