### ISSUE TITLE
Bitwise and in SQL?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3313]
Is there support for bitwise operators? Like this:
https://msdn.microsoft.com/sv-se/library/ms174965.aspx

I get an exception, but maybe I'm doing it wrong (bitwise & on progress)?
> SELECT COUNT(*) FROM "HSM"."Concepts"."ComputerSoftwareRevisionState" c WHERE c."Revision"=? AND c.IsBound=? AND c.Progress&?

**Comment by k-rus** [comment]
Thank you for your question. No, bitwise operators are not supported.

**Comment by careri** [comment]
Ok. would it be possible to implement? Or is it to much work for to little gain?

**Comment by k-rus** [comment]
No enhancements of SQL will be done in the current query processor. New query processor will be open for enhancements. However, it is not so near yet.

**Comment by mtornwall** [comment]
@careri How about adding properties to the entity that test the state of the bits?

~~~
public bool ProgressState1 { get { return (this.Progress & 1) == 1; } }
public bool ProgressState2 { get { return (this.Progress & 2) == 2; } }
...
~~~

Not sure how this would affect performance, but it seems to me that even if you did have bitwise operations there would be no index to support them?

**Comment by dan31** [comment]
@mtornwall Thanks for a suggested solution! That's right, currently we don't support indices on calculated fields. Considering how to make such feature work, one have to track dependencies of the field on other fields to invalidate indices at a right moment when the calculated field value is changed. Efficient invalidation means some logical decomposition, so that invalidation doesn't call an avalanche of calculations, but only a reasonable part. Considering arbitrary nature of the result, one have to analyse the whole property getter. So, in general, for arbitrary codehost this is challenging. We want to support it and we are going to investigate the option in future.

**Comment by careri** [comment]
@mtornwall Thanks, already solved it with a similar solution. Just wondering if there was a more efficient way.
