### ISSUE TITLE
Refresh session data on server event

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3318]
Hi!

I think it was @alemoi or @warpech that showed me ```Session.ForAll```.
I though you could use this callbacks to push out data to an ongoing http session, i.e. a web browser.

When I push a button I run a task async, once the task completes I call Session.ForAll and get a callback. What should I do in this callback to push data to the initial browser where the button was pushed?

**Comment by careri** [comment]
I do the callback from Session.ForAll to a static method. In this method I check the Data-property of the session instance. The strange thing is that the Data-property is null.

I've added debugging that prints the SessionIdString when the session is created, when the button is invoked and when the callback to Session.ForAll is made.

It's the same id so the session instance is the same right?

>SESSION0C30B337B447909D00000020.Created, Data=AdminApp
SESSION0C30B337B447909D00000020.NewSetUploaded, Data=AdminApp
SESSION0C30B337B447909D00000020.OnSoftwareUpdated,Data=null

The first log is written when the session is created.
The second when the button is invoked, in the json Handle(Input method
The third is in the Session.ForAll callback.

Why is data null?

**Comment by alemoi** [comment]
Thank you for the question!

> I though you could use this callbacks to push out data to an ongoing http session, i.e. a web browser.

Yes, this is correct. One should use `session.CalculatePatchAndPushOnWebSocket();` when you are on scheduler.

However why is your `session.Data` is null - we have to investigate. @chrhol do you have any ideas?

**Comment by chrhol** [comment]
> However why is your session.Data is null - we have to investigate. @chrhol do you have any ideas?

No not really. Maybe the correct appname is not set? 

@careri: Could you check if `StarcounterEnvironment.AppName` is set to the name of your app or not.

**Comment by alemoi** [comment]
That's a good guess Christian. I will check the code as well.

**Comment by alemoi** [comment]
I looked at the code and its quite messy. For example, it does not filter current app when doing `ForAll`. I need to go through the code and fix it.

**Comment by careri** [comment]
You're right about AppName:
## SESSION19716834E6CCFA1500000000.Created, Data=AdminApp, AppEnv=HAD
## SESSION19716834E6CCFA1500000000.NewSetUploaded, Data=AdminApp, AppEnv=HAD
## SESSION19716834E6CCFA1500000000.OnSoftwareUpdated, Data=, AppEnv=

**Comment by alemoi** [comment]
I did a major reconsideration of session API related to running delegates on session. Basically it will be similar to WebSockets. Right now I am at testing stage and hope to describe/push everything tomorrow.

**Comment by alemoi** [comment]
I have pushed changes regarding Session. And added the following info to CHANGELOG (will update documentation tomorrow + blog entry):
- Added `Session.ToAsciiString()` to convert an existing session into an ASCII string. Later this session ASCII string can be used as parameter to `Session.ScheduleTask`.
- Added simpler task scheduling interface using static method `Scheduling.ScheduleTask()`.
- Session API has been refactored. `Session.ForEach` has been removed for its inefficiency, `Session.ScheduleTask` now replaces it.
- `Session.Destroyed` is now replaced by `Session.AddDestroyDelegate` because of apps separation issues.
- `Session.CargoId` is removed because of no use.


The Chatter application I updated as well.

**Comment by careri** [comment]
Ok, I'll give it a spin. So I have to keep track of live sessions my self? Or is there some session manager keeping track of live sessions?

**Comment by careri** [comment]
Action<Session,string> is the string the id of the session being passed as first arg?

**Comment by per-samuelsson** [comment]
@alemoi 

> Session API has been refactored. `Session.ForEach` has been removed for its inefficiency, `Session.ScheduleTask` now replaces it.

In [Replicator](https://github.com/Starcounter/Replicator), we are using `Session.ForAll`, and when I try to build against latest **pnext**, it will obviously fail b/c of the new Session refactoring:

https://github.com/Starcounter/Replicator/issues/23

Whats the correct replacement for `Session.ForAll`, as it's used here:

https://github.com/Starcounter/Replicator/blob/4383cb9b92efeda647fab14974980308d7661043/Program.cs#L215-L218

Thanks for any help!

**Comment by per-samuelsson** [comment]
> So I have to keep track of live sessions my self? Or is there some session manager keeping track of live sessions?

@careri

I'm not 100% sure, but I'm trying to find this out myself, and by looking at the recent Chatter redesign, it certainly looks so. Take a look at this snippet: [Chatter.MainHandler.Register()](https://github.com/StarcounterSamples/Chatter/blob/2e2fb521abc3f2984d0b672b63f90ae39069db5e/Api/MainHandlers.cs#L15-L49).

**Comment by per-samuelsson** [comment]
> Take a look at this snippet: [Chatter.MainHandler.Register()](https://github.com/StarcounterSamples/Chatter/blob/2e2fb521abc3f2984d0b672b63f90ae39069db5e/Api/MainHandlers.cs#L15-L49).

Also, [this line](https://github.com/StarcounterSamples/Chatter/blob/2e2fb521abc3f2984d0b672b63f90ae39069db5e/ViewModels/ChatGroupPage.json.cs#L75) seem to consume those self-tracked sessions, pushing out data on them.

**Comment by careri** [comment]
Ok. I did a similar solution. But only in memory, I'm propbably only going to have one session at the time.

Havn't tested the logic yet though :)

**Comment by alemoi** [comment]
Didn't know about so rapid response from you guys. Yes, the list of sessions is maintained by you now, exactly like it works for WebSockets, except that its strings instead of UInt64. Storing Session objects globally (static) is prohibited, its like storing SQL enumerators. Once you store session string, the only thing you can do is schedule a task on that session using Session.ScheduleTask.

**Comment by alemoi** [comment]
> Ok. I did a similar solution. But only in memory, I'm propbably only going to have one session at the time. Havn't tested the logic yet though :)

Let me know how it goes. I will write the documentation for new API today.

**Comment by alemoi** [comment]
I finally wrote the documentation and a blog post about the changes I made: http://starcounter.io/changes-in-session-and-scheduling-api-starting-from-build-2-1-1183/

**Comment by per-samuelsson** [comment]
> I finally wrote the documentation and a blog post about the changes I made: http://starcounter.io/changes-in-session-and-scheduling-api-starting-from-build-2-1-1183/

Looks good, nice! 

About this clause:

> Session API has been refactored. **Session.ForEach** has been removed for its inefficiency, Session.ScheduleTask now replaces it.

Do you mean `Session.ForAll`? Because that API was removed, and I don't remember I've seen a `ForEach`, but maybe both existed?

**Comment by alemoi** [comment]
Thanks for pointing! Its just a typo, I will correct it ;)

**Comment by warpech** [comment]
Any reason why `Session.ForAll` was removed, not deprecated? I strongly suggest deprecating instead of removing features that are used.

**Comment by dan31** [comment]
@alemoi, maybe you can make everything be deprecated instead of removing. I recall that your changes tolerate that. This will make much smoother move to upcoming 2.2.

**Comment by alemoi** [comment]
Yes,I had to remove the code internals but I think I can make it empty and throw exception. Next time I will obsolete the method and throw NotImplemented exception from an empty method.

**Comment by dan31** [comment]
Hm. Then guys, do we agree upon the term "deprecated" here? :) If one keeps ```ForAll``` in-place but throws an exception instead of actually running it, then the customer will see a degradation in runtime in a newer version, and maybe even in production, since he most likely might not have the 100% test coverage. That's the powers of strongly typed languages that you fail fast and early at compile time. So I think that by bringing back the empty method currently, you enforce the customer to punish himself really badly. @alemoi, do you believe that is a good model of deprecation? Or you meant something different there?

On the other hand, do deprecating means keeping the old version of the function for a while marked as deprecated and removing it later on, over some span of releases? Do we agree upon that definition, @warpech @alemoi?

**Comment by alemoi** [comment]
I agree, in cases if its possible. However what if the old code is faulty/very inefficient/etc? Like when we add new functionality - it contradicts with old?

**Comment by warpech** [comment]
> On the other hand, do deprecating means keeping the old version of the function for a while marked as deprecated and removing it later on, over some span of releases? Do we agree upon that definition, @warpech @alemoi?

I agree with this definition. https://en.wikipedia.org/wiki/Deprecation

**Comment by alemoi** [comment]
@careri how did it go with the original issue once you updated your code with the latest API changes? Do you need any further help?

**Comment by careri** [comment]
It's working, thanks

**Comment by alemoi** [comment]
Thanks for response! Closing the issue then.
