### ISSUE TITLE
pnext: nightly build failed with timeout on load and latency

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3331]
[this build](https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=717#_focus=10024)

**Comment by alemoi** [comment]
Thank you for reporting. I looked in the build log and I don't think anything is wrong with the test - it just took more time than allowed (15000 seconds). The database maybe become slower or something. Now since everything is fine with nightly runs - I will close the issue, since its not reproducible.
