### ISSUE TITLE
Add support to `staradmin.exe` for the `-oid` and `-lastoid` flags

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3360]
`sccreatedb.exe` and the `Create new database` page in the web administration interface both support setting the first and last object ID for the new database. This functionality should be added to `staradmin.exe` as well.

**Comment by per-samuelsson** [comment]
Like I said, I've already started considering this. My idea is to come up with a smart way to get this one done (or at least started) in the same scope: https://github.com/Starcounter/Starcounter/issues/3321. Thinking of it, they are quite related.

**Comment by per-samuelsson** [comment]
Just about to push this.

I've designed it so that everything we support in [the underlying REST JSON representation](https://github.com/Starcounter/Starcounter/blob/pnext/src/Server/Starcounter.Server.Rest/Representations.JSON/Database.json) Configuration can get specified on the command-line:

```
staradmin new db DataDirectory=C:\Users\Per\Foo DefaultUserHttpPort=1234 FirstObjectID=1 LastObjectID=19999999
```

And when things are added there, they are supported in this API too (until we blacklist them).

**Comment by per-samuelsson** [comment]
Merged and pushed as part of https://github.com/Starcounter/Starcounter/commit/84d4b8cbbf200e0157c7a2df5daa6ced98344853. Will be part of the upcoming nightly.

Note again that I've intentionally made this a **pnext**-only feature.
