### ISSUE TITLE
Question: Setting Typed JSON property key-value style?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3367]
Marginal case, but here it goes. Having this:

**Foo.json**
```json
{
  "Bar": 123,
}
```

materialized with `new Foo()`, is there some way to do this?

```cs
var foo = new Foo();
foo["Bar"] = 123;
```

And if so, what happens if I do either of these?

```cs
foo["Bar"] = "BarIsNotAStringItsANumber";
foo["Bar2"] = "doesntexist";
```

**Comment by chrhol** [comment]
This is another area which have some basic implementation but haven't been maintained for quite some time (and of course never used other then for prototype testing). 

You can use the syntax above, but the exceptions you get is not very informative. 

The first one, `foo["Bar"] = 123;` is bugged and you have to currently write `foo["Bar"] = 123L;` since the it has to use `object` and cast it to correct type.

The second and third example gives you runtime exceptions, since it is not possible to have overloaded indexers for each type.

**Comment by per-samuelsson** [comment]
Thanks, @chrhol. That answer what I was wondering.

I ended up doing a kind of custom little thing, based on trial and error, when I implemented this new `staradmin` feature. It it could be to any help for anyone in the future, it's here, this snippet [CreateDatabaseCLICommand.cs](https://github.com/Starcounter/Starcounter/blob/810bf3bbed1a01347fad39185af388533804d0f1/src/Server/Starcounter.CLI/CreateDatabaseCLICommand.cs#L62-L94).
