### ISSUE TITLE
An entity type declared a base class that did not match the base class previously bound

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3370]
I am trying to modify my database classes and got this error.

```
An entity type declared a base class that did not match the base class previously bound to the core database schema. 
The inheritance for class 'Sweoffshore.IdCard.IdCardHistory' has been changed from 'Sweoffshore.IdCard.IdCard' to 'Simplified.Ring1.Something'.
(ScErrTypeBaseDeviation (SCERR4127))
```

Do we have any documentation on what is supported and what is not supported?

cc @k-rus, @eriohl, @alemoi

**Comment by k-rus** [comment]
Basically, when you change your class for an existing database you are on your own. The only schema change automatically supported by Starcounter is adding new column or changing column type. The latter is probably not supported in pnext.
I don't know if there is any documentation.

**Comment by dan31** [comment]
@miyconst I believe you use pnext. If so, I expected that question to occur. Currently in pnext the schema upgrade works much more strict than in develop. For pnext, the behavior is nowhere explained now. However, since pnext have to be in use for customers, we need to provide a viable instruction on how to handle schema upgrades now. This might not be something users could deal with on daily basis, but that is what we have today. @chrhol, do you think you can provide a generic instruction on how to deal with schema upgrade in the best way today?

**Comment by miyconst** [comment]
Closing the issue as this is a known pnext limitation.
