### ISSUE TITLE
Starcounter.Application.Current.ResourceDirectories is empty

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3397]
Starcounter application takes `wwwroot` of the `WorkingDirectory` as a default `ResourceDirectory`.

Then why we don't add this value to the `Starcounter.Application.Current.ResourceDirectories` collection?

I need path to the `wwwroot` directory, or any other directory assigned as `ResourceDirectory`. This is only available when I explicitly set it, which is really annoying.

cc @alemoi, @andwah, @warpech

**Comment by miyconst** [comment]
cc @per-samuelsson

**Comment by alemoi** [comment]
Thank you for your question! I think @per-samuelsson is the best here to answer since he did some work around this recently. Thank you!

**Comment by andwah** [comment]
Maybe you can find your answer here #3099

**Comment by per-samuelsson** [comment]
@miyconst,

You are right, only those resource directories *explicitly* introduced is possible to iterate using the `Application.ResourceDirectories` API.

I was very precise when I documented this. Main documentation is [here](http://starcounter.io/guides/network/static-file-server/), and this additional https://github.com/Starcounter/Starcounter/issues/3099#issuecomment-160137228 provide some in-depth and samples. Furthermore, the API is document itself: [Application.ResourceDirectories](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Application.cs#L96-L110).

Bottomline: it's by design.

Furthermore, I had quite a long sprint of collecting inputs when I did that thing, and no one disagreed to the proposal at that point.

With all that being said, we can extend it of course. I don't think it's very tricky, even though I won't promise that, since I need to do some code reviewing first. It this is a feature we really want, I suggest we change the title to a feature request and try to add it to some planning.

Oh, and you can of course work around it by specifying ```wwwroot``` yourself, explicitly. Either in code or on the command-line. The provided documentation will show you how.

**Comment by miyconst** [comment]
@per-samuelsson 

Thank you for the answer.

I have read the documentation, and did not report it as a bug. Probably I am the first one who use this in production. For me it is very annoying to set up those directories on every machine I have to test the application.

The app has export feature. The feature creates a file and should save it in some place available for download. For sure this is `ResourceDirectory`.

Everything works fine, I setup my `ResourceDirectory`, then read it from `Starcounter.Application.Current.ResourceDirectories` and save file to there.

The annoying part is that I have to set those settings every time I use a new machine, and even more annoying part is to explain this to application consumers when answering the questions like "The app is not working, why?".

**Comment by miyconst** [comment]
>Furthermore, I had quite a long sprint of collecting inputs when I did that thing, and no one disagreed to the proposal at that point.

Sorry for not paying enough attention at that time. If I would realize that the `ResourceDirectories` collection will be empty unless values set manually, I would complain about it. :disappointed:

**Comment by per-samuelsson** [comment]
@miyconst 

What you write make sense, and I can understand your frustration. I suggest an approach like this:

1. We add an issue that adds any present [conventionally based directory](http://starcounter.io/guides/network/static-file-server/#directories-added-by-convention) to the list of directories returned by `Starcounter.Application.Current.ResourceDirectories`.
2. You make a workaround until we have time to actually develop that issue.

I can propose 2 workarounds.

Either you use the rather simple logic by which mean we add the ```wwwroot``` or ```src\[appname]\wwwroot``` in the code host to detect if such directory is present, and use it if its there (you know it will be exposed):

```cs
Main() {
  var app = Application.Current;
  var workDir = app.WorkingDirectory;
  var exportDir = null;

  var candidate = Path.Combine(workDir, StarcounterConstants.WebRootFolderName);
  if (Directory.Exist(candidate) {
    exportDir = candidate;
  }
  else {
    candidate = Path.Combine(workDir, "src", app.Name, StarcounterConstants.WebRootFolderName);
    if (Directory.Exist(candidate) {
      exportDir = candidate;
    }
  }

  if (exportDir == null) {
    // Try explicit resource directories?
    // Maybe fail the application, telling users they need to specify one, etc
    // TODO:
  }
}
```

Or, as an alternative, you introduce an explicit export directory using code, and use that:

```cs
Main() {
  var app = Application.Current;
  var workDir = app.WorkingDirectory;
  var exportDirectory = Path.Combine(workDir, "ExportedStuff");
  if (!Directory.Exist(exportDirectory)) {
    Directory.Create(exportDirectory);
  }
  AppsBootstrapper.AddStaticFileDirectory(exportDirectory);
}
```

WDYT?

**Comment by miyconst** [comment]
Sounds good to me. I have already created a similar workaround and the new issue is here https://github.com/Starcounter/Starcounter/issues/3398. Closing this one.
