### ISSUE TITLE
GitLab with Level0 is down

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3445]
git.starcounter.org gives me:

>504 Gateway Time-out

**Comment by alemoi** [comment]
@linkdata do you know if something happened with Linux machine? Any changes there?

**Comment by linkdata** [comment]
It's up, but it looks like some security patches have been auto-applied. I'll restart it.

**Comment by linkdata** [comment]
Disk was full. Should be up now.

**Comment by alemoi** [comment]
Thank you for checking this!

**Comment by k-rus** [comment]
The server, git.starcounter.org, is down again with the same error, which implies no builds on build server.

**Comment by linkdata** [comment]
...and the disk was full, again. GitLab is using up pretty much the entire SDD, and I'm running out of things to clean up. @dan31, how about that new server?

**Comment by dan31** [comment]
@linkdata @k-rus What does it exactly utilise on space, is that dropbox-based backups or something.

**Comment by linkdata** [comment]
Yes, the Dropbox uses up most of the space.

**Comment by k-rus** [comment]
Putting dropbox on operational server seems to me a bad idea, especially on the same disk.

@dan31 
Can you move dropbox from the disk or the server and solve this vital issue for at least some time?

**Comment by linkdata** [comment]
> Putting dropbox on operational server seems to me a bad idea, especially on the same disk.

Agreed. I was quite surprised to find it there.

@dan31 @alemoi I don't know much about Dropbox (I never use it myself), but if you like, I can try to remove it. Do we need it to be there? What is it used for?

**Comment by alemoi** [comment]
We can for example for now create a siblings empty folder and start sybcing there and remove the previous folder in SelectiveSync in dropbox options (NOT just delete).

**Comment by dan31** [comment]
To all guys, please follow the advise since now on, all these issues regarding infrastructure please let us try to create at here: https://github.com/Starcounter/AdminTrack/issues. As an alternative, you can follow @eriohl approach and post to a __private__ gitter: https://gitter.im/Starcounter. Believe me, our users have no interest in knowing when our gitlab stops working, nor they are interested in tremendous amount of issues on the public tracker. We also do not want to spend time crunching on these issues instead of building a great product. I hope you understand my point and follow :)

**Comment by dan31** [comment]
I moved most backups from Gitlab folder to Gitlab-Archive folder. This should probably help. Write if it helps there.
