### ISSUE TITLE
Investigate removing of htmlmerger

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3495]
As discussed today with @chrhol on Hangouts, a very interesting way of solving problems related to `htmlmerger` (such as https://github.com/StarcounterPrefabs/Launcher/issues/224) would be to remove `htmlmerger`.

Replacement would be to teach [`starcounter-include`](https://github.com/Starcounter/starcounter-include) and [`Launcher's starcounter-include`](https://github.com/StarcounterPrefabs/launcher-include) the concept of namespaces. Client side web component would iterate over namespaced responses and load each of their `Html`s individually, without the need for HTML merging on the server.

JSON namespaces might be changed from object to array. See [the example](https://gist.github.com/warpech/217dda5bef531c94227dd35affbc808f). This would be much easier for Polymer template binding.

**Comment by miyconst** [comment]
+1! Maybe this could also help to solve the order of merged content?

**Comment by tomalec** [comment]
:+1: for the idea of solving problems by removing code :)

> Replacement would be to teach starcounter-include and Launcher's starcounter-include the concept of namespaces. Client side web component would iterate over namespaced responses and load each of their Htmls individually, without the need for HTML merging on the server.

Then we would have to face following problems:
- even bigger performance hit, as we would need to execute `n^m` more HTML Imports (XHR requests for polyfilled browsers) - we already heard complains about it,
- lifecycle / async flow of content - it may be hard to debug and work with parts of partial (tiles) being stamped in and out asynchronously in quite unpredictable order,
- blinking related to above.

Regarding to async problem I got an idea - described below.

> JSON namespaces might be changed from object to array

Then it would be much harder to pick Launcher's namespace to get layout & co.

---

Idea to remove namespace awareness from `<starcounter-include>`.

Instead of "teach [`starcounter-include`](https://github.com/Starcounter/starcounter-include) and [`Launcher's starcounter-include`](https://github.com/StarcounterPrefabs/launcher-include) the concept of namespaces" we can use the fact that [`imported-template`](https://github.com/juicy/imported-template) (used by both) is already aware of it - it uses `<imported-template-scope>` to apply correct name-spaced scope to given nodes.

Therefore, `imported-template` could receive name-spaced map of URLs to import, then once all are loaded it will stamp them together. In case we would like to change this behavior in future, we could even make it configurable by attribute whether it should stamp them all together or on-by-one.

**Comment by tomalec** [comment]
However, both ideas mentioned at https://github.com/Starcounter/Starcounter/issues/3495#issue-148108899 and https://github.com/Starcounter/Starcounter/issues/3495#issuecomment-211407011 are in fact moving `htmlmerger` code to the browser rather than removing it

**Comment by warpech** [comment]
It was decided yesterday that we don't remove htmlmerger, but we are removing a "Html" property from the namespace root level in the serializer. @tomalec will move that part of the logic to `starcounter-include`: https://github.com/Starcounter/Starcounter/issues/3539
