### ISSUE TITLE
App doesn't serve request while stopping another app in the same database

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3542]
I have two apps running. The first app stops serving requests with 404 while another is stopping. Everything goes fine again once the second one is stopped.

cc @alemoi

**Comment by alemoi** [comment]
When stopping an application, the codehost restarts, meaning that handlers are re-registered. Meaning that there is a moment when all codehost handlers are unregistered, because the whole sccode processes shuts down. Its current design, I don't think I can do much about this. What do you think @dan31 ?

**Comment by dan31** [comment]
@alemoi true, in current design (stop app = restart codehost) not much you can do. This is until dnx, to conclude.

**Comment by per-samuelsson** [comment]
I can just confirm @alemoi's conclusion, this is our current 2.x hosting implementation and by design, and nothing we really can change. The alternative would have been to use AppDomain's instead of processes initially, but we chose not to, and hence we get this behavior.

**Comment by bigwad** [comment]
Technically, it's possible, once we can run many IWP against the same database (https://github.com/Starcounter/CompanyTrack/issues/64#issuecomment-210401741). We may start new codehost, allow it to register handlers,switch processing from old codehost to the new one and finally stop old codehost. 
Even if won't go this way now, probably it makes sense to keep this issue on track to ensure dnx won't suffer the same problem.

**Comment by per-samuelsson** [comment]
> Technically, it's possible, once we can run many IWP against the same database [...] Even if won't go this way now, probably it makes sense to keep this issue on track to ensure dnx won't suffer the same problem.

Yep, that's the idea. My thinking is that once we support the new multi-host / database design, the default in development scenarios will be to isolate apps one per process. That will mean stopping one app is not affecting the others.

And that we supplement that with a feature that allows stopping apps in multi-app hosts (normally in production) using a scheme something like this:

* Spawn a new host (duplicate)
* Load all weaved apps into that new host, but not invoke their entrypoint
* Take down the abandonded host
* Run entrypoints in the new

The thing we must get right is mainly handler registration, since if apps in the new host register handlers that are already registered in the old host, they will of course fail. But maybe we could even support some kind of scheme that when a handler is registered in a second host, and it's in some certain state (like *restarting host state*), every such registration does not fail, but instead invalidate the previous handler endpoint, replacing it with the new one.

But all that is for a future story. :smile:
