### ISSUE TITLE
KB Request: What changes to database classes are considered safe?

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#3559]
In a conventional RDBMS I can use `ALTER TABLE ...` statements to synchronize changes to the models with the persistent representation. Since Starcounter removes this distinction I think there ought to be some documentation describing how I can safely change the definition of a database class without breaking existing data.

Some relevant questions:
1. If I have a database class that has some instances in the database, is it safe to:
   - Add fields?
   - Remove fields?
   - Change field types?
2. If I have a database class that **doesn't** have any instances, is it safe to:
   - Completely change the definition of the class (i.e., any sequence of field additions, changes and removals)?
   - Remove the class altogether?

**Comment by dan31** [comment]
@mtornwall it is a good question. @k-rus as I recall back to 2014 we actually summarised what changes give what when you do them. Today we are approaching 2.3 (pnext), where schema change isn't yet possible in a way of previous 2.x. Hence we'd have to go back to the topic. This issue is a good point to dance from. @k-rus do you think you can bring back the schema change algorithm in text form? Then we could put it on .io.

**Comment by k-rus** [comment]
Schema upgrade in 2.3 was implemented by @chrhol Basically it is just possible to add new column.

In my opinion an important question is how to alter schema. We had such descriptions in some issues, but we need to search for them.

**Comment by mtornwall** [comment]
What's the status in the pre-pnext versions?

**Comment by k-rus** [comment]
> What's the status in the pre-pnext versions?

Can you clarify your question? I don't really understand what you want to know. Do you want to know which database classes are accepted in pre-pnext version? Or do you want to know about release of 2.2, which is between current stable and pnext, and this is off-topic here?

**Comment by mtornwall** [comment]
> Do you want to know which database class chagnes are accepted in pre-pnext version?

This.

**Comment by k-rus** [comment]
In current stable in addition to adding new property it is possible to change a type of an existing property. In this case it will try to migrate data, but this can fail for obvious reason.

I forgot to mention that in current and future versions removing a property from a database class is also accepted. This does not change anything in the database, but the property becomes unavailable.

So if you rename a property, it will be accepted, since it will be treated as adding new column and removing existing. No data will be migrated, so the system will not treat it as renaming, since we cannot know what was in the mind of the developer.

**Comment by mtornwall** [comment]
Exactly what I needed to know. Thanks @k-rus!

**Comment by bigwad** [comment]
My experiments and source code analysis show following behaviour:


schema modification| effect in 2.2|effect in 2.3
------|-----|-----
type change|data loss without warning|error on upgrade, so data is intact
field remove|data loss without warning|data is intact. safe to add the field back

**Comment by dan31** [comment]
All legit refactorings in 2.3 are thoroughly documented in here: https://docs.starcounter.io/guides/working-with-starcounter/database-refactoring/.
