### ISSUE TITLE
Getting the IP address of the client from the session

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#3564]
As far as I know the `Session` object doesn't currently expose any functions or properties that allow user code to read the IP address of the client that owns the session.

Having access to this information would be useful for security logging etc.

I realize that the "owning client" is somewhat ambiguous, so I'll settle for the last client that touched the session.

cc @chrhol

**Comment by alemoi** [comment]
Just a note: IP address can be saved when the initial HTTP request comes, along with the session string  ID. But you probably know about this solution :)

**Comment by warpech** [comment]
I might be totally wrong, so @chrhol and @alemoi correct me. But:

Starcounter session is just a long living in Json object. It is not necessarily a web session, so it doesn't know the concept of "IPs". I think the best approach would be to save the request's IP information as a private field in your Json class.

**Comment by chrhol** [comment]
I agree with you @warpech. It's should be up to the application if it want to keep track of client-information. One part we need to improve on is this though:

>  I think the best approach would be to save the request's IP information as a private field in your : Json class.

We have no notion of private state today. We should enhance the `Session.Data` property to distinguish between exposed (to clients) and serverside-only state.

Storing values directly in the class declared in the code-behind is not something that should be recommended. It will work for today, but later on it will probably not work, since the long-term goal is to have the actual instance of `Json` as a proxy-object, that will be recreated when needed, and all state read from a semi-persistent layer to survive restarts of the codehost (very similar to how database-objects work, the actual instance only contains a pointer used when reading/writing values). For that to work, the value needs to be declared in the JSON-by-example file.

**Comment by mtornwall** [comment]
Okay, you have me convinced. I withdraw my suggestion. :-)
