### ISSUE TITLE
pnext: "staradmin kill all" returns error code 999

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3567]
As observed during extended daily pnext. Shows error `Access is denied`.
Here is the place in the build log:
https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=3463#_focus=8099

Probably there should be a retry inside staradmin when this happens.

**Comment by per-samuelsson** [comment]
I've seen this locally several times as well, and I'm quite sure it only happens in **pnext**.

My suspicion is that it relates to the different way back-end processes are managed in **pnext**, possibly relating to that data manager now start the log writer (I think), and killing that process should no longer be done (because it should be killed, reacting to the killing of the data manager). But that's just a guess.

I'm also quite sure that if you instantly run `staradmin kill all` after the error, no process are killed, indicating that the failing process actually was killed after all.

**Comment by alemoi** [comment]
Yes, its pnext. Im thinking to put a few retries there.

**Comment by alemoi** [comment]
Tonights nightly pnext failed, because of this issue: https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=3953#_focus=13009

I will add a retry tonight.

**Comment by alemoi** [comment]
I have pushed the fix with retries now in "staradmin kill all". Lets see if its a problem again.

**Comment by dan31** [comment]
@eriohl @bigwad can you pls assure this fix is actually a proper thing to introduce in pnext? My little concern here is that the fix introduced and described in this issue looks more like a temporary thing not really addressing the proper way. Or maybe I am wrong?

**Comment by eriohl** [comment]
```staradmin kill all``` just goes over the processes in the task manager and terminates them on name. It is not the proper way to shutdown the system regardless.

Access denied on what process exactly? I know I've seen this on attempting to shut down the prolog process. But that I can't see being related to **pnext**.
