### ISSUE TITLE
pnext: Attempt to improve TT4 decoder performance

### ISSUE THREAD

**Issue by eriohl** [Starcounter/Starcounter#3580]

**Comment by bigwad** [comment]
So far. Decoder performance improved for 80%. For tpcc test it gives 25% performance boost.
More to come.
Have dipped into turbotext, I see more opportunities to increase performance (both encoding and decoding, but much for decoding) and to decrease encoded string size.

What's wrong now and what I want to do with it?

1. Symbol ratings are too coarse. This probably leads to inefficient encoding. I'll address it by redesigning collation.xml files structure.
2. Algorithm of assigning codes to symbols is probably suboptimal. Once I have proper symbol ratings, I'll implement classic Hu-Tucker algorithm and will see the difference. But definitely something wrong with suffixes.
3. Turbotext uses prefix-free codes, that probably is not optimal in our case due to ordering requirement. I'll take a look at non prefix-free codes.

And the last one that I'm not going to investigate right now, but it may be of some interest.
4. Turbotext library doesn't generate code in compile-time anymore. As consequence it's possible to get rid of generated collation dlls. It allows to easily create custom collations. Say, we may provide user with utility that scans user database and generates optimal encoding for their specific data.

**Comment by bigwad** [comment]
And all proposed changes will break compatibility for current pnext clients.

**Comment by eriohl** [comment]
80% sounds really great!x

> And all proposed changes will break compatibility for current pnext clients.

Right. Although if this prefix stuff is to be put into place this will be true anyway. @dan31? Also: We need to support changing the encoding without rebuilding the database anyway (although I was hoping to avoid doing this work now).

> Turbotext uses prefix-free codes, [...]

I though all characters was required to have a prefix (although the prefix would then obviously be the same for a lot of different characters). I guess that means that a prefix can represent multiple characters then? This sounds like a good is a good thing to me. You remember this discussion regarding sorting MacDonalds and McDonalds. It is certainly also useful if you want phonetic sorting. Also there is probably cases where you want to completely ignore a character in sorting although I can't think of one right now.

**Comment by dan31** [comment]
> Right. Although if this prefix stuff is to be put into place this will be true anyway. @dan31?

Oh, yes, sorry guys to answer here, but I didn't have time to formulate in writing in a correct thread. Basically, what we decided with SWO (the only one using pnext right now) is following. They do their demo runs and POC projects on the existing version right now (like the one of today), and we do not introduce breaking change such as prefix thing before end of POC. When the POC is ended (2 more weeks at least), they are comfortable to through away all generated data. And we can safely migrate them into 2.3 with no cumbersome data migration. For the rest of customers, they don't run log streamers and a change with prefix when they start to use 2.3 alltogether is something they shan't notice.

@bigwad if you put yourself in place of users, what will be breaking related to turbotext? Meaning, how much shall I change in my setup in order to adopt to this changes. Keeping in mind that starting from 2.3 release all develop users effectively become pnext users. Surely I will do unload/reload, that is just fine. What else?

**Comment by bigwad** [comment]
>Surely I will do unload/reload, that is just fine. What else?

Nothing more.

**Comment by bigwad** [comment]
Pushed another non-breaking optimization (10% on top of previous one). Now decoding performance has almost reached the encoding one.
Starting off with breaking improvements mentioned above.

**Comment by bigwad** [comment]
Most of breaking improvements I planed are done:

1. Made it possible to assign fine-grained letters probabilities inside collation.
2. Rewrote almost from scratch turbotext encoding generator using Hu-Tucker algorithm to follow fine-grained probabilities.
3. Found some studies of letter distribution in English texts and updated European collation with probabilities I've found.

In essence it reduced typical encoded text by 10%, but increased decoding time (probably due to more cache misses). Though it still significantly better than was before optimizations, it could be optimized much more with cache friendly decoder.

As a side effect, new generator made it possible to generate better x-tid collation. Now it utilizes bit space more efficiently.

So, to do:
1. Cache friendly decoder.
2. Investigate [partial alphabetic trees](http://www.sciencedirect.com/science/article/pii/S0196677405000672) and non-prefix free code to reduce size of encoded text even more.

**Comment by bigwad** [comment]
Done cache friendly decoder. 
Here are some numbers to clear the progress:

Step | decoding rate (Mc/s) | encoding rate (Mc/s) | avg bits per char
------------ | ------------- | ------------ | -------------
Original | 1.33 | 3 | 6.37
All non-breaking improvements | 2.54 | 3 | 6.37
Breaking improvements (new generator) | 2.7 | 3 | 5.83

With new cache friendly decoder decoding speed should increase proportionally to avg symbol size decrease. Thus the next point of my plan -  to investigate partial alphabetic trees and non-prefix free code to reduce size of encoded text even more.
And encoding speed is questionable. I expected it to increase as symbols size decreased. But that haven't happen.

**Comment by bigwad** [comment]
@dan31, I'm ready to merge it to pnext.
Has SWO test project already finished?

**Comment by bigwad** [comment]
Done.
Have investigated the paper ragarding [partial alphabetic trees]( http://www.sciencedirect.com/science/article/pii/S0196677405000672). It briefly addresses our problem but suggests only brute-force like solution, which has unacceptable cost.
Haven't investigated prefix free codes. Probably will return to it later, but I don't expect significant improvement out of this.
