### ISSUE TITLE
ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3611]
I am using AVG antivirus, and I get this error on launching apps in SC if my Antivirus is fully active. But if I Disable my Web protection in AVG (as shown in attached image) everything works fine. 
![antivirus](https://cloud.githubusercontent.com/assets/4388707/15212915/ee119220-1843-11e6-9c19-ad93c5743bd2.jpg)

Is there a way to keep my Antivirus active and still use SC?

**Comment by dan31** [comment]
@atifwaqar there were times when Starcounter generated dlls on disk and AVG was very concerned about it. Now we don't do such thing. So, probably AVG doesn't like us messing with the ports. More likely, we are simply in the blacklist db of AVG because it has been concerned about us big time in the past. Could you simply point AVG to not track Starcounter folders and processes?

**Comment by atifwaqar** [comment]
@dan31 I have added the following directories in AVG exception list :

1. C:\adfenix-backend\  (this one have all the code and apps in it)
2. C:\Program Files\Starcounter\
3. C:\Users\atif\Documents\Starcounter\
4. C:\TeamCity\

But AVG still blocks my apps somehow. So i think for now i'll have to keep my AVG disabled. but I will let you know if i find a workaround. 

Thanks for you suggestion.
