### ISSUE TITLE
ScErrInvalidObjectAccessAbort with multi transactions

### ISSUE THREAD

**Issue by aloscha** [Starcounter/Starcounter#3619]
I would like to know how handle multi long running transactions.

I have few classes in relation like that: ChatMessage --- TextRelation --- ChtaMessageText
And create some sample:

            Handle.GET("/helloworld/partials/helloworld/{?}", (string objectId) => {
                var relation = (TextRelation)DbHelper.FromID(DbHelper.Base64DecodeObjectID(objectId));
                return new Transaction(false,false).Scope(() =>
                {
                    var json = new PersonJson();
                    var chatmessatext = new ChatMessageText();
                    relation.Content = chatmessatext;
                    Transaction.Current.Commit();
                    return json;
                });
            });

            Handle.GET("/HelloWorld", () =>
            {
                return new Transaction(false, false).Scope(() =>
                {
                    var master = (MasterPage)Self.GET("/helloworld/partials/master");
                    var chatMessage = new ChatMessage();
                    var relation = new TextRelation
                    {
                        Concept = chatMessage 
                    };
                    master.CurrentPage = Self.GET("/helloworld/partials/helloworld/" + relation.GetObjectID());
                    return master;
                });
            });

So generally I try to something like this

            Transaction1{
            object1 = new;
                        Transaction2{
                                    object2 = new
                                    object1.Relation = object2
                        }
            }

And when I commit Transaction2, I would like to have in DB only object2 (now I get error). Also when I commit Transaction1, then Transaction2 should also commits, because it's child of Transaction1 (parent).

That situation will occurs in many applications. Let's imagine I would like to make a bank transfer, when I finish input account number I click save it and in current transactions model, whole data will save (but need only account number).

**Comment by chrhol** [comment]
> And when I commit Transaction2, I would like to have in DB only object2 (now I get error). Also when I commit Transaction1, then Transaction2 should also commits, because it's child of Transaction1 (parent).

Short answer is that it's not possible. There are no support for child-transactions that can be committed/rollbacked independently while still see changes from the outer transaction.

if you use `new Transaction(false, false).Scope(...)` then you explicitly say that you want a new (long-running) transaction and that the data modified in the scope of this transaction will not be visible until it's committed.

Responses for partials should be careful with creating their own transactions, since it will disable the functionality for blending and sharing modified data on the client. Take for example barcode and product apps, if the partial for barcode would create it's own transaction, it would no longer reflect changes made from the product-app.

In this example, it's a bit strange that the relation is set and committed in the transaction for the partial. Isn't that up to the other transaction that have the new `ChatMessage` object. If `ChatMessage` is rollbacked, then the relation should also be rollbacked (of course this is based on the short answer) .

I think, in this case, I would simply have the whole thing in one transaction, that is remove the transaction in the partial-handler, and use `Db.Scope()` instead of `new Transaction().Scope()`

> That situation will occurs in many applications. Let's imagine I would like to make a bank transfer, when I finish input account number I click save it and in current transactions model, whole data will save (but need only account number).

I'm not exactly sure what you mean here. But if we're talking an operation that for example transfer money between accounts, then long-running transactions should not be used at all. Then it would be more suitable to use a short-running transaction with conflict detection, `Db.Transact(...)` instead.

Some information on how transactions looks and work can be found on starcounter.io
http://starcounter.io/guides/transactions/
http://starcounter.io/guides/transactions/more-on-transactions/
http://starcounter.io/guides/transactions/long-running-transactions/

**Comment by aloscha** [comment]
Thanks for answering @chrhol, I think we could close the issue.
