### ISSUE TITLE
TypedJson: Invalid code generated when not explicitly extending `Json`

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3624]
1. Create TypedJson with code-behind
1. make your partial class definition implement `IBound<Something>`, but don't explicitly extend `Json`. It should look like this: `partial class Page : IBound<Something>`
1. Generated code references `IBound` type without type parameter, causing compilation error. At no point SC informs you about why that happened
1. Explicitly extending `Json` probably shouldn't be necessary - in C# it's enough if just generated partial declares extending.

SC version: 2.2.1.2149

**Comment by per-samuelsson** [comment]
Thanks for reporting this @joozek78.

Coincidentally, we are just undertaking some work trying to improve the Typed JSON code-behind parser, in #3439 (and have a related survey in #3625).

Even when turning to Roslyn, in this first iteration, we'll have somewhat a hard time to validate base types of user defined JSON classes, caused by the fact that we can not iterate the tree up to the root (since we allow custom inheritance, and can't resolve all references when compiling).

Still, I'll make sure we consider your case, and see if we can improve in the error reporting. I'll take it in as part of #3439.

> Explicitly extending Json probably shouldn't be necessary - in C# it's enough if just generated partial declares extending.

About that, I agree and at the same time, I don't. If it would be possible, I would actually rather go in the direction that code behind classes *must* explicitly define the inherit `Json`, since it makes it easier to see what is going on. But again, we can't enforce that, since we must allow inheritance and we can't walk the tree. So now it's something in between.

**Comment by chrhol** [comment]
Probable cause of this: https://github.com/Starcounter/Starcounter/issues/3439#issuecomment-219715060

**Comment by per-samuelsson** [comment]
With #3439 done, I've made sure we can now handle the case in the OP. @joozek78, let us know if you test it and find it to be a problem still in a version built after "now".
