### ISSUE TITLE
Question : How to handle duplication of data?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3663]
I am working on a messaging app, and I have a class as following : 
```
using Starcounter;
namespace ChatBot.Database.Facebook
{
    public class Sender : Concept
    {
        public string id;
    }
}
```
At this stage I am the only `sender` sending messages (as the app is under-development). and I expect that DB have only 1 `sender` object, but this is not the case. I can see hundreds of objects containing the same `id`, which makes things difficult for me.

Is there a simple way to handle this duplication issue? 

(Note : This issue is connected to the same task I mentioned in [this question](https://github.com/Starcounter/Starcounter/issues/3661), where I create DB objects through a JsonString)

**Comment by per-samuelsson** [comment]
Well, the only reason there could be hundreds of `Sender` instances with the same ID is because they have been explicitly created like that.

If you need uniqueness, we provide that with the built-in key ("object ID") that is assigned to every object, and via [unique indexes](http://starcounter.io/guides/sql/indexes/).

**Comment by miyconst** [comment]
I don't have much do add, @per-samuelsson described the situation.

The `id` field is treated exactly the same as any other field, for example `Amount`. You do not ask:

>Why there are multiple orders with same `Amount`?

Whatever application creates, database saves. If you need uniqueness, than you have to explicitly set unique constraint and write your application in that way that it does not violate the constraint.

**Note:** trying to commit a transaction which violates unique constraint will result in an exception.

Please close the issue if your questions was answered.

**Comment by dan31** [comment]
This is the essence of operational databases. You have a row store, rows (records, tuples) contain the cells with data values. Each cell stores a real physical representation of the value. The outcome is fast access to the rows and cells (fields) inside the row. Being in-memory makes it instant. If one has inefficient domain data model, the space consumption grows substantially. Going to more normalised data models (3NF) reduces memory footprint since you take big shared parts of the table into a separate table. JOINing these tables is still pretty fast for in-memory engines.

**Comment by dan31** [comment]
Atif, you probably want to refer to a Sender object by its OID (primary key), which will be a foreign key that you would store in your Msg object, rather than creating the whole Sender object each time the Msg comes. Correct? (by this you get normalised form of your model)

**Comment by atifwaqar** [comment]
> Atif, you probably want to refer to a Sender object by its OID (primary key), which will be a foreign key that you would store in your Msg object, rather than creating the whole Sender object each time the Msg comes. Correct? 

@dan31 This is correct. I read [unique indexes](http://starcounter.io/guides/sql/indexes/) as @per-samuelsson suggested. I created a new project just to test it, It really works fine : 
`Db.SQL("CREATE UNIQUE INDEX tableIndex ON TestTable (Name)");`

I noticed that when I create this sort of UNIQUE-KEY index, I can not create a new object if `Name` already exists in DB, But I am facing 2 issues : 
1. Case Insensitive (May be it is needed, so this is manageable)
2. I get exception if the Name already exists in DB. 

Now for case 2, is there anyway that instead of getting an exception I get the existing Object?
The reason I am asking for this is related to [Issue 3661](https://github.com/Starcounter/Starcounter/issues/3661#issuecomment-222502348)

And sorry, I am not a C# expert, may be there are way around this thing in C# but I'm kind of stuck on this issue for a long time.

**Comment by k-rus** [comment]
> 2. I get exception if the Name already exists in DB.
> 
> Now for case 2, is there anyway that instead of getting an exception I get the existing Object?

You can write a group or sorting query to get duplicates and then programmatically resolve them.
