### ISSUE TITLE
The transaction was aborted because of a failure to allocate file storage space.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3667]
SC Version 2.2.1834

System Status :
![sc error](https://cloud.githubusercontent.com/assets/4388707/15666326/873012bc-2710-11e6-8333-91f56bd299ec.jpg)

Error Message : 
```
Starcounter.TransactionAbortedException: ScErrOutOfFileStorageAbort (SCERR8010): The transaction was aborted because of a failure to allocate file storage space.
Version: 2.2.1834.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8010.
   at Starcounter.Internal.TransactionManager.Commit(Int32 tran_locked_on_thread, Int32 detach_and_free) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Starcounter\TransactionManager.cs:line 701
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Starcounter\Db.cs:line 354
   at AdFenix.ApiMirror.FacebookHelper.None(String requestbody, Int32 user) in C:\adfenix-backend\src\ApiMirror\FacebookHelper.cs:line 258
   at AdFenix.ApiMirror.FacebookActions.GetRightAction(String requestBody, Int32 user, String operation) in C:\adfenix-backend\src\ApiMirror\FacebookActions.cs:line 49
   at AdFenix.ServletEndpoints.ResponseFromPOST(String operation, Request r) in C:\adfenix-backend\src\ApiMirror\ServletEndpoints.cs:line 137
   at AdFenix.Server.Handlers.ServletEndpointHandler.<>c.<Register>b__0_0(String operation, Request r) in C:\adfenix-backend\src\Server\Handlers\ServletEndpointHandler.cs:line 12
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
ErrorCode=8010
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8010

```

**Comment by atifwaqar** [comment]
Probable way to reproduce this issue : 
I had 20 GB ram on this system, with Paging on. And the DB loading process required more than 20 GB of RAM, so in background while loading, it was loading the DB and to free-up the ram it was [paging](https://blogs.technet.microsoft.com/danstolts/2013/01/how-to-change-the-size-of-virtual-memory-pagefile-sys-on-windows-8-or-windows-server-2012/).
Yesterday I added 16GB Ram to the server, turned off the paging, restarted windows and tried to launch the apps but i was getting some weird error while launching the apps. So I turned on the Paging option again, And my apps launched perfectly after turning on the paging option. 

And now I am getting the above errors in my SC Logs.

**Comment by per-samuelsson** [comment]
@atifwaqar 

Take a look at related #3222.

**Comment by atifwaqar** [comment]
@per-samuelsson the last comment says : 

> This issue has been addressed in next version of Starcounter (where the image file has been dropped.)

and I have the latest Stable SC Version.

**Comment by per-samuelsson** [comment]
> [...] and I have the latest Stable SC Version.

Ah, sorry, my bad. Sometimes we are not clear enough in answering these support issues.

The statement in that issue 

> This issue has been addressed in next version of Starcounter (where the image file has been dropped.)

refers to a different branch of Starcounter, where we still have no stables at all, but only nightly builds. If I'm not wrong, you are using either our latest stable (2.2) or nightly builds on that (i.e. 2.2.1), while the builds where this is redesigned is in 2.3-based versions (working name "pnext"). Those builds can already be tested ([latest](http://downloads.starcounter.com/download/Starcounter/PnextNightlyBuilds/latest)), but I'm not sure you want to go there already.

Meanwhile, I understand you want to get pass this problem you have right here and now, but I'm not sure how though.

cc @dan31 @eriohl

**Comment by atifwaqar** [comment]
Ok I'll wait for Dan's approval, if he or anyone of you recommend to upgrade the SC version on this Live server then I will upgrade.

Also my apps just crashed with the following error : 
![image](https://cloud.githubusercontent.com/assets/4388707/15670178/5246541c-2724-11e6-99fe-3c83a5a8c637.png)

Do you think this crash and the `The transaction was aborted because of a failure to allocate file storage space.` are somehow connected?

**Comment by eriohl** [comment]
In version < 2.3 you need to rebuild the database (recreate the image files) when moving to a machine with more memory (or upgrading the memory of the machine your on). The reason for this is that the logical size of the image is by default configured to fit the size of the memory of the target machine so it will run out of image file space as the database expands. This problem is addressed in 2.3.

Rebuilding the database is easiest done by doing and [unload/reload](https://github.com/Starcounter/Starcounter/wiki/Reloading-database-between-Starcounter-versions).
This is kind of a cumbersome process but unfortunately there is no other way to address the issue.

**Comment by per-samuelsson** [comment]
> Do you think this crash and the `The transaction was aborted because of a failure to allocate file storage space.` are somehow connected?

Sorry @atifwaqar, I don't dare to answer that, but it doesn't seem unlikely. Maybe @eriohl can comment on it?

**Comment by eriohl** [comment]
**ScErrBadMemoryCksumCheckp** occurs when the snapshot doesn't match what has been flushed to file. This should not happen and indicates a bug in how image memory is marked as dirty. Not sure if it is related but probably in the sense that the other error has triggered the bug.

**Comment by atifwaqar** [comment]
@per-samuelsson. I migrated the live server on another server, It was a mess but its pretty much handled now.
Just out of curiosity, I just installed ([latest](http://downloads.starcounter.com/download/Starcounter/PnextNightlyBuilds/latest)) on the server, as you suggested. But now I am getting a new error : 
`A fatal error was detected: ScErrCantFindImageFile (SCERR4117): One or both of the image files are missing.`

Its not an issue for me as I have migrated my DB to a new server, but I thought it will be good to share the details of this issue.

**Comment by per-samuelsson** [comment]
> Just out of curiosity, I just installed ([latest](http://downloads.starcounter.com/download/Starcounter/PnextNightlyBuilds/latest)) on the server, as you suggested. But now I am getting a new error : 
`A fatal error was detected: ScErrCantFindImageFile (SCERR4117): One or both of the image files are missing.`

Yes, that's kind of expected (but o/c undesirable) because you moved versions between 2.2 and 2.3 ("pnext"), and there are rather massive changes underneath, including that database files are now in a different format (and with different naming, hence the error).

I'm not sure what the status is or how we recommend to do this migration, if we have some kind of tutorial, etc. Would be good to get that clarified.

cc @dan31 @k-rus @bigwad, what path has other customers taken to do this? Are there any docs / guides?

**Comment by atifwaqar** [comment]
Aha, Thanks for the info, I was thinking of upgrading another of my Live server to 2.3 :P
Good thing I tried it on a Non-Live server. Thanks for the info. Also do let me know if there is any Tutorial on how to upgrade from 2.2 to 2.3. So that im well prepared before I do this upgrade.

**Comment by k-rus** [comment]
> cc @dan31 @k-rus @bigwad, what path has other customers taken to do this? Are there any docs / guides?

There is a guide how to migrate between different versions of Starcounter with Unload/Reload, but it does not discuss anything related to database configuration.


> Aha, Thanks for the info, I was thinking of upgrading another of my Live server to 2.3 :P
> Good thing I tried it on a Non-Live server.

It is always good thing to try on a non-live server in any migration, not only in this particular case.

**Comment by dan31** [comment]
@atifwaqar 2.3 will become a stable release likely in August. Hence, we do not recommend to migrate now, since there is no migration guide ready and non of us ready to help with migration. Let's migrate when it is ready. When migrating from 2.2 to 2.3, one has to unload all data and reload it to a new 2.3 installation, since the data storage format is completely changed in 2.3. We are thinking to give that an automatic form on the installer. But this doesn't actually change a situation - one has to unload and reload data.

In your case, moving to 2.3 doesn't give any difference, because you still need to unload and reload data. Currently I strongly recommend to always have a tool/code/batch file that extracts data from your database and reloads it into the new database. Hence you will always have the means to reflow the data on necessity. Then to adjust to memory size change you unload the data from the database, recreate the database and reload the data into the newly created database.

**Comment by atifwaqar** [comment]
Thanks @dan31 . I see your point. We can wait till 2.3 becomes stable.
