### ISSUE TITLE
Patches from server side arrive in wrong order

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3692]
I have the following scenario:

- Client establishes puppet connection.
- User clicks a link.
- Puppet morphs the link.
- Server receives a GET request.
- Launcher catches the request.
- Launcher creates a new workspsace.
- Handler for the GET invoked.
- Handler does some changes in the workspace.
- Handler calls `Session.Current.CalculatePatchAndPushOnWebSocket()`.
- **Server generates patch for the change and sends over web socket.**
- **Client tries to apply patches to a non-existing workspace.**
- **Handler call finishes and server responses with JSON patch to create the workspace.**

@chrhol is it a bug or I am trying to make something I should not?

**Comment by chrhol** [comment]
When it comes to pushing changes and having changes sent over http, patches can come out of order. If they are received out-of-order, the client and server will wait until the previous patches arrives before applying them. However if they are sent out-of-order (i.e. the push is handled before the response from the GET request is finished), then you will get this kind of behaviour

How does the code look that does the pushing? If the push is scheduled, it should be executed after the request is finished (since we lock access to the whole session).

**Comment by tomalec** [comment]
@miyconst They are received in wrong order, but are they applied in wrong order (I'm asking for jsonpatch, not for polymer)

I suspect it might be an issue we described recently with @joozek78, that `puppet-polymer-client` may notify Polymer in receive order, not in apply order.

**Comment by miyconst** [comment]
It does not look to be related to the Polymer. Here is the stack trace of the exception. Seems like PuppetJs applies patches once they received over websocket.

![image](https://cloud.githubusercontent.com/assets/6435556/15928206/df97187e-2e45-11e6-812b-9195b52769f2.png)

**Comment by tomalec** [comment]
It's not applying but it's marking parents, https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L638-L651 should be moved to queue callback as well. But AFAIK, we are going to remove `markObjPropertyByPath` anyways - https://github.com/PuppetJs/PuppetJs/issues/79

**Comment by miyconst** [comment]
Thanks @tomalec, I close this issue in favor to https://github.com/PuppetJs/PuppetJs/issues/79.
