### ISSUE TITLE
Unable to retrieve a struct object via DbHelper.FromID

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3766]
The `DbHelper.FromID` method returns `IObjectView` which is not possible to cast to `struct` type. This makes it impossible to get items from `struct` tables.

```cs
[Database]
public class ClassItem {
    string Name { get; set; }
}

[Database]
public struct StructItem {
    string Name { get; set; }
}
```

```cs
ClassItem ci = DbHelper.FromID(0123) as ClassItem; // This works.
StructItem si = DbHelper.FromID(0123) as StructItem; // This does not compile.
```

```
Cannot convert type 'Starcounter.IObjectView' to 'StructItem'
```

cc @chrhol, @k-rus

**Comment by k-rus** [comment]
I don't know anything about struct tables. Where are they described?

**Comment by miyconst** [comment]
I didn't see any specific documentation about `struct`, but this is just another type in c#, and it is supported to declare `[Database]` structs.

**Comment by k-rus** [comment]
Then structs are not supported. Probably, weaver sees them as classes and to reject them some specialisation in implementation is needed. cc @per-samuelsson

**Comment by miyconst** [comment]
Hm, that would be a penalty in my case, right now they are widely used in the Palma project.

**Comment by bigwad** [comment]
Declaring structs as a database type is not supported according to [Database attribute declaration](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/DatabaseAttribute.cs#L15).
So, you should have compilation error declaring such type in the first place.

It would be strange if it was permitted because it would break expected struct behaviour. Here I mean that when you assign one struct-typed variable to another - you effectively make an independent copy: 
```
    struct a
    {
        public int i;
    }
        a x = new a { i=0 };
        a y = x;
        x.i = 1;
        //y.i - still equals to 0
```
Given it's a database struct, what would you expect - creating a new object in the database each time you pass a struct as a parameter? Unlikely. Then both structs will refer to the same underlying database object thus breaking structs expectations and becoming the class de facto.

**Comment by miyconst** [comment]
@bigwad thank you for the answer. I missed this one out, and it looks like the structs are not `[Database]` types, they only access database inside property getters.

Closing this issue as invalid.

**Comment by k-rus** [comment]
I think the correct behaviour will be to get error when database attribute is defined on structs, instead of accepting. I will re-open the issue to see what @per-samuelsson think about it.

**Comment by miyconst** [comment]
@k-rus it was my mistake, it is not allowed.

```
Attribute 'Database' is not valid on this declaration type. It is only valid on 'assembly, class, interface' declarations.
```

**Comment by k-rus** [comment]
I see. I missed that you actually got the error.
