### ISSUE TITLE
Starcounter sample apps do not work in Edge 38.14393 (Windows 10 Anniversary Update)

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3785]
Starcounter apps doesn't work in latest edge browser. The window is blank (nothing renders) and the following error is logged in console:
> NotSupportedError
> webcomponents.js (1765,20)

See attached screenshot:
![image](https://cloud.githubusercontent.com/assets/6013217/17586878/beb25ef6-5fc4-11e6-85e4-8da6dccdab1b.png)
(I suspect that 404 is unrelated, but I'm not sure)

**Comment by k-rus** [comment]
As I heard Win10 anniversary update does not really work well even without Starcounter. Microsoft has many problems with this update, thus I am wonder if this issue related to Starcounter or Microsoft.

**Comment by joozek78** [comment]
Example polymer apps work in this version, only SC apps do not. So I guess
there's at least a little bit of guilt on our side ;)

**Comment by warpech** [comment]
@tomalec Could you please take a look?

**Comment by warpech** [comment]
Of course when you are back from vacation 🌴

**Comment by warpech** [comment]
Seems to be deeply related with webcomponentsjs or Polymer, because I could isolate it to a four-line jsFiddle: https://github.com/webcomponents/webcomponentsjs/issues/575

**Comment by warpech** [comment]
@k-rus was right. It is an Edge problem and was fixed in one of the yesterday's updates:

- Update for Windows 10 Version 1607 for x64-based Systems ([KB3176936](https://support.microsoft.com/en-us/kb/3176936))
- Cumulative Update for Windows 10 Version 1607 for x64-based Systems ([KB3176934](https://support.microsoft.com/en-us/kb/3176934))

Thanks @joozek78 for reporting and evaluating this!
