### ISSUE TITLE
Question : How indexing can be optimized?

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3805]
I have a query : 
```
decimal value = Db.SQL<decimal>("SELECT Sum(s.MediaCost) FROM AdFenix.Database.Stats s WHERE Parent=? OR AdSetParent=?", this, this).First;
```

and my Index is :
```
Starcounter.Db.SQL("CREATE INDEX StatsIndex ON AdFenix.Database.Stats (Parent,AdSetParent,MediaCost)");
```

Is this the correct way of indexing? 
or should i have 2 indexes like following : 
```
Starcounter.Db.SQL("CREATE INDEX StatsIndex ON AdFenix.Database.Stats (Parent,AdSetParent)");
Starcounter.Db.SQL("CREATE INDEX StatsMediaCostIndex ON AdFenix.Database.Stats (MediaCost)");
```

**Comment by k-rus** [comment]
Thank you for the question. Query execution can use only one index on a table. Thus defining second index will not help to improve the same query execution. Furthermore, the index on aggregated valued cannot really give any improvements, since aggregate needs to iterate over all values to calculate the result, i.e., you don't need to include `MediaCost` in any indexes.

The order of columns in a compound index depends on the column selectivity. If the condition on `Parent` is more selective (finds less records/filters more records) than the condition on `AdSetParent`, then your index is correct. If it is opposite, i.e., the condition of `AdSetParent` filters more records than `Parent`, then the order of columns in the index should be opposite.

By the way, current implementation of `SUM` in the current Starcounter version is not efficient. It might be more efficient to use LINQ. At least @miyconst experiences this and created benchmark about this.

In general, aggregate on a large set of records (i.e., the query is not selective) will never work fast. i don't know how many records is found by the query and cannot say if it is your case or not.

**Comment by atifwaqar** [comment]
@k-rus Thanks for the detailed info. I had no idea about this. Also, I was having performance issue in `SUM`

Thanks again

**Comment by miyconst** [comment]
@atifwaqar make sure to cast your value to `decimal?` when using `Sum` otherwise it will throw an exception if there are no items.

Like this:

```cs
decimal? sum = rows.Sum(x => (decimal?)x.Amount);
```

**Comment by atifwaqar** [comment]
@miyconst Thanks

**Comment by bigwad** [comment]
@miyconst, are you sure about that?

Sum() should return zero on empty sequence and I expect conversion to decimal? to slow down calculation significantly due to boxing/unboxing.

**Comment by miyconst** [comment]
@bigwad you are right, only `Min` and `Max` throws `System.InvalidOperationException: Sequence contains no elements` exception. The `Sum` returns `0`.

@atifwaqar please ignore my comment, you don't have to cast it to `decimal?` when calculating the sum value.

**Comment by atifwaqar** [comment]
I dont understand when you guys say 

> The Sum returns 0.

For me when I run a query with sum in it I get results

![image](https://cloud.githubusercontent.com/assets/4388707/18005782/73014e48-6b9c-11e6-8c2f-e5ee104d8656.png)

**Comment by miyconst** [comment]
@atifwaqar we are talking about the LINQ `Sum` function, how it behaves if the collection is empty.

**Comment by atifwaqar** [comment]
@miyconst Thanks, got it

**Comment by k-rus** [comment]
@atifwaqar Let us know if you have more question, or we can close the issue.

**Comment by atifwaqar** [comment]
@k-rus My questions are answered. Thanks for asking.
I'll close this question/issue now.
