### ISSUE TITLE
Order of execution in middleware

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3810]
It seems that the `Application.Current.Use` middleware in Starcounter executes in the reverse order of registration. Perhaps it is because of [this line](https://github.com/Starcounter/Starcounter/blob/21345582673c882eef81f59d77be47f4440b3731/src/Starcounter.Internal/Handle.cs#L482);

In other system, middleware executes in the order of registration:

## ExpressJS

ExpressJS [executes the middleware in the order of registration](https://derickbailey.com/2016/05/09/in-what-order-does-my-express-js-middleware-execute/)

## Rails

Middleware is added at the bottom of the middleware stack. There is API to manually force a custom order. See: http://guides.rubyonrails.org/rails_on_rack.html

Notable commentary in [a blog post](https://wincent.com/wiki/Rails_and_Rack_middleware):

> it may appear at times that *the effective execution order is reversed*, depending on how you look at it. This is because each piece of middleware is being called by the item before it in the stack, and ends up doing a `call` on the next item in the stack. So while "earlier" items in the stack start before "later" items, "later" items *finish* before "earlier" ones.

## Slim

Same applies in [Slim Framework](http://www.slimframework.com/docs/concepts/middleware.html). Middleware code called after the `next()` method seems to execute in order of registration. The code called after the `next()` method seems to execute in the reverse order of registration.

## Starcounter

The main difference may be that `Application.Current.Use` does not expose the `next()` delegate. [`MimeProvider`](https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Middleware/MimeProvider.cs) has a `Next` delegate, but it seems at different level than expected. There are places in [Launcher](https://github.com/StarcounterPrefabs/Launcher/blob/4acea897480a86cdffdcad24d057dfa397d555ea/src/Launcher/Helper/LauncherHelper.cs#L25) or [SignIn](https://github.com/StarcounterPrefabs/SignIn/blob/6c22967f540b723c9d54ff92d038a597b8abdd01/src/SignIn/Api/MainHandlers.cs#L29) that call `Use` directly.

@per-samuelsson WDYT?

cc @chrhol

**Comment by per-samuelsson** [comment]
> @per-samuelsson WDYT?

I need to spend a little time trying to remember what design decisions we took. Just initially, this seem like a bug:

> It seems that the `Application.Current.Use` middleware in Starcounter executes in the reverse order of registration.

**Comment by per-samuelsson** [comment]
> The main difference may be that `Application.Current.Use` does not expose the `next()` delegate.

I think that was a conscious decision we took. We said we would introduce the middleware pattern in 2.x in the simplest possible fashion, just as a way to get people used to that instead of previous request- and response filters, and extend those with reusable *middleware classes*. And that we would push a more mature implementation to next big version. See [this](https://github.com/Starcounter/RebelsLounge/blob/master/uncategorized/middleware.md#important-22-implementation-detail) disclaimer.

Do you think we need to revise that?

**Comment by warpech** [comment]
I am fine with no presence of `next()`, but I think it makes big sense to fix the order of execution now, if you agree that this is a bug.

Thanks!

**Comment by per-samuelsson** [comment]
> I am fine with no presence of next(), but I think it makes big sense to fix the order of execution now, if you agree that this is a bug.

I've now set up a test, and can confirm your finding:

```cs
app.Use((req) =>
{
    // Keep invoking filters
    return null;
});

app.Use((req) =>
{
    // Filters down the line should not be invoked
    return new Response() { StatusCode = 200, StatusDescription = "I'm on it!" };
});

app.Use((req) =>
{
    // This is bad
    return new Response() { StatusCode = 500, StatusDescription = "Shouldn't be invoked" };
});
```

In an application with that setup, 500 is returned (i.e. from the last registered handler) and handlers above are never invoked. That's clearly a bug.

Since actually invoking middleware delegates still build on the legacy implementation (request- and response filters), the bug is inherited from there, and hence I must verify with someone if there is a reason for this.

I'll assign it to me to try fixing it, and I will also test and verify usage of middleware built on response-filters. Those should adhere to the same principle.

**Comment by per-samuelsson** [comment]
>I'll assign it to me to try fixing it ... 

Done.

> [...] and I will also test and verify usage of middleware built on response-filters. Those should adhere to the same principle.

Also done.

Both pushed to `develop` in merge https://github.com/Starcounter/Starcounter/commit/316bd052a8d01016928b761fd92303e4a052b1fb.

@warpech, I'm closing this as fixed. Feel free to reopen it if you don't find it working and/or sufficient.

**Comment by per-samuelsson** [comment]
Now also pushed to **pnext**.

**Comment by warpech** [comment]
Thanks a 💯 !
