### ISSUE TITLE
ResourceDir locked

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3853]
@thebrauer sometimes has problems with git pull -rebase when he has changed web resources loaded with e.g. --resourcedir="..\..\wwwroot"
Working dir for the debug process=bin\debug 

If his local changes needs to be rebased on changes from origin, git will first reset to the previous commit. Meaning that his local web resources will be removed from his working directory. Then git will reapply these files meaning creating them again as a child commit to the one fetched from origin.

**What are the rules for file/directory lock of the resources loaded by starcounter?**
I could fully understand if it was always locked, but @thebrauer claims that most of the time this operation succeeds .

Even stranger is that we used to have the working dir to the project root (not bin\debug) and the wwwroot would be loaded automatically. When we worked like this @thebrauer says that this error never occurred.

**Comment by dan31** [comment]
@careri thanks for your question! @alemoi could you please follow up?

**Comment by alemoi** [comment]
I have just tested with simple Launcher application and resource directory becomes locked (e.g. you can't delete or rename it) once at least one file was served from it.

I just wrote an independent console application that uses `FileSystemWatcher` to observe some files, and upper directory becomes non-movable (can't rename or delete).

I guess the reason why it was so random in your case, because it depends if any file was accessed and observed, because the first `FileSystemWatcher` call is made only when the actual file is accessed on the disk.

**Comment by alemoi** [comment]
Here is the note I wrote about locking: http://starcounter.io/guides/network/static-file-server/#directory-locking

**Comment by careri** [comment]
Ok, thanks. That clarifies things
