### ISSUE TITLE
Question : Is there a way to restart an App without Unloading and Reloading DB

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3857]
Here is what I am experiencing : 
1. I have 4 apps up and running. I can see it in SC Admin Panel.
2. I have tiny logic changed in 1 app (Adfenix app). by logic change I mean change in some algorithm, not in DB Schema.
3. I press the stop button for AdFenix app only

Note : On my Live server I have a DB of 60 GB
1. The DB is unloaded from RAM. (Dont know the exact wording for this. What I notice is that in Task manager RAM gets freed up. and then starts filling again.)
2. After the Ram is filled up, the AdFenix app disappears from SC Admin Panel.
3. I run the executable AdFenix.exe 

Now this whole process takes 5-8 min. Is there any shorter/quicker way of handling this?

**Comment by per-samuelsson** [comment]
@atifwaqar 

> Is there any shorter/quicker way of handling this?

I'm afraid there is not. Not in our 2.x versions. The reason for this is because how our hosting model in those versions work, with a single host for many applications. To unload a version of an application, the only technical possibility is for us to terminate and respawn the process.

To bring some positive news long-term, we are aware of that this model has its drawbacks and hence we are actively discussing, and aiming at implementing, a complementary hosting model we call "self-hosted apps". It's not likely to be realized for some time yet though.

> Now this whole process takes 5-8 min.

Really sorry to hear that. We have researched those slow startup times before, but I guess we didn't come to any results that could help you.

**Comment by atifwaqar** [comment]
@per-samuelsson  Thanks for the detailed response. 
I would like to add some info here. If I stop an app (step 3 in my first comment) on my local machine, the app stops immediately without unloading the DB from RAM.
Now i'm guessing that if any function/process/handler is running from that app, the stopping process will take too much time. Am I right with this assumption?

**Comment by bigwad** [comment]
@per-samuelsson, given the required time and fact that memory usage drops, I assume entire database is restarted here. Isn't it enough to restart required application only, like:
```
star -D=<db> --stop <app_name>
star -D=<db> <app_name>
```

**Comment by atifwaqar** [comment]
```
star -D=<db> --stop <app_name>
star -D=<db> <app_name>
```
Yes, that is correct. And that's exactly what I do. But still the entire DB is restarting.

**Comment by atifwaqar** [comment]
@bigwad , I will check this tomorrow, and update you then.

**Comment by per-samuelsson** [comment]
> [..] given the required time and fact that memory usage drops, I assume entire database is restarted here. Isn't it enough to restart required application only [...]

@bigwad, good catch. I was under the impression that what took time was the code host *attaching/connecting* to `scdata` that took time, but maybe I remember wrong. 

Let me investigate this a little and get back on that.

**Comment by per-samuelsson** [comment]
> Let me investigate this a little and get back on that.

Over here, things seem to work as expected.

Starting fresh, I do

```
star myapp.exe
staradmin stop app myapp
star myapp.exe
```

That sequence will recycle the `sccode` host process, while `scdata` stays resident.

Changing that to

```
star myapp.exe
staradmin stop db
star myapp.exe
```

will instead recycle both processes. This is all by design.

Please let us know the experience you have doing this, @atifwaqar!

**Comment by per-samuelsson** [comment]
Issues related to slow-starting databases: #3481, #3494.

**Comment by dan31** [comment]
@atifwaqar I believe @per-samuelsson and @bigwad questions fully cover your question. @atifwaqar please also make sure that you and all your team members are fully accustomed to the current issue and also to a nice wrap-up from here: https://docs.starcounter.io/guides/working-with-starcounter/starting-and-stopping-apps/. Thanks!
