### ISSUE TITLE
Dynamic loading of database entities

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3890]
I tried to dynamically load an assembly from a subfolder, e.g. plugins.
The assembly is loaded as expected. But there is no weaving activated.

So my Entity1 exampel class with the Database-attribute is just a plain CLR-class with no connection to the database.

I looked through the code for DeployManager and PackageManager for the Administrator. But the example Apps don't seem to have any private database classes?

Is there any API to call for weaving and loading an assembly? I guess it's possible since the codehost can load/reload an app.

An other alternative would be to load assemblies from a subfolder during database/app start.
Say that I start my ManagerApp which in turn will look through the plugins folder and start/stop applications from that folder.

**Comment by per-samuelsson** [comment]
> Is there any API to call for weaving and loading an assembly?

Currently, there is not no. But we are busy doing some development that will change some things, see #3869 and related #3684. I'll try factor in that case when I do the rewrite.

Right now, the weaver only support application assemblies as their input. It should be possible to give it libraries as well, and if so, we could support something like you suggest. I think it still will need to be run in a separate process though, since we are tied to an old PostSharp version in 2.x. With our upcoming Roslyn-based weaver, that will improve further.

**Comment by careri** [comment]
Seems like there is some interesting stuff in the pipe.
I think for now I'll just use star.exe to start/stop additional "plugins" in the same database.

They are loaded in the same AppDomain then, right?

**Comment by per-samuelsson** [comment]
> They are loaded in the same AppDomain then, right?

Yes they are. This is to be considered an implementation detail, but I think it's very unlikely it will change, so should be safe to depend upon.

**Comment by dan31** [comment]
v2.4 is to address these. Archiving the question.
