### ISSUE TITLE
How to handle exceptions thrown in input handlers?

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3901]
```c#
void Handle(Input.Edit Action) {
    throw new NotSupportedException();
}
```

Upon triggering this handler will cause exception to be thrown and presented to client via connection error (i.e. a red box will appear telling you that your connection has broken). How can I catch this exception?

CC @chrhol @miyconst

**Comment by miyconst** [comment]
It looks like the only possible way is to wrap the insides of `Handle` function into a `try/catch` block. @chrhol might know more.

**Comment by per-samuelsson** [comment]
This question is actually quite generic. It's about how to manage exceptions raised from callbacks, and how you (as a developer) is responsible not to let it happen. There's quite a lot to read about it if you just google it.

As a platform, Starcounter *could* offer some way to intercept unhandled exceptions like this, kind of like [AppDomain.UnhandledException](https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx), but I'm not sure it's a good idea. It's generally very little one can do, since you don't know the side-effects of catching exceptions you don't know how to deal with.

@joozek78, could you elaborate a bit more on what it is you want to do, and how you think Starcounter *should* operate on exceptions slipping through callbacks (like this, or `Handle.GET`, or `Db.Transact`, etc)?

**Comment by miyconst** [comment]
The `AppDomain.UnhandledException` is not working with Starcounter :( - [CurrentDomain.UnhandledException does not work in Starcounter](https://github.com/Starcounter/Starcounter/issues/3334).

**Comment by per-samuelsson** [comment]
> The `AppDomain.UnhandledException` is not working with Starcounter :( - [CurrentDomain.UnhandledException does not work in Starcounter](https://github.com/Starcounter/Starcounter/issues/3334).

Thats not really true. It is not raised because Starcounter will need to make sure exceptions don't crash the code host, and hence need to react to them as a host. Hence, the exception raised from a callback is not technically unhandled.

Furthermore, the reference to that was not of the kind "use this". It was used as an *example*, hinting that we could support something similar. Something like `HandleInput.UnhandledException`. Not saying we will though.

**Comment by mtornwall** [comment]
In my opinion, deferring exception handling is an anti-pattern.

I suggest this pattern:

    void Handle(Input.Foo input)
    {
        Protected(() => {
            // code that might throw1
        });
    }

    void Protected(Action action)
    {
        try {
            action();
        } catch (Exception e) {
            // do viewmodel-specific handling
        }
    }

**Comment by per-samuelsson** [comment]
> In my opinion, deferring exception handling is an anti-pattern.

I agree. Exception handling are there to be used as a mean of reporting about exceptional cases. Each implementation either choose to deal with them or not. If they are not handled, Starcounter will need to make sure they don't cause the termination of the server, and can not really do anything else.

**Comment by mtornwall** [comment]
> If they are not handled, Starcounter will need to make sure they don't cause the termination of the server, and can not really do anything else.

Agreed - the current way of handling exceptions is basically the best we can do. It's up to the application developer to ensure that input handlers don't throw.

**Comment by miyconst** [comment]
>Thats not really true. It is not raised because Starcounter will need to make sure exceptions don't crash the code host, and hence need to react to them as a host. Hence, the exception raised from a callback is not technically unhandled.

**I think there are two types of the exceptions:**

- Starcounter exception. 
 - Should never occur.
 - Not possible to completely avoid.
 - Should crash session only if possible, entire database otherwise.
 - Exceptions in a database should never crash entire server.
- Application exception.
 - Expected to be thrown very often.
 - For the developers point of view is an `UnhandledException`.
 - The one developers should care about.
 - Should never crash database or server.
 - Should only crash session if not handled.
 - There should be a way to catch all unhandled exceptions.

**What we currently have is:**

- Starcounter exceptions crash entire database/server even if other parts can continue work properly.
- Application exceptions partially treated as handled, and `CurrentDomain.UnhandledException` does not work.
- Application exceptions can crash entire database instead of session.
- Application exceptions in the async tasks crash entire database/server.

>Furthermore, the reference to that was not of the kind "use this". ...

I know, just this is a very cool feature of .NET, and I would love to see it in Starcounter, that is why mentioned it once again.

**Comment by miyconst** [comment]
@mtornwall, I am sorry to say, but I really dislike your example with `Protected` method. Anything with `Action` and `Func` is extremely difficult to debug. In my opinion it is a very bad practice to define functions with `Action` or `Func` parameters, except of some exclusions of course, for example LINQ.

**Comment by mtornwall** [comment]
> There should be a way to catch all unhandled exceptions.

I'm in favor of this if the behavior is specified *locally*, e.g.:

    // Applied to view model level.
    [ExceptionBehavior(ExceptionBehavior.Explode)]
    public class FooPage : Page { /* ... */ }

    // Applied to handler level.
    [ExceptionBehavior(ExceptionBehavior.Suppress)]
    void Handle(Input.Fire input) { /* ... */ }

I think this is nicer and more explicit than installing something like a `Db.UnhandledException` event handler, or similar.

**Comment by mtornwall** [comment]
@miyconst I obviously disagree about the debuggability of anonymous functions, but I think we should have that debate offline. ;-)

I respect that many programmers do not like this style of programming, and therefore offer this as an alternative:

    void Handle(Input.Foo input)
    {
        try {
            // code that might throw
        } catch (Exception e) {
            if (!HandleException(e)) throw;
        }
    }

Where `HandleException` is some user-defined method, either in the view model or something more global.

**Comment by per-samuelsson** [comment]
FWIW, C# 6.0 shipped with new [exception filter capabilities](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#exception-filters). That along with some app-global extension method could allow a syntax such as:

```cs
void Handle(Input.Foo input) {
try {
  // User-defined handler implentation
}
catch (Exception e) when (e.WasHandled()) {}
}
```

```cs
// App- or assembly- or solution global exception handler
static class ExceptionExtensions {
  public static bool WasHandled(this Exception e) {
    // Yeah, we can handle and swallow any ...
    return true;
  }
}
```

**Comment by miyconst** [comment]
>@miyconst I obviously disagree about the debuggability of anonymous functions, but I think we should have that debate offline. ;-)

Let's do it :)
