### ISSUE TITLE
Insert a list / Bulk Insert / Insert many / Batch Insert

### ISSUE THREAD

**Issue by mandatorySuicide** [Starcounter/Starcounter#4024]
I have a handler which looks like 
`Handle.POST("/post", (Request r) =>`
`{`
           List< Data> myData = process(r.Body); 
         `// Need to save the list into my db`
         `return data.Count.toString();`
});`
How can I save all the data in myData into SC? Is there any way to bulk insert?

**Comment by per-samuelsson** [comment]
> Is there any way to bulk insert?

Currently, there is not I'm afraid. Inserting happen when you instantiate database classes within the scope of a transaction. It's hard to give a more detailed answer based on the code you provided.

Please close this if you consider it an answered question. Otherwise, let us know if you like us to discuss this matter further.
