### ISSUE TITLE
if any json field changed in the client reRead data on the server!

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4032]
if Json data fetch from Db.SQL

`PersonPage.DataArray = Db.Sql<DummyTable>("SELECT d FROM DummyTable d");`

then
if any json field (i.e DummyClick) changed in the client (if this field fetched from DB or not) reRead data on the server!

Is it intentional?
```
PersonPage
{
	Html: "",
	DummyClick$: 0,
	DataArray: []
}
```

**Comment by miyconst** [comment]
@SenerDemiral thank you for the question.

Yes. This is intentional.

Server has to gather all changes from the view-model to generate a patch for the client. This is done through dirty checking. This means that every patch from client will trigger read of every property on the server side.

If you do not want this behavior, than you have to bind your view-model to plain C# classes instead of `[Database]` classes.

**Comment by SenerDemiral** [comment]
Thanks.
