### ISSUE TITLE
When entering the home page Handle.GET returns 2 times!

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4045]
Handle.GET hits 2 times if `Application.Current.Use(new HtmlFromJsonProvider());` is used.
``` 
Handle.GET("/TTclient", () => {
	return Db.Scope(() => {
		Master master;
		if(Session.Current != null) {
			master = (Master)Session.Current.Data;
		}
		else {
			master = new Master();
			master.Session = new Session(SessionOptions.PatchVersioning);
		}
		return master;
	});
});
```
If this behavior is intentional, How to know the second/last hit/return?

**Comment by miyconst** [comment]
cc @warpech, @alemoi

**Comment by warpech** [comment]
The intentional behaviour is to use `Application.Current.Use(new HtmlFromJsonProvider());` with `Application.Current.Use(new PartialToStandaloneHtmlProvider());`. 

Then in your master HTML you don't have to include the code that handles the session (`<head>`, `<puppet-client>`, etc), because it is handled for you. 

Your master HTML should then have only the content for that page, more or less like https://github.com/StarcounterSamples/HelloWorld/blob/tutorial-20161222/src/HelloWorld/wwwroot/HelloWorld/PersonJson.html

Please let me know if that's helpful.

Note to @miyconst - this happens when `<puppet-client>` is called without the `session-url` attribute. In this case, `<puppet-client>` calls `window.location.href` URL with `application/json` header. Maybe we should switch off this behaviour and show an error instead?

**Comment by SenerDemiral** [comment]
I want to control what is loading, so my master HTML have all the startup code.
Because of that I can not using `Application.Current.Use(new PartialToStandaloneHtmlProvider())`

**Comment by warpech** [comment]
You can provide your own HTML startup code as the parameter to `PartialToStandaloneHtmlProvider()` constructor, e.g.

```cs
var html = @"<!DOCTYPE html>
<html>
<head>
    <meta charset=""utf-8"">
    <title>{0}</title>
    <script src=""/sys/webcomponentsjs/webcomponents.min.js""></script>
    <link rel=""import"" href=""/sys/polymer/polymer.html"">
    <link rel=""import"" href=""/sys/starcounter.html"">
    <link rel=""import"" href=""/sys/starcounter-include/starcounter-include.html"">
    <link rel=""import"" href=""/sys/starcounter-debug-aid/src/starcounter-debug-aid.html"">
    <link rel=""import"" href=""/sys/bootstrap.html"">
    <style>
        body {{
            margin: 20px;
        }}
    </style>
</head>
<body>
    <template is=""dom-bind"" id=""puppet-root"">
        <template is=""imported-template"" content$=""{{{{model.Html}}}}"" model=""{{{{model}}}}""></template>
    </template>
    <puppet-client ref=""puppet-root"" remote-url=""{1}""></puppet-client>
    <starcounter-debug-aid></starcounter-debug-aid>
</body>
</html>";
Application.Current.Use(new PartialToStandaloneHtmlProvider(html))
```

**Comment by miyconst** [comment]
>Note to @miyconst - this happens when `<puppet-client>` is called without the `session-url` attribute. In this case, `<puppet-client>` calls `window.location.href` URL with `application/json` header. Maybe we should switch off this behaviour and show an error instead?

Sounds like a good idea to me.

**Comment by SenerDemiral** [comment]
Thank you,
I will try as you suggested.

**Comment by warpech** [comment]
I have created an issue to discuss changing this: https://github.com/PuppetJs/PuppetJs/issues/117

Thanks @SenerDemiral for the report! Please reopen if something does not work as expected.
