### ISSUE TITLE
How to get Client IP address if Reverse Proxies used?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4047]

**Comment by warpech** [comment]
cc @alemoi?

**Comment by alemoi** [comment]
@SenerDemiral thank you for the question. Can you please describe your application design and what you are trying to achieve?

In general here is the list of possible ways: http://security.stackexchange.com/questions/36420/how-can-a-website-find-my-real-ip-address-while-im-behind-a-proxy

**Comment by SenerDemiral** [comment]
I have experimental site [www.masatenisi.online](url) about table tennis team tournaments.
I am using Starcounter 2.3 and can not change Http port!
And yet didn't convert 2.4 which in Http port can be changed.
I tried to change port 8081 to 80 using Proxies and I need Client IP address.

**Comment by andwah** [comment]
It is possible to change the port by open the configuration file and manually edit the port number tag `<DefaultUserHttpPort>8080</DefaultUserHttpPort>`

The configuration file is located in your database repository

`c:\Users\someuser\Documents\Starcounter\Personal\Databases\yourdatabasename\yourdatabasename.db.config`

After you saved the configuration file you need to restart starcounter.

**Comment by SenerDemiral** [comment]
Thank you. I got the message.

**Comment by warpech** [comment]
@SenerDemiral anything you think should be added to https://docs.starcounter.io/guides/network/network-gateway.html?

**Comment by SenerDemiral** [comment]
Thank you for your attention.
I think following sentence strengthen the subject.
Network gateway process listen port defined by Http Port parameter of database.
In Web Administrator http://127.0.0.1:8181/#/databases/DatabaseName/settings

**Comment by warpech** [comment]
@Mackiovello I think that this is a fair point. The above topic (how to configure the HTTP port bound to a database) should be explained on https://docs.starcounter.io/guides/database/database-configuration.html

It is (too) briefly mentioned at https://docs.starcounter.io/guides/working-with-starcounter/administrator-web-ui.html, but Administrator is just a UI to the configuration, so this must be covered in configuration.

Also, it would be good to add cross links between pages:

- https://docs.starcounter.io/guides/database/database-configuration.html
- https://docs.starcounter.io/guides/network/network-gateway.html
- https://docs.starcounter.io/guides/working-with-starcounter/administrator-web-ui.html

So that the people get a better feeling that there are two things to configure (the databases and the gateway) as well as two ways to configure (XML files and Administrator).
