### ISSUE TITLE
Typo in the exception text: One of more of the languages the database

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4052]
The exception text says:

>ScErrDatabaseLangUnsupported (SCERR2023): One **of** more of the languages the database is configured for isn't supported by the current system.

It should be:

>ScErrDatabaseLangUnsupported (SCERR2023): One **or** more of the languages the database is configured for isn't supported by the current system.

cc @k-rus

**Comment by miyconst** [comment]
Discovered from - [pnext: `Personal.server.config` is not updated when upgrading Starcounter versions](https://github.com/Starcounter/Starcounter/issues/3343).

**Comment by k-rus** [comment]
I don't know anything about the error. Looking into the other issue, I can understand the error, but I don't understand why I am explicitly mentioned for the issue. 

The type can be fixed by anyone who has access to Level1 source code and knows how to fix it. I guess the fix should be done in v2.3 and develop branches. It is important to run personal build before pushing changes to main branches to avoid unintended mistakes.

**Comment by miyconst** [comment]
>... but I don't understand why I am explicitly mentioned for the issue.

Sorry, I thought it is some sort of SQL exception.

@alemoi could you please fix it?

**Comment by alemoi** [comment]
Sure. Not my area either, but I will fix the texts!

**Comment by miyconst** [comment]
Thanks.

**Comment by alemoi** [comment]
Done.
