### ISSUE TITLE
HtmlFromJsonProvider doesn't show any error when you don't provide "Html"

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#4115]
When you take https://github.com/StarcounterSamples/HelloWorld and change the property at line 

https://github.com/StarcounterSamples/HelloWorld/blob/tutorial-20161222/src/HelloWorld/PersonJson.json#L2

from `Html` to `html`, accessing `localhost:8080/helloworld` shows an empty page with no error message.

This of course applies to all apps, but Hello World might be the simplest way to reproduce the problem.

Spotted by @jwillmer.

**Comment by warpech** [comment]
The above applies only when the page is wrapped by Launcher or Website app:

![2017-03-02 17_54_17-helloworld](https://cloud.githubusercontent.com/assets/566463/23517664/510b4f50-ff71-11e6-9873-f39390930b88.png)

**Comment by warpech** [comment]
@un-tone could you please check if the same problem is reproducible with the Website app?

**Comment by un-tone** [comment]
@warpech yes, it is reproducible with the Website app too

**Comment by per-samuelsson** [comment]
Guess it's as simple as [this access pattern](https://github.com/Starcounter/Starcounter/blob/81c9a245f2f3769cb19bb2e2ad0c3d69a14b19b8/src/Starcounter/Middleware/HtmlFromJsonProvider.cs#L36) is case-sensitive, no?

@chrhol ?

**Comment by warpech** [comment]
I think that the problem is not really in case sensitivity, but in failing fast. 

If Launcher/Website app is not wrapping the response then the user sees a nice shiny stack trace. Launcher/Website replaces the stack trace with an empty page.

@un-tone could you investigate if Website app could skip wrapping the app in case it is not a Json but a text stack trace?

**Comment by un-tone** [comment]
@warpech it can

**Comment by warpech** [comment]
Pls make a PR for this in the Website app and then lets see, maybe that is a solution.

**Comment by un-tone** [comment]
_(I tested **Website** with **People** app)_

The **HtmlFromJsonProvider** instance defined in the **People** app validates the JSON object which is already a **WrapperPage** object created by **Website**. In this case the JSON object is correct since it has a valid `Html` field, so the app doesn't throw an exception.

In this PR https://github.com/StarcounterApps/Website/pull/57 I added response filter which validates a JSON object recieved from an application before it is beeing wrapped by **WebsiteProvider.** For tests I changed this line https://github.com/StarcounterApps/People/blob/master/src/People/ViewModels/StandalonePage.json#L2.

Currently the **HtmlFromJsonProvider** checks the "Html" field only in the root of a JSON object and it is a correct behavior in my point of view.

**Comment by warpech** [comment]
If some app exposes a REST API, then in fact you would want to return a JSON response without `Html` property. 

So I think that a desired solution to https://github.com/Starcounter/Starcounter/issues/4115#issuecomment-285066563 would be to make WebsiteProvider wrap only reponses that are of type `Json` and have `Html` property.

If your response is not `Json` or it is a `Json` without a `Html` property, WebsiteProvider should be bypassed.

WDYT @un-tone?

**Comment by un-tone** [comment]
It is exactly a better approach. Thanks @warpech. I updated the PR.

**Comment by warpech** [comment]
Great, thanks!

As it turned out, this was a problem in Launcher & Website, not in HtmlFromJsonProvider.

@un-tone has fixed the problem in Website. I don't think it is needed to fix in Launcher, because Launcher is being phased-out.
