### ISSUE TITLE
Bamboo

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#43]
Setup Bamboo

Getting started with simple Bamboo setup.

**Comment by dan31** [comment]
So far TeamCity is a way better option.

**Comment by per-samuelsson** [comment]
> So far TeamCity is a way better option.

Minus that we still don't have guarded commits / push-triggered personal builds. Which is quite a large drawback still. And that was the entire reason we once decided to try Bamboo out, but we didn't find the time to make the switch properly.

**Comment by k-rus** [comment]
I fully agree with @per-samuelsson 
We have problem that developers commit their changes directly to main branch and sometimes break the builds with further negative outcome for other developers. It was promised that the commit guard will be in place as soon we can allocate resources.

**Comment by dan31** [comment]
Since TC 9.x there is similar function: https://confluence.jetbrains.com/display/TCD9/Pre-Tested+(Delayed)+Commit. I don't see a difference from what was observed before in Bamboo, hence I think the issue now is not connected to Atlassian products at all. Once we have a volunteer with spare time, it will definitely be introduced by this brave person.
